### ISSUE TITLE
Pull Requests - Activation Layers

### ISSUE THREAD

**Issue by conceptofmind** [patrick-kidger/equinox#102]
Hi Patrick,

I wanted to get your thoughts on adding activation layers to Equinox's API. Similar to how Pytorch has torch.nn.ReLU().

For example a basic GELU class example:

```python
class GELU(Module):
    approximate: bool = static_field()

    def __init__(self, approximate: bool = False):
        super().__init__()
        self.approximate = approximate

    def __call__(self, x, *, key = None):
        if self.approximate:
            sqrt_2_over_pi = jnp.sqrt(2 / jnp.pi).astype(x.dtype)
            cdf = 0.5 * (1.0 + jnp.tanh(sqrt_2_over_pi * (x + 0.044715 * (x ** 3))))
            return x * cdf
        else: 
            return jnp.array(x * (lax.erf(x / jnp.sqrt(2)) + 1) / 2, dtype=x.dtype)
```

If this is something you think would be beneficial I can open up a pull request with added documentation.

Thank you,

Enrico

**Comment by patrick-kidger** [comment]
Have discussed this separately. Posting the solution for anyone else coming across this:

```python
from typing import Callable
import equinox as eqx
import jax.nn as jnn

class Lambda(eqx.Module):
    fn: Callable

def __call__(self , x, *, key=None):
        return self.fn(x)

...

eqx.nn.Sequential([
    eqx.nn.Linear(...),
    Lambda(jnn.gelu),
    eqx.nn.Linear(...),
])
```

**Comment by mfouesneau** [comment]
I followed your example and when I try
`loss, grads = value_and_grad(loss_fn)(model, x)`
I get a TypeError:
`TypeError: Argument '<function gelu at 0x7b51a1fd23b0>' of type <class 'function'> is not a valid JAX type.`

(I can evaluate the `loss_fn(model, x)` without error)

**Comment by patrick-kidger** [comment]
If your `model` includes non-JAX-types (does it?) then try either using `eqx.filter_value_and_grad`, or partitioning/combining. See [here](https://docs.kidger.site/equinox/all-of-equinox/#2-filtering).

**Comment by mfouesneau** [comment]
yes thanks. answered in  #706
