### ISSUE TITLE
Feature request: Equinox version of `optax.incremental_update(...)`

### ISSUE THREAD

**Issue by callumtilbury** [patrick-kidger/equinox#110]
Hey again @patrick-kidger :)

Would you be willing to introduce an Equinox version of `optax.incremental_update` (-> `equinox.update.incremental_update`), in the same way you have done for `optax.apply_updates` (-> `equinox.update.apply_updates`)? i.e. Use the same process of applying a `tree_map`, but checking for `_is_none`, so that we can pass in a filtered PyTree.

I have already written code for this (which I can PR) but I understand if you'd prefer to minimise code bloat. If it's not in core Equinox, I'll just implement it elsewhere for my use-case.

Thanks!

**Comment by patrick-kidger** [comment]
Hey again! So on balance I'd prefer to leave this out -- `eqx.apply_updates` covers 99% of use cases, but more than this and we'll find ourselves wrapping a substantial portion of the Optax API.

**Comment by callumtilbury** [comment]
Completely understand that! Thanks 💯
