### ISSUE TITLE
Lack of `out=` breaks use of `filter_pmap(fn)` when output of `fn` involves non-JAX types

### ISSUE THREAD

**Issue by jatentaki** [patrick-kidger/equinox#115]
The repro is [here](https://colab.research.google.com/drive/101ZT_F2_iCzRnh85Z_3_3hD4zQfJrWci?usp=sharing). In short, functions which return PyTrees involving non-JAX types break `filter_{vmap,pmap}`. With `vmap` this can be fixed by specifying the `out=` kwarg, but it doesn't work for `pmap`. Is this just a TODO or a limitation of the "networks as callable PyTrees" model that equinox takes?

**Comment by jatentaki** [comment]
I just realized this can be solved by making the `non_jax` with `equinox.static_field()`; however this is a technique I only learned from reading the source, I don't think it's discussed in the docs?

**Comment by jatentaki** [comment]
In particular, `pmap` is broken for `eqx.nn.MLP` due to nonlinearities [not having been declared as static](https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/composed.py#L30).

**Comment by jatentaki** [comment]
Thanks for your reply, I think I understand your rationale for this design. Still, it sounds at odds with my mental picture of parallel training. This is my first attempt at that in JAX, but as I mentioned in the previous issue, I believe the way to [train on multiple GPUs](https://jax.readthedocs.io/en/latest/jax-101/06-parallelism.html#example) is to shard-replicate the model and optimizer state across GPUs, shard-split the training batch, insert `grad = jax.lax.pmean(grad, axis_name='device')` inside the `update` function and then `pmap` it. This means the example I linked above only differs from ensambling models by the `pmean` operations inside, which is obviously orthogonal to the issue we're discussing here. Therefore my use-case is indeed similar to ensambling models and since my `update` returns an entire neural network (with all non-array leaves it may have) I need to filter that.

What would be your approach to parallel training with `pmap`? To `pmap`-reduce the gradient computation, perform model update on a single GPU and then broadcast the updated model? I'm not very confident with equinox but I have the impression that I would also run into that kind of problems there.

Since making this issue I noticed that using `static_field` indeed breaks some things downstream, so I experimented with pre-computing a non-callable `out=` value. This should be possible since my output signature is known ahead of time, but for some reason JAX complains about structure mismatch...

```python
_0_if_array = lambda v: 0 if eqx.is_array(v) else None
mask = jax.tree_map(_0_if_array, v_model)
eqx.filter_vmap(fn, out=mask)(v_model)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [61], in <cell line: 1>()
----> 1 eqx.filter_vmap(fn, out=mask)(v_model)

File ~/Programs/equinox/equinox/vmap_pmap.py:146, in _VmapWrapper.__call__(***failed resolving arguments***)
    144 else:  # `out` of type ResolvedAxisSpec
    145     out_axes = _map_axes(__self._out)
--> 146 vmapd, nonvmapd = jax.vmap(
    147     _fun_wrapper, in_axes=in_axes, out_axes=out_axes, **__self._vmapkwargs
    148 )(__self._fun, bound.args, bound.kwargs)
    149 return combine(vmapd, nonvmapd.value)

    [... skipping hidden 5 frame]

File /opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/jax/_src/api_util.py:310, in flatten_axes(name, treedef, axis_tree, kws, tupled_args)
    306       else:
    307         hint += (f" In particular, you're passing in a single argument which "
    308                  f"means that {name} might need to be wrapped in "
    309                  f"a singleton tuple.")
--> 310   raise ValueError(f"{name} specification must be a tree prefix of the "
    311                    f"corresponding value, got specification {axis_tree} "
    312                    f"for value tree {treedef}.{hint}") from None
    313 axes = [None if a is proxy else a for a in axes]
    314 assert len(axes) == treedef.num_leaves

ValueError: vmap out_axes specification must be a tree prefix of the corresponding value, got specification Model(
  linear=Linear(weight=0, bias=0, in_features=3, out_features=3, use_bias=True)
) for value tree PyTreeDef((CustomNode(<class '__main__.Model'>[(('linear',), (), ())], [CustomNode(<class 'equinox.nn.linear.Linear'>[(('weight', 'bias'), ('in_features', 'out_features', 'use_bias'), (3, 3, True))], [*, *])]), CustomNode(<class 'equinox.compile_utils.Static'>[((), ('value',), (Model(
  linear=Linear(
    weight=None,
    bias=None,
    in_features=3,
    out_features=3,
    use_bias=True
  )
),))], []))).
```

**Comment by jatentaki** [comment]
More poking around: is it intended that [here](https://github.com/patrick-kidger/equinox/blob/main/equinox/vmap_pmap.py#L145) you don't return an extra `None`, to broadcast the `Static(nonvmapd)` part of `_fun_wrapper`?

**Comment by patrick-kidger** [comment]
`filter_pmap`: ah, I see what you're getting at. Good point - that's also a reasonable way to do parallel training, so ideally `filter_pmap` should support this. I'll definitely have a look at switching things up to make these use cases work.

As for the error you're seeing, and you comment about the missing `None`: I think you're correct; there's a missing `None` and that's what raising the error you're seeing.
