### ISSUE TITLE
Automatically compile dependant Equinox modules

### ISSUE THREAD

**Issue by Atlis** [patrick-kidger/equinox#125]
Hi @patrick-kidger! (I forgot the greatings and made an edit for it as I think it is very important. Thanks for this work btw!)
I'm using a pattern which can be summarized by the minimal example herein. If I uncomment one of the two commented line (but not both simultaneously) it fails with `TypeError: unhashable type: 'DeviceArray'`.  In other words, it works only in two ways:
 - if *all* Equinox modules are *not* compiled or;
 - if *all* Equinox modules are explicitly compiled with `jax.jit()`

With a similar pattern in PyTorch, I would only have to compile `SecondModule`. `FirstModule` would be compiled automatically because it is an input to `SecondModule`.

Would there be a simple solution to obtain the same behavior has in Pytorch?

Thank you!

``` python
import equinox as eqx
import jax


class FirstModule(eqx.Module):

    params: float

    array: jax.numpy.ndarray

    def __init__(
        self,
        param: float,
    ):
        self.params = param
        self.array = jax.numpy.array([param])

    def __call__(self, x):
        return self.array + x


class SecondModule(eqx.Module):

    first_module: FirstModule

    def __init__(
        self,
        first_module: FirstModule,
    ):
        self.first_module = first_module

    def __call__(self, x):
        return self.first_module(x)


first_module = FirstModule(param=0.1)
# first_module = jax.jit(first_module)

second_module = SecondModule(first_module=first_module)
# second_module = jax.jit(second_module)

out = second_module(jax.numpy.array([1.0]))

print(out) # Expected: [1.1]

```

**Comment by patrick-kidger** [comment]
Short version: use `eqx.filter_jit(second_module)` and this will just work.

But I'd note that this is quite an uncommon pattern. When using JAX then you should JIT *every* JAX operation (for speed) and so the usual pattern is to have a single JIT'd `make_step` function, that computes the loss and the gradients and updates your model, all in one go. (Assuming you're training a neural network.) Have a look at the "train RNN" example in the docs.

As for why this works. When you JIT-compile a callable, then JAX uses a dictionary to map the callable to its compiled version. This of course implies that the callable must be hashable. Functions are callable, but the hash of an Equinox module is defined as the hash of all of its leaves. (Essentially `hash(jax.tree_leaves(module))`.) And if any of those leaves are JAX arrays then you get the error you've seen: JAX arrays aren't hashable.

`eqx.filter_jit` is essentially just a bit smarter: it knows to filter out JAX arrays before computing the hash. (And then treats those JAX arrays as an input to the compiled function.)

**Comment by Atlis** [comment]
Hi Patrick,
You are right indeed. Using `eqx.filter_jit()` on the last module instead of using `jax.jit()` makes it work, and about 33% faster. However, I took much longer to answer because it seems the two methods yields slightly different results. I don't run NN for the moment. Instead I run a RK4 to simulate a mechanical system. Precision is key here. I find that using 'jax.jit()' yields the analytical (expected) result, while `eqx.filter_jit()` does not. Do you have any idea of what could be wrong here before I make any attempt to replicate the issue with a minimal example?
Thanks!

**Comment by patrick-kidger** [comment]
Haha, I'm glad to hear you're enjoying using JAX and Equinox!

On the difference between `jax.jit` and `eqx.filter_jit`, this does sound unusual, and I don't know of something that could trip things up like that. If you can post a MWE that'd be great. (Of anything demonstrating the difference between them,  even if it's not mathematically a diffeq solver.)

In passing, RK4 is an "okay" method but for slightly more computational cost something like Tsit5 is usually better.

**Comment by Atlis** [comment]
Oh! I see. You are the co-author of Diffrax too! Wow! I'll go deeper into it. Same as your thesis. I'm curious.

By "Precision is key", I essentially meant that obtaining expected results is important (and... obviously). RK4 may not be the most precise solver out there indeed. I'll check into Tsit5 (I see its implemented in Diffrax). I never heard of it before. Thanks for that.

Now, I'm starting to understand the problem. From what I can tell:
-  **case 1**: where `eqx.filter_jit()` is applied on the last module of my pattern
**is not equal to**
-  **case 2**: where  `jax.jit` (or `eqx.filter_jit()`) is applied to all modules independently.

That's because there is a compartmentalization of modules when we compile them. That separation is somewhat equivalent to a copy operation applied to the inputs and outputs of the module's callable. I hope I'm being clear enough. That's just how just deep I understand it :) You probably know better.

I've not made a MWE yet, but here how I essentially solved my problem using the code I provided initially:
``` python
from copy import copy

# [...]

class SecondModule(eqx.Module):

    first_module: FirstModule

    def __init__(
        self,
        first_module: FirstModule,
    ):
        self.first_module = first_module

    def __call__(self, x):
        return copy(self.first_module(x)) # <---  I must copy the output of submodules' callable

# [...]
```

From what I can tell, with that modification, the results obtained from both cases are now equivalent. It was not necessary to do so with PyTorch. They probably do it under the hood somewhere. When you say Equinox's modules are No Magic, I like it. It forces us to develop a deeper understanding of the underlyings.

I may be wrong, but I'm temped to say that `eqx.Module()` **!=** `eqx.filter_jit(eqx.Module())` because `eqx.Module()` is lacking these copy operators. And I would argue at that point that making sure `eqx.Module()` **==** `eqx.filter_jit(eqx.Module())` is quite important. What do you think?

**Comment by patrick-kidger** [comment]
So having a copy operation there is definitely weird. I don't think it's technically wrong but it definitely shouldn't improve things for you either.

I would note that JAX(/Equinox)'s JIT operation is different to PyTorch. In PyTorch there is indeed this notion of "jitting a module" as this is a typical pattern. In contrast JAX's JIT operation is almost always applied to some standalone function, and "jitting a module" is probably a mistake. If you're new to this I'd suggest reading up on how JAX's JIT works under the hood, as understanding this is really important to get good/correct behaviour with JAX.

**Comment by Atlis** [comment]
Ok perfect. I guess I'll investigate a more formal way to do thing with JAX, and continue my reading on the subject. Thanks again. I close the issue.
