### ISSUE TITLE
Feature Request: add attention utility functions like flax

### ISSUE THREAD

**Issue by jenkspt** [patrick-kidger/equinox#142]
It would be nice to split up the the [MultiheadAttention](https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/attention.py#L14) Module code into utility functions for calculating attention weights and multihead attention without projection layers. Flax does this -- but would be nice to have it here as well.

[https://github.com/google/flax/blob/main/flax/linen/attention.py#L40-L187](https://github.com/google/flax/blob/main/flax/linen/attention.py#L40-L187)

**Comment by patrick-kidger** [comment]
Sounds reasonable. I'd be happy to accept a PR doing this.

**Comment by anshradh** [comment]
Hey, I'd be interested in picking this up as a first issue if that's alright!

**Comment by patrick-kidger** [comment]
Go for it!
