### ISSUE TITLE
VGG support or eqxvision repository?

### ISSUE THREAD

**Issue by oarriaga** [patrick-kidger/equinox#143]
Hi,
so with some work I have now VGG16 with imagenet weights working in equinox. Here is the basic model description:
```python
import jax
import jax.numpy as jp
from equinox import Module
from equinox.nn import MaxPool2D, Linear, Conv2d


def build_block(intro_channels, outro_channels, key):
    keys = jax.random.split(key, len(outro_channels))
    block = []
    for outro_channel, key in zip(outro_channels, keys):
        conv2D = Conv2d(intro_channels, outro_channel, 3, padding=1, key=key)
        block.extend([conv2D, jax.nn.relu])
        intro_channels = outro_channel
    block.append(MaxPool2D((2, 2), stride=(2, 2)))
    return block


def flatten(x):
    x = jp.moveaxis(x, 0, 2)
    x = jp.reshape(x, -1)
    return x


def build_head(key, in_features, num_classes):
    key_1, key_2, key_3 = jax.random.split(key, 3)
    return [flatten,
            Linear(in_features, 4096, key=key_1),
            jax.nn.relu,
            Linear(4096, 4096, key=key_2),
            jax.nn.relu,
            Linear(4096, num_classes, key=key_3),
            jax.nn.softmax]



class VGG16(Module):
    layers: list

    def __init__(self, key, num_classes=1000):
        key_1, key_2, key_3, key_4, key_5, key_6 = jax.random.split(key, 6)
        block_1 = build_block(3, [64, 64], key_1)
        block_2 = build_block(64, [128, 128], key_2)
        block_3 = build_block(128, [256, 256, 256], key_3)
        block_4 = build_block(256, [512, 512, 512], key_4)
        block_5 = build_block(512, [512, 512, 512], key_5)
        head = build_head(key_6, 512 * 7 * 7, num_classes)
        self.layers = block_1 + block_2 + block_3 + block_4 + block_5 + head

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x)
        return x
```

I have now serialized the model leafs with imagenet weights, so there is a `VGG16.eqx` file that one can deserialize. In order to support VGG in equinox one would only need to host this file somewhere else.

I think it would be great to have at least some simple models like this working here out of the box. These models have stayed for some time in the perception community and are still being used. In the past, keras contained just a small set of standard models that  are reused constantly in multiple domains, but more specialized models were never introduced. Having said this, I also see the appeal of just having a minimal bare-bones library and focusing on having the basics in order.

Let me know what you think. I can quickly host this model in another repo or I can just make a PR here.

**Comment by patrick-kidger** [comment]
This is very elegantly written.

On balance I'm still inclined to host these in an external project, but as before I'm very happy to advertise its existence. What I'd quite like is for Equinox to be a foundation for other projects to build on top of -- indeed, this is precisely how Equinox got started, as the foundational set of abstractions for [Diffrax](http://github.com/patrick-kidger/diffrax).

**Comment by patrick-kidger** [comment]
I'm closing this as we now have `paganpasta/eqxvision`.
