### ISSUE TITLE
How to parallelize model training?

### ISSUE THREAD

**Issue by AaronSpieler** [patrick-kidger/equinox#144]
Hello,

my goal is to train a lot of tiny model (e.g. 1k) in parallel, and I though jax with equinox would be a good choice as jax has vmap (so I could just code up a single model and vectorize it) and equinox is close to vanilla jax. Importantly, I do not just want the same tiny model to be replicated, but have each of them differently initialized. So I would have to vmap the initialization function i.e. the constructor.

Essentially like here https://willwhitney.com/parallel-training-jax.html just with an eqx.Module.

I would think that the syntax would have to be something like the code below (which doesnt work), however, the constructur of eqx.Module is not pure functional so just vmapping the constructuor cannot work... // Also, then the question would be if that is possible, how to I properly vmap the __call__ function?

```
import equinox as eqx
import jax

class Linear(eqx.Module):
    weight: jax.numpy.ndarray
    bias: jax.numpy.ndarray

    def __init__(self, in_size, out_size, key):
        wkey, bkey = jax.random.split(key)
        self.weight = jax.random.normal(wkey, (out_size, in_size))
        self.bias = jax.random.normal(bkey, (out_size,))

    def __call__(self, x):
        return self.weight @ x + self.bias

batch_size, in_size, out_size = 32, 2, 3

# create a single model
model = Linear(in_size, out_size, key=jax.random.PRNGKey(0))

# create 10 different models
num_model = 10
model_keys = jax.vmap(jax.random.PRNGKey)(jnp.arange(0, num_model))
models = jax.vmap(Linear.__init__, in_axes=(None, None, 0))(in_size, out_size, model_keys)
```

I tried a couple of versions of the above code, but it seems to be non trivial, and I'm kind of stuck.

Any help would be greatly appreciated & thx so much for your time!

Best,
Aaron

**Comment by patrick-kidger** [comment]
Editing just the bottom two lines of your code:

```python
import equinox as eqx
import jax

class Linear(eqx.Module):
    weight: jax.numpy.ndarray
    bias: jax.numpy.ndarray

    def __init__(self, in_size, out_size, key):
        wkey, bkey = jax.random.split(key)
        self.weight = jax.random.normal(wkey, (out_size, in_size))
        self.bias = jax.random.normal(bkey, (out_size,))

    def __call__(self, x):
        return self.weight @ x + self.bias

batch_size, in_size, out_size = 32, 2, 3

# create a single model
model = Linear(in_size, out_size, key=jax.random.PRNGKey(0))

# create 10 different models
num_model = 10
model_keys = jax.random.split(jax.random.PRNGKey(0), 10)
models = jax.vmap(Linear, in_axes=(None, None, 0))(in_size, out_size, model_keys)
```

For more advanced examples in this vein, see the [`eqx.filter_vmap`](https://docs.kidger.site/equinox/api/filtering/filtered-transformations/#equinox.filter_vmap) documentation.

**Comment by AaronSpieler** [comment]
Hello,

thx for the extremely fast reply!

I see, I also did something super weird for the key splitting, ahah.
Perfect, thx so much for the correction and the hint! 
Using [eqx.filter_vmap](https://docs.kidger.site/equinox/api/filtering/filtered-transformations/#equinox.filter_vmap) was essential to make it work for me! 
But now the model ensemble seems to work, even with an additional batch dimension!

The working code for me:
```
@eqx.filter_vmap(kwargs=dict(param_config=None))
def ensemble_constructor(param_config, model_key): 
    return model_class(**param_config, key=model_key)

ensemble_keys = jax.random.split(jax.random.PRNGKey(0), 10)
ensemble = ensemble_constructor(param_config, ensemble_keys)
```
with 
```
@eqx.filter_vmap(kwargs=dict(x=None))
def evaluate_ensemble(model, x):
    return model(x)

ensemble_output = evaluate_ensemble(ensemble, example_batch_input[0])
ensemble_batched_output = jax.vmap(evaluate_ensemble, (None, 0))(ensemble, example_batch_input)
```

Coming from PyTorch the resulting code looks pretty clean and elegant, but also trippy with all the filtering.

Thx!
