### ISSUE TITLE
Make `nn.Sequential` indexable

### ISSUE THREAD

**Issue by jenkspt** [patrick-kidger/equinox#152]
Pytorch has the nice feature that you can index `Sequential` models.
For example in pytorch you can do the following

```python
>>> from torch import nn
>>> model = nn.Sequential(nn.Linear(10, 10), nn.Linear(10, 10), nn.Linear(10, 10))
>>> model[0]
Linear(in_features=10, out_features=10, bias=True)
>>> model[1:]
Sequential(
  (1): Linear(in_features=10, out_features=10, bias=True)
  (2): Linear(in_features=10, out_features=10, bias=True)
)
```
We can of course already do `eqx.nn.Sequential(...).layers[0]`, but it's a nice feature that the slicing returns another `Sequential`.

**Comment by patrick-kidger** [comment]
Sounds reasonable. I'd be happy to accept a PR on this.
