### ISSUE TITLE
Adding eqx.nn.Lambda ?

### ISSUE THREAD

**Issue by paganpasta** [patrick-kidger/equinox#157]
Hi, 
As per previous issues: https://github.com/patrick-kidger/equinox/issues/32, https://github.com/patrick-kidger/equinox/issues/102
It seems that a functionality to wrap Callables for nn.Sequential would be useful? 
Using `nn.Sequential` with an activation function is quite common and it is worthwhile to have `eqx.nn.Lambda` here instead of users replicating the effort for the same?

**Comment by patrick-kidger** [comment]
Right, so this has come up a couple of times. So the fact that this is basically only useful for working with `eqx.nn.Sequential` has been the reason against this before; i.e. it's something with a very limited used.

But that's not a strong feeling. I suppose the counterargument is that `eqx.nn.Sequential` isn't super useful without being able to include activation functions. So I'd be happy to accept a PR on this if it's something you particularly want in the library.
