### ISSUE TITLE
Missing #output in the example of StateIndex.

### ISSUE THREAD

**Issue by paganpasta** [patrick-kidger/equinox#163]
Hi,

It appears as though the example is missing comments specifying the expected outputs for the last two commands. Here: https://docs.kidger.site/equinox/api/experimental/stateful/#equinox.experimental.StateIndex

Just a small quality of life fix: 
```
# last_x=[0. 0.], x=[1. 2.]
# last_x=[1. 2.], x=[3. 4.]
```

**Comment by patrick-kidger** [comment]
Yep, agreed. Open a PR?
