### ISSUE TITLE
Globally set default filter functions?

### ISSUE THREAD

**Issue by LouisDesdoigts** [patrick-kidger/equinox#177]
Hey Patrick, I was wondering if there was a way to set the default behavior for the filter functions in some global manner? I am currently building an [fully differentiable optical modelling framework](https://github.com/LouisDesdoigts/dLux) that makes heavy use of Equinox (which is awesome by the way!). 

My current issue is that we want to use the enum package to set some properties (essentially tracking units) which I have been able to get working, but by default the `filter_jit` function uses the `is_array_like` filter function, resulting in `ConcretizationTypeError`, as the integer value from the `enum.IntEnum` is turned into a tracer. 

This can be trivially fixed by passing the `is_inexact_array` filter function to the `filter_jit` decorator, however this means that we can not use jit functionality without explicitly passing this extra argument anytime we want to use it, Therefore for our use-case it would make sense to be able to set this *globally*, so that `filter_jit` can be called natively. 

Is there currently any functionality for something like this, or any plans to implement something like this in the future? I imagine something like the `jax.config` could be possible, but I am mostly a high-level user so I'm not entirely sure.

Anyway any help would be greatly appreciated, and feel free to add our package to #75 - We have lost of awesome optics and astrophysics projects in the pipeline working on JWST, Hubble, photonic design.... lots of awesome stuff coming! Thanks again.

**Comment by paganpasta** [comment]
Hi @LouisDesdoigts, 

Is there a small code to reproduce the behaviour? 

I see that currently `filter_jit` uses `is_array` as default here:https://github.com/patrick-kidger/equinox/blob/edbdf570dfc0edceebcda40ecad736cb7ebd5274/equinox/jit.py#L107-L116

And as per its definition, it should only allow `jax.ndarrays` 
https://github.com/patrick-kidger/equinox/blob/edbdf570dfc0edceebcda40ecad736cb7ebd5274/equinox/filters.py#L15-L17

**Comment by LouisDesdoigts** [comment]
Yes Equinox is working appropriately, this is not a bug post, more of a feature request/question. 

In my use-case because of the way we are using the `enum.IntEnum`, I *always* want the `filter_jit` filter function to be `is_inexact_array` (the same is `filter_grad`). I am just curious if there is some way to define this globally, or change the default behaviors, just to prevent us needing to pass in an extra argument every call of `filter_jit`?

**Comment by patrick-kidger** [comment]
I think the correct thing for you to do here is to define your own wrapper for `filter_jit`, that you use throughout your package. For example:
```python
# utils.py
from equinox import filter_jit, is_inexact_arary
my_filter_jit = filter_jit(default=is_inexact_array)

# foo.py
from utils import my_filter_jit

@my_filter_jit
def bar(...): ...
```
I'm recommending this as it's definitely not possible to introduce a global flag. If someone were to load your package (that sets the global flag) and some other unrelated package (that expects the global flag not to be set), then the unrelated package could start misbehaving. Does that make sense?

**Comment by LouisDesdoigts** [comment]
Ah yes global flags won't exactly work in that case, good point. Yeah we could implement a wrapped version for our package, that will work for sure! Cheers for the help, closing this issue 👍
