### ISSUE TITLE
JAX installation

### ISSUE THREAD

**Issue by onnoeberhard** [patrick-kidger/equinox#178]
Hi,

If I install Equinox without having JAX installed, and then do `import equinox` in Python, I get an error: `ModuleNotFoundError: jax requires jaxlib to be installed.`

I get that it doesn't really make sense to use Equinox without a JAX installation, but shouldn't `pip install equinox` install all the necessary requirements (i.e. should jaxlib be added to the requirements)? Though what really surprises me is that JAX itself doesn't seem to depend on jaxlib, as far as pip knows... Am I doing something wrong?

Thanks!

**Comment by patrick-kidger** [comment]
Yep, this is deliberate. As you note, JAX itself doesn't like jaxlib as a dependency -- so we follow their example and don't list it either.

As for why JAX itself doesn't list jaxlib as a dependency -- I'm not 100% sure but I think it has to do with handling CPU vs GPU etc. support.

**Comment by onnoeberhard** [comment]
Ah I see, thanks for replying!
