### ISSUE TITLE
eqx.Module interaction with optax

### ISSUE THREAD

**Issue by liukidar** [patrick-kidger/equinox#193]
Hi,
I've noticed the following behaviour, which I believe is not intended. Not sure if there's any workarounds (or if I'm simply doing things wrong), but here we go:

The function optax.multi_transform expects as a second parameter a PyTree specifying the names for each leaf to link them with the corresponding optimizer. E.g.:

```python
model_mask = jtu.tree_map(..., model)
optimizer = optax.multi_transform({
	'n': optax.sgd(1e-3),
	'w': optax.adam(1e-3)
}, model_mask)
```

However, if we specify a `__call__` function for our model class, optax will treat `model_mask` as a generating function (I believe), resulting in an error. Is there a workaround for this? Or what I'm trying to achieve should be done in an entirely different way?

Thank you

**Comment by patrick-kidger** [comment]
Yup, this is an unfortunate design choice on Optax's part: at the time Optax was conceived, folks weren't using objects that could be both pytrees and callables. (Then Equinox came along!)

**Comment by liukidar** [comment]
Perfect, thank you!

**Comment by liukidar** [comment]
Perfect, thank you!
