### ISSUE TITLE
Easier syntax for `eqx.tree_at()`

### ISSUE THREAD

**Issue by LouisDesdoigts** [patrick-kidger/equinox#194]
Hey Patrick,

I've been developing [dLux](https://github.com/LouisDesdoigts/dLux) with @benjaminpope, who you recently met up with for a coffee in London! I believe you discussed a gentler syntax for parameter updates, and a more general update function to build native interfacing for equinox with probabilistic programming languages to run MCMC algorithms. I think I have found some nice solutions that might be worth integrating with equinox.

The general goal has been to be able to pass in a list/tuple of string/index based `paths` in order to specify where in the arbitrary pytree structure one would like to update (or apply functions!) to parameters, along with a list/tuple of new values/functions to apply to those parameters. Here are the functions and a minimal working example demonstrating the usage:

Update functions:
```python

import jax.numpy as np
import equinox as eqx
import typing

def get_leaf(pytree, path):
    """
    Recuses down the path of the pytree
    """
    key = path[0]
    pytree = pytree.__dict__[key] if isinstance(pytree, eqx.Module) else \
             pytree[key]
    
    # Return param if at the end of path, else recurse
    return pytree if len(path) == 1 else get_leaf(pytree, path[1:])

def update_pytree(pytree, paths, values):
    """
    Updates the `pytree` leaves specificied by params_paths with values
    """
    # Returns a tuple of leaves specified by paths
    get_leaves = lambda pytree : tuple([get_leaf(pytree, paths[i]) \
                                        for i in range(len(paths))])
    
    # Updates the leaf if passed a function
    update_leaf = lambda leaf, leaf_update: leaf_update(leaf)\
            if isinstance(leaf_update, typing.Callable) else leaf_update
    
    # Updates the leaves specified by paths
    update_values = tuple([update_leaf(get_leaf(pytree, paths[i]), \
                            values[i]) for i in range(len(paths))])
    
    return eqx.tree_at(get_leaves, pytree, update_values)

```

Define two classes to interface with
```python
class Foo(eqx.Module):
    param1 : float
    
    def __init__(self, p1):
        self.param1 = p1
        
class Bar(eqx.Module):
    foo : object
    some_dict : dict
    some_list : list
    param1 : float
    
    def __init__(self, foo, some_dict, some_list, param1):
        self.foo = foo
        self.some_dict = some_dict
        self.some_list = some_list
        self.param1 = param1

some_dict = {'entry1': 0., 'entry2': 1., 'foo': Foo(2)}
some_list = [3, 4, Foo(5)]
pytree = Bar(Foo(6), some_dict, some_list, 7)

print(pytree)
>>>Bar(
>>>  foo=Foo(param1=6),
>>>  some_dict={'entry1': 0.0, 'entry2': 1.0, 'foo': Foo(param1=2)},
>>>  some_list=[3, 4, Foo(param1=5)],
>>>  param1=7
>>>)
```

Define paths to parameters, as well as new values/functions to apply
```python
paths = [['foo', 'param1'], 
         ['some_dict', 'entry1'],
         ['some_dict', 'foo', 'param1'],
         ['some_list', 0],
         ['some_list', 2,'param1']]
values = [lambda x: -x, 10, 11, lambda x: x**2, 14]

new_pytree = update_pytree(pytree, paths, values)

print(new_pytree)
>>> Bar(
>>>  foo=Foo(param1=-6),
>>>  some_dict={'entry1': 10, 'entry2': 1.0, 'foo': Foo(param1=11)},
>>>  some_list=[9, 4, Foo(param1=14)],
>>>  param1=7
>>>)
```

As you can see from this example it is able to arbitrarily update or apply functions to each leaf specified by the path through arbitrary nesting. I think that this syntax will already help non-developer and less experienced users be able to interface with our software. I am already using it in a Base class that all others inherit from, so it would make sense to me to move this into equinox. The general functionality is more related to pytrees, so having it live in the `tree.py` could also make sense.

Anyway I can create a PR if you're interested, I would to be able to contribute to this awesome software!
Cheers

ps. I do have some further functionality I use to get a nice interface with probabilistic programming languages like [Numpyro](https://num.pyro.ai/en/latest/index.html#introductory-tutorials), which could be nice for others using equinox to build more physical modelling software. They are essentially just lightweight wrappers but Im happy to share examples of that if you're interested

**Comment by benjaminpope** [comment]
Hi Patrick,

Thanks for your comments... I think we have been avoiding those edge cases simply by how we're calling it in `dLux`, but if these won't work in general they can't get merged into `equinox` directly.

Unfortunately all of the solutions are a bit tacked on, but we need something like this to interface to `numpyro` or other PPLs straightforwardly, where we need to be able to update named parameters. There is nice syntax in `equinox` with `model = eqx.apply_updates(model, updates)` for use with `optax`, but for many physics problems we want to use HMC samplers.

I don't know if Louis' solution will work in general, but perhaps it will be useful to show the full `dLux` example with the full example using `numpyro`. 

Cheers,

Ben

**Comment by LouisDesdoigts** [comment]
Thanks for the response!

You bring up some good points, let me know what you think.

---
> First of all, you have a hasattr(pytree, eqx.Module), which will raise an error as eqx.Module isn't a string.
>
> In any case, it's also an important design goal for Equinox that eqx.Module not be special-cased: it's just a PyTree like any other. This is important as it makes it much easier to reason about how code behaves.
>
> A variation like getattr(pytree, key) if isinstance(key, str) else pytree[key] has the problem of not supporting pytree[some_str].

That `hasattr` call is actually `isinstance`! I'm not sure how it ended up as `hasattr` in the post 😂, I've fixed that up now. 

Yeah there are definitely some annoying edge cases here I haven't thought about, we are focused towards a more specific use case. 

Do you think that `hasattr(pytree, 'tree_flatten')` could be used to specify a *general* pytree like so?
```python
pytree = pytree.__dict__[key] if hasattr(pytree, 'tree_flatten') else pytree[key]
```
As far as I understand this would be able to arbitrarily applied to any pytree structure as long as the entries in the path list refer to parameters/entries that exist, which is the same behavior of eqx.tree_at. I would use `hasattr(pytree, '__dict__')` but unfortunately `collections.OrderedDict()` is an edge case that breaks it.

---

> The isinstance(leaf_update, typing.Callable) will frequently fail: for example when doing something like
>
>```python
>model = eqx.nn.MLP(...)
>new_linear = eqx.nn.Linear(...)
>model = eqx.tree_at(lambda m: m.layers[-1], model, new_linear)
>```
>
>for which the replacement is itself callable.

Yeah I hadn't considered that. I bumped up against a similar issue with our package interfacing with optax, resulting in us deciding to replace the `__call__()` method with a different named function. This was just some extra functionality I had an idea for along the way that works in our use case. 

I think this should be possible though with a modified `get_leaf` function that returns `True` in the base case could be used to apply specific functions to specific leaves. There are some use cases in our work where this would simplify our syntax.

---

>You're assuming that objects can be navigated just via model.foo and model[foo]. This is certainly true about 90% of the time, but it needn't always be the case. For example one current use-case is:
>
>```python
>cond = lambda x: ...  # returns True or False
>where = lambda m: [x for x in jax.tree_leaves(m, is_leaf=cond) if cond(x)]
>eqx.tree_at(where, ...)
>```
>
>to find all nodes satisfying a certain condition.

Yes this is a good point, I don't think there is a general case that the syntax I've proposed could ever work for this use case. I guess what I'm proposing here wouldn't actually be a replacement for `eqx.tree_at`, but perhaps a higher-level function to simplify parameter update calls within equinox, which is something we need to do a lot!

---
---

> Regarding your other wrappers -- absolutely, I'd be curious to see these.

So to give you an idea of the general way we are trying to use equinox and the sort of syntax we are looking for I can link you [this notebook](https://github.com/LouisDesdoigts/dLux/blob/main/dLux/dev/dLux_HMC.ipynb) in our dev folder. The basic idea is we are trying to infer the properties of a binary star *and* the the optical system that is observing it. MCMC algorithms try to learn these parameters and their relationships by randomly sampling some likelihood function. HMC algorithms are versions that use autodiff to allow high dimensional models. 

If you look in the notebook in the 7th cell, these libraries essentially want a differentiable function that can update and then evaluate the model, hence our desire to built a nice syntactical interface. Using the method I posted I've been able to simplify this down to users constructing a single function that specifies the path to these parameters that takes in keyword arguments. Our classes all also inherit from this Base class, which gives the extra functionality we need.

```python
class Base(abc.ABC, eqx.Module):
    def get_leaf(self, pytree, path):
        """
        Recuses down the path of the pytree
        """
        key = path[0]
        pytree = pytree.__dict__[key] if isinstance(pytree, eqx.Module) else \
                 pytree[key]

        # Return param if at the end of path, else recurse
        return pytree if len(path) == 1 else self.get_leaf(pytree, path[1:])
    
    def update_pytree(self, paths, values):
        """
        Updates the `pytree` leaves specificied by params_paths with values
        """
        # Returns a tuple of leaves specified by paths
        get_leaves = lambda pytree : tuple([self.get_leaf(pytree, paths[i]) \
                                            for i in range(len(paths))])

        # Updates the leaf if passed a function
        update_leaf = lambda leaf, leaf_update: leaf_update(leaf)\
                if isinstance(leaf_update, typing.Callable) else leaf_update

        # Updates the leaves specified by paths
        update_values = tuple([update_leaf(self.get_leaf(self, paths[i]), \
                                values[i]) for i in range(len(paths))])

        return eqx.tree_at(get_leaves, self, update_values)
    
    def update_params(self, update_fn, **kwargs):
        """
        Update the paramaters with the given input value
        """
        params, param_paths = update_fn(**kwargs)
        
        # Get value & paths to be updated
        update_values = tuple([params[i] for i in range(len(params)) \
                              if params[i] is not None])
        
        # Get paths to be parameters to be updated
        update_paths = tuple([param_paths[i] for i in range(len(params)) \
                              if params[i] is not None])
        
        # Return updated pytree
        return self.update_pytree(update_paths, update_values)
    
    def update_and_model(self, update_fn, model_fn, **kwargs):
        """
        Updates the given input parameters, and then models the psf
        """
        return getattr(self.update_params(update_fn, **kwargs), model_fn)()
```

This is about as a simple as I have been able to get the end user experience, which is a really big focus in our work because *most* people in astro do not have any formal CS education and just kind of learn programming along the way. Most will throw their hands in the air if you show them syntax that requires a `lambda` function, hence our desire for an easier syntax 😂.

Anyway take a look, equinox has allowed us to do some really awesome things, and let me know if you have any ideas about how to improve the general syntax, you are clearly the resident pytree expert!

**Comment by LouisDesdoigts** [comment]
Hey so I've been thinking some more about this, and I think that given the wider use-cases that I hadn't considered, the current `tree_at` syntax is likely optimal. I think that there could be value in adding a reduced functionality `update_pytree` or `update_params` function to equinox. I know that for our use-case this would be valuable both for end-users, and make interfacing with packages with like Numpyro a bit easier.

This should only require adding the `__getitem__` method to `eqx.Module`, which simply calls the `__dict__` method and indexes it: 

```python
  def __getitem__(self, index):
      return self.__dict__[index]
```

You mentioned in your original reply that you wanted equinox modules to be general pytrees, I think that allowing them to indexable would actually help serve this goal. With this addition, if we ignore applying functions to leaves, then a simple parameter update function would look like this:

```python
import jax.numpy as np
import equinox as eqx

def get_leaf(pytree, path):
    """
    Recuses down the path of the pytree
    """
    # Return param if at the end of path, else recurse
    pytree = pytree[path[0]]
    return pytree if len(path) == 1 else get_leaf(pytree, path[1:])

def update_pytree(pytree, paths, values):
    """
    Updates the `pytree` leaves specificied by params_paths with values
    """
    # Returns a tuple of leaves specified by paths
    get_leaves = lambda pytree : tuple([get_leaf(pytree, paths[i]) \
                                        for i in range(len(paths))])
    
    return eqx.tree_at(get_leaves, pytree, values)
```

Which using the same example as above would be interfaced with like this:

```python
class Base(eqx.Module):
    def __getitem__(self, index):
        return self.__dict__[index]
    
class Foo(Base):
    param1 : float
    
    def __init__(self, p1):
        self.param1 = p1
        
class Bar(Base):
    foo : object
    some_dict : dict
    some_list : list
    param1 : float
    
    def __init__(self, foo, some_dict, some_list, param1):
        self.foo = foo
        self.some_dict = some_dict
        self.some_list = some_list
        self.param1 = param1

some_dict = {'entry1': 0., 'entry2': 1., 'foo': Foo(2)}
some_list = [3, 4, Foo(5)]
pytree = Bar(Foo(6), some_dict, some_list, 7)

print(pytree)
>>>Bar(
>>>  foo=Foo(param1=6),
>>>  some_dict={'entry1': 0.0, 'entry2': 1.0, 'foo': Foo(param1=2)},
>>>  some_list=[3, 4, Foo(param1=5)],
>>>  param1=7
>>>)
```

```python
paths = [['foo', 'param1'], 
         ['some_dict', 'entry1'],
         ['some_dict', 'foo', 'param1'],
         ['some_list', 0],
         ['some_list', 2,'param1']]
values = [9, 10, 11, 12, 14]

new_pytree = update_pytree(pytree, paths, values)
print(new_pytree)
>>>Bar(
>>>  foo=Foo(param1=9),
>>>  some_dict={'entry1': 10, 'entry2': 1.0, 'foo': Foo(param1=11)},
>>>  some_list=[12, 4, Foo(param1=14)],
>>>  param1=7
>>>)
```

This could also be robustly extended to apply functions to leaves by similarly passing in a list/tuples of booleans that either replace or apply the 'values' list.

Let me know what you think!

**Comment by patrick-kidger** [comment]
So, on balance I'm inclined against this.

I think it's important to have a single canonical way to do things.

Providing wrappers makes the one task you're currently doing simpler, but at the expense of making the library more complicated.

Nonetheless, thank you for raising this -- I appreciate the desire to contribute back to an upstream library.

**Comment by LouisDesdoigts** [comment]
Yeah no problem, that does make sense.
Thanks for the help though!
