### ISSUE TITLE
Counting the number of parameters in an equinox module.

### ISSUE THREAD

**Issue by jacobusmmsmit** [patrick-kidger/equinox#198]
Based on [this answer](https://github.com/google/jax/discussions/6153#discussioncomment-506909) I came up with the following code to count the number of parameters. The default `replace = None` has size 1 so `[]` is used instead.

Is this a reliable way to do so? I implicitly make the assumptions that all parameters are contained in JAX arrays and all JAX arrays contain parameters but I feel this is a reasonable assumption.

```
import jax.numpy as jnp
import jax.tree_util as jtu
import equinox as eqx
from equinox.custom_types import PyTree

def count_params(pytree: PyTree) -> int:
    return sum(
        jnp.size(x)
        for x in eqx.filter(jtu.tree_leaves(pytree), eqx.is_array, replace=[])
    )
```

**Comment by patrick-kidger** [comment]
Yep, that looks fine. I'd probably neaten it slightly to:

```
sum(x.size for x in jtu.tree_leaves(eqx.filter(pytree, eqx.is_array)))
```

Btw, `equinox.custom_types.PyTree` is private API. The good news is that the [jaxtyping](https://github.com/google/jaxtyping) library has a `PyTree` type you can use instead!

(And at some point, when I get around to it, I intend to update Equinox to use jaxtyping as well.)
