### ISSUE TITLE
[Documentation] Higher order tensors as input

### ISSUE THREAD

**Issue by logan-hs** [patrick-kidger/equinox#212]
_Having this comment from linear.py's source somewhere prominent in the documentation would have been quite helpful for me:_

If you want to use higher order tensors as inputs (for example featuring batch dimensions) then use `jax.vmap`. For example, for an input `x` of shape `(batch, in_features)`, using
```python
linear = equinox.nn.Linear(...)
jax.vmap(linear)(x)
```
will produce the appropriate output of shape `(batch, out_features)`.

**Comment by patrick-kidger** [comment]
Yup, that makes sense -- this could probably afford to be better-advertised.

It might also br worth listing it in a few other common onboarding locations: in the intro docs  and in the docstring for `MLP`.
