### ISSUE TITLE
Any plan to abstract this library out to provide OOP with jax?

### ISSUE THREAD

**Issue by epignatelli** [patrick-kidger/equinox#23]
As per title, do you have any plan to abstract this library out to allow OOP in jax?
I am thinking about something like a `jaxclass` decorator, or a `JaxObject` base class.

I undersand this is already possible by dealing with jax `PyTree`s, but the question is about whether there is any plan to bake this into an easer API.

**Comment by patrick-kidger** [comment]
One of the goals of Equinox is to provide the minimum set of abstractions needed to do OOP with JAX. (Those abstractions being `eqx.Module` and the filtered transformations.)

I'd argue that those goals have already been met, however. So I'm not sure I understand what you have in mind? Is there a part of the current API that you find troublesome?

**Comment by cgarciae** [comment]
Hey! For a "lightweight" dependency that exposes custom JAX Pytree classes you can check:  

* [chex](https://github.com/deepmind/chex): provides a [dataclass](https://github.com/deepmind/chex#dataclass-dataclasspy) abstraction (does a lot more stuff).
* [treeo](https://github.com/cgarciae/treeo): focuses exclusively on creating class-based pytrees.
* Actually equinox only depends on JAX itself so you can consider it a lightweight dependency 😀.

**Comment by epignatelli** [comment]
Apologies for the late reponse all, I did tie a string around my finger for this but as @patrick-kidger said, the answer is already in the `eqx.Module`, or even in the `register_pytree_node_class`.
Thank you for all the answers!
