### ISSUE TITLE
Parameterise fields with nested dict

### ISSUE THREAD

**Issue by slishak** [patrick-kidger/equinox#230]
Hi @patrick-kidger ,

Thanks very much for [pointing me](https://github.com/rtqichen/torchdiffeq/pull/134#issuecomment-1194183400) to Diffrax. I've been trying it out over the past week and it's a good few thousand times faster!

I had some questions that are specific to Equinox though. They essentially focus on a specific way I'm parameterising the modules, and I wanted to know if there's anything I've done here that might potentially cause problems down the line - it all seems to work fine for now, but I haven't tried to do anything that complicated yet.

Below is an abstract outline of what I'm trying to do. To set the scene: I have some model `MainModel` which contains multiple `Component` modules:

```python
import equinox as eqx

class Component(eqx.Module):
    u: float

    def __call__(self, x):
        return self.u * x

class MainModel(eqx.Module):
    a: Component
    b: Component
    c: Component
    d: float

    def __call__(self, x, y, z):
        return self.a(x) + self.b(y) + self.c(z) + self.d
```

The `Component` class has a couple of subclasses which work a little differently:
```python
class Variation1(Component):
    def __call__(self, x):
        return self.u * x**2

class Variation2(Component):
    v: float

    def __call__(self, x):
        return super().__call__(x) + self.v * x**2
```

Already, as expected, I can parameterise `MainModel` with these subclasses and it seems to work fine:
```python
m = MainModel(
    a=Component(2.0),
    b=Component(3.0),
    c=Component(4.0),
    d=1.0,
)
print(m(-1.0, 0.0, 1.0))
# 3.0

m = MainModel(
    a=Component(2.0),
    b=Variation1(3.0),
    c=Variation2(4.0, 2.0),
    d=1.0,
)
print(m(-1.0, 0.0, 1.0))
# 5.0
```

And I can also create a subclass of `MainModel` that specifically refers to these subclasses (which is useful if the main model has its own internals which are also different when using these different components):
```python
class OtherModel(MainModel):
    b: Variation1
    c: Variation2

    def __call__(self, x, y, z):
        return self.a(x) + self.b(y) + self.c(z) + 2 * self.d

m = OtherModel(
    a=Component(2.0),
    b=Variation1(3.0),
    c=Variation2(4.0, 2.0),
    d=1.0,
)
print(m(-1.0, 0.0, 1.0))
# 6.0
```

All far so good. But now, imagine I have multiple sets of parameters that can parameterise `MainModel`, and multiple sets of parameters that can parameterise `OtherModel`. I want to store these separately and be able to choose which set to use. I don't want to keep repeating which component classes are used by each of the models, I want to just write it once in the model definition to reduce maintenance workload. So I create a file that has nested dicts that will parameterise each of the models:

```python
main_model_params_1 = {
    "a": {"u": 2.0},
    "b": {"u": 3.0},
    "c": {"u": 4.0},
    "d": 1.0,
}

main_model_params_2 = {
    "a": {"u": 2.5},
    "b": {"u": 5.0},
    "c": {"u": -4.0},
    "d": 100.0,
}


other_model_params_1 = {
    "a": {"u": 2.0},
    "b": {"u": 3.0},
    "c": {"u": 4.0, "v": 2.0},
    "d": 1.0,
}

other_model_params_2 = {
    "a": {"u": -4.0},
    "b": {"u": 6.0},
    "c": {"u": 0.0, "v": 1.0},
    "d": -100.0,
}
```

In order to use these numbers with the classes defined in the models, I wrote the following code:

```python
from dataclasses import fields

class MainModel(eqx.Module):
    a: Component
    b: Component
    c: Component
    d: float

    def __init__(self, params: dict):
        self.parameterise(params)

    def parameterise(self, params: dict):
        for field in fields(self):
            try:
                field_params = params[field.name]
            except KeyError:
                continue

            if isinstance(field_params, dict):
                setattr(self, field.name, field.type(**field_params))
            else:
                setattr(self, field.name, field.type(field_params))

    def __call__(self, x, y, z):
        return self.a(x) + self.b(y) + self.c(z) + self.d

class OtherModel(MainModel):
    b: Variation1
    c: Variation2

    def __call__(self, x, y, z):
        return self.a(x) + self.b(y) + self.c(z) + 2 * self.d
```

This all seems to work as expected:
```python
m = MainModel(main_model_params_1)
print(m(-1.0, 0.0, 1.0))
# 3.0

m = MainModel(main_model_params_2)
print(m(-1.0, 0.0, 1.0))
# 93.5

m = OtherModel(other_model_params_1)
print(m(-1.0, 0.0, 1.0))
# 6.0

m = OtherModel(other_model_params_2)
print(m(-1.0, 0.0, 1.0))
# -195.0
```

But I'm not sure if I'm risking any "weirdness" down the line by using `setattr` to set the field values, or using `dataclasses.fields`, or anything else. Or whether what I'm doing is totally unnecessary and there's a simpler way to be doing it. Any input appreciated!

**Comment by patrick-kidger** [comment]
Hmm, interesting! So right now the type annotations used at the top of an `eqx.Module` are somehow "purely decorative": you could set them to anything at all; simply having the type annotation is the prerequisite for them to be used as fields.

(Why? Because that's how the built-in dataclasses work, and we try to build on top of Python stdlib. Why do dataclasses work this way? Good question.)

So what you're doing here -- introspecting the dataclass fields and looking at their annotations -- definitely has no existing analogue. Moreover this probably only works because you're in a relatively restricted setting (e.g. each `Variation` has the same `__init__` as its parent class), so probably there is no generic solution to this kind of thing.

So I think the short answer is "Sure, this looks fine to me! Keep doing what you're doing."

`*` Side note: I have some plans to update [jaxtyping](https://github.com/google/jaxtyping) so that the type annotations are enforced.

**Comment by slishak** [comment]
Thanks very much! The confirmation that the type annotations work the same here as they do in `dataclasses` (i.e. no effect on how the code runs) is good to know - that's something I intended to ask explicitly but forgot, so thanks for reading between the lines there.

And thanks for the link to jaxtyping; reading the [FAQ](https://github.com/google/jaxtyping/blob/main/FAQ.md#does-jaxtyping-use-pep-646-variadic-generics) resulted in me falling down a rabbit hole of learning about Python internals!

I will keep this parameterisation code for now, but will proceed with caution...
