### ISSUE TITLE
filter_jit static_argnames

### ISSUE THREAD

**Issue by chrisflesher** [patrick-kidger/equinox#236]
I'd like to jit a function that has both an `equinox.Module` and a function as input. Here was my first attempt:
```
@functools.partial(jax.jit, static_argnames=['myfunction'])
def jit_function(mymodule: equinox.Module, myarray: jnp.ndarray, myfunction: typing.Callable) -> jnp.ndarray:
```

But am getting:
```
TypeError: Shapes must be 1D sequences of concrete values of integer type, got Traced<ShapedArray(int32[3])>with<DynamicJaxprTrace(level=0/1)>.
```

Then I tried changing to:
```
@functools.partial(equinox.filter_jit, static_argnames=['myfunction'])
def jit_function(mymodule: equinox.Module, myarray: jnp.ndarray, myfunction: typing.Callable) -> jnp.ndarray:
```

But am getting:
```
ValueError: `jitkwargs` cannot contain 'static_argnums', 'static_argnames' or 'donate_argnums'.
```

I'm not really sure how to proceed, if you have any insight I'd appreciate it!

**Comment by chrisflesher** [comment]
Maybe this problem has nothing to do with equinox and is because my `myarray` is not a known size...

**Comment by patrick-kidger** [comment]
This issue looks to be something happening inside your JAX code. (And not something to do with Equinox.) Probably you're doing something like:
```python
@jax.jit
def f(shape):
  return jax.numpy.zeros(shape)
```
Which doesn't work as JAX requires that all array shapes be known statically.

FWIW, if you're an Equinox user, then best practice is to just do
```python
@eqx.filter_jit
def foo(...)
```
You shouldn't find yourself needing to manually specify what is traced and what is static. 99% of the time this is just determined by the type of each argument. (Arrays are traced, everything else is static.)

**Comment by chrisflesher** [comment]
Ah, that is nice to not have to worry about defining static stuff with `eqx.filter_jit`. Thank you for the explanation! Have been enjoying using `equinox`.
