### ISSUE TITLE
A way to copy an instance while replacing some fields

### ISSUE THREAD

**Issue by chrisflesher** [patrick-kidger/equinox#240]
Often I need to copy a class but replace a single attribute. For the `typing.NamedTuple` classes there is the `_replace` function. I was wondering what the most readable equivalent when using `equinox.Module` might be? Thanks!

Here is a similar issue with some examples:
https://github.com/ericvsmith/dataclasses/issues/42

**Comment by patrick-kidger** [comment]
Take a look at `eqx.tree_at`.

**Comment by chrisflesher** [comment]
Cool, thanks! That works.
