### ISSUE TITLE
Avoiding recompilation with multiple identical modules

### ISSUE THREAD

**Issue by danielward27** [patrick-kidger/equinox#246]
I was wondering if there is any way to avoid recompiling identical submodules within a module. For example, in the MLP definition (https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/composed.py#L76), we may have multiple hidden layers with fixed sizes that are all compiled separately. In my context this can becomes costly.

I'd ideally like a way to avoid recompilation without explicitly manipulating the class definition, so it could be applied to arbitrary modules. I tried coding up a rough version:
```
import equinox as eqx
from jaxtyping import Array, PyTree
import jax.numpy as jnp
from typing import List, Any
import jax

class Add(eqx.Module):
    bias: Array

    def __init__(self, bias) -> None:
        self.bias = bias
    
    def __call__(self, x):
        return x + self.bias


class MultiLayer(eqx.Module):
    static: PyTree
    params: PyTree

    def __init__(self, layers: List[eqx.Module]):
        structures = jax.tree_map(lambda x: x.shape if eqx.is_array(x) else x, layers)
        if not eqx.tree_equal(*structures):
            raise ValueError("Layers must all share the same structure.")
                
        self.static = eqx.filter(layers[0], eqx.is_array, inverse=True)

        # Combine params into pyree of arrays so we can scan 
        self.params = jax.tree_map(
            lambda *x: jnp.stack(x, axis=0),
            *[eqx.filter(l, eqx.is_array) for l in layers]
        )

    def __call__(self, x):
        y, _ = jax.lax.scan(self._scan_fn, x, self.params)
        return y

    def _scan_fn(self, x, params):
        "Single layer computation"
        layer = eqx.combine(self.static, params)
        y = layer(x)
        return y, None


multi = MultiLayer([Add(jnp.array([2,2])), Add(jnp.ones(2)), Add(jnp.ones(2))])
multi(jnp.zeros(2))
```
Is this a reasonable approach?

Thanks!

**Comment by patrick-kidger** [comment]
Yep, this kind of thing is absolutely a reasonable approach. What you've done is sometimes known as "scan over layers", which as you've been finding, is used to minimise compile time costs.

If you control the layer initialisation then you can also simplify things slightly by wrapping the constructor with `filter_vmap`. See the examples [in the docs](https://docs.kidger.site/equinox/api/filtering/filtered-transformations/#equinox.filter_vmap) for creating ensembles using `filter_vmap`, but creating multiple identical layers would work equally well.

**Comment by danielward27** [comment]
Thanks! I will give the `filter_vmap` approach a play too.
