### ISSUE TITLE
PReLU Activation

### ISSUE THREAD

**Issue by enver1323** [patrick-kidger/equinox#247]
Hi @patrick-kidger, I am a big fan of Equinox, thank you for publishing this framework. I am currently working on a project and decided to give a PReLU a try, Therefore, I was wondering, if it was possible to add PReLU Activation function to a some module like `nn.activations`.

My current implementation, is as follows:

```
class PReLU(eqx.Module):
    negative_slope: jaxtyping.Array

    def __init__(self, alpha):
        self.negative_slope = jnp.array((alpha,))

    def __call__(self, x):
        return jax.numpy.where(x >= 0, x, self.negative_slope * x)
```

**Comment by patrick-kidger** [comment]
Your implementation looks good to me. I'd be happy to accept a PR adding this to Equinox.

**Comment by enver1323** [comment]
Thank you, @patrick-kidger! I added the PR with the implementation and docs in the [PR #249 ](https://github.com/patrick-kidger/equinox/pull/249).

**Comment by patrick-kidger** [comment]
Closing since this now exists on the `dev` branch, which will shortly be merged to `main`.
