### ISSUE TITLE
Changes to nn.MLP

### ISSUE THREAD

**Issue by dimarkov** [patrick-kidger/equinox#255]
HI, I am using equinox in combination with Numpyro PPL and to register parameters of an MLP module or a Sequential module  as random variables I've made the following function:

```
def register_network_vars(nnet):
        params, static = eqx.partition(nnet, eqx.is_inexact_array)
        vals, aux = params.tree_flatten()

        new_vals = ()
        for l, layer in enumerate(vals[0]):
            lv, l_aux = layer.tree_flatten()
            new_lv = ()
            for value, name in zip(lv, l_aux[0]):
                if value is not None:
                    if name == 'bias':
                        new_lv += (sample(f'layer{l}.{name}', dist.Normal(0., 1.).expand(list(value.shape)).to_event(1)),)
                    else:
                        weight = prior(f'layer{l}.{name}', value.shape)
                        new_lv += (weight,)
                else:
                    new_lv += (value,)

            new_vals += (layer.tree_unflatten(l_aux, new_lv),)

        vals = (new_vals,) + vals[1:]
        params = self.params.tree_unflatten(aux, vals)

        return eqx.combine(params, static)
```

however, depending on how I define nnet either as 
```
nnet = nn.MLP(...)
```
or
```
nnet = nn.Sequential([Linear(...), ..., ])
```

I get an error which can be tracked to how a sequence of module is stored inside each of these Classes. MLP uses a list for linking linear layers, while in Sequential layers are stored as a tuple, because of this transform within the init self.layers = tuple(layers). So basically the error says MLP net is expecting a list when combining the network, whereas if I would set  new_vals = [] then when nnet = Sequential(...) I get similar error complaining that vals should be a tuple. 

I solved this for now simply by changing the MLP module as
```
  ...
  layers = ()
  if depth == 0:
      layers += (Linear(in_size, out_size, use_bias=use_bias, key=keys[0]), )
  else:
      layers += (Linear(in_size, width_size, use_bias=use_bias, key=keys[0]), )
      for i in range(depth - 1):
          layers += (Linear(width_size, width_size, use_bias=use_bias, key=keys[i + 1]), )
      layers += (Linear(width_size, out_size, use_bias=use_bias, key=keys[-1]), )
``` 

I wanted to ask if making a pull request would be reasonable? If not is there a way I can change register_network_vars so that this problem does not occur.

**Comment by patrick-kidger** [comment]
Hey there!

So it looks like you're trying to edit the weights and biases of your model? The recommended way to do this is using `eqx.tree_at`; [see this documentation](https://github.com/patrick-kidger/equinox/blob/dev/docs/tricks.md#custom-parameter-initialisation).  (Incidentally, there's no reason you should have known about this documentation. I only wrote it recently and it isn't published yet -- this'll happen in the next week or so!)

Does that accomplish what you're after?

(Side note, `module.tree_{flatten,unflatten}` methods are actually private API. You should use `jax.tree_util.{tree_flatten, tree_unflatten}` instead. I can see that that isn't at all clear, though! So in the next release I'll rename these to `_tree_{flatten,unflatten}`.)

**Comment by dimarkov** [comment]
Thank you, I will try it out. Practically what I am trying to do is to sample model parameters from priors, and than use those values in the network module to compute responses to some inputs.

**Comment by dimarkov** [comment]
@patrick-kidger Thank you again, this worked, the code is definitely cleaner and independent of the neural network module things just work.

**Comment by patrick-kidger** [comment]
That's great to hear, thank you!
