### ISSUE TITLE
Sync the parameter shared by two equinox module classes

### ISSUE THREAD

**Issue by PeishiJiang** [patrick-kidger/equinox#258]
Hello!

I have one trainable parameter that is used by two equinox module-based classes. The two classes are further called by a third class. Given that, how to design the three classes so that the parameter of the two classes are linked when being updated?

Take the example below. The class `Mother` uses the instances of two classes `ChildA` and `ChildB`, both of which use parameter `pA`. **I expect to find a way to sync the update of `ChildA.pA` and `ChildB.pA` so that `ChildA.pA = ChildB.pA`.** However, the current design does not allow it (I always get different `ChildA.pA`and `ChildB.pA`after putting `Mother` into an optimization framework).

```python
import equinox as eqx
from jaxtyping import Array

class ChildA(eqx.Module):
    pA: Array
    pB: Array

    def __init__(self, pA, pB  **kwargs):
        super().__init__(**kwargs)
        self.pA, self.pB = pA, pB

    def __call__(self, *args, **kwargs):
        ...do something

class ChildB(eqx.Module):
    pA: Array
    pC: Array

    def __init__(self, pA, pC  **kwargs):
        super().__init__(**kwargs)
        self.pA, self.pC = pA, pC

    def __call__(self, *args, **kwargs):
        ...do something

class Mother(eqx.Module):
    child_a: ChildA
    child_b: ChildB

    def __init__(self, pA, pB, pC  **kwargs):
        super().__init__(**kwargs)
        self.child_a = ChildA(pA, pB)
        self.child_b = ChildB(pA, pC)

    def __call__(self, *args, **kwargs):
        ...do something
```

**Comment by patrick-kidger** [comment]
See [the FAQ](https://docs.kidger.site/equinox/faq/#a-module-saved-in-two-places-has-become-two-independent-copies)!

The usual fix for this is to store the parameter in the parent and then pass it in at call time. For example:
```python
class Mother(eqx.Module):
    pA: Array
    child_a: ChildA
    child_b: ChildB
    
    ...
    
    def __call__(self, ...):
        ... = self.child_a(self.pA, ...)
```

Alternatively you can typically delay initialisation until call-time as well (since JAX compilation makes this efficient):
```python
class Mother(eqx.Module):
    pA: Array
    pB: Array
    pC: Array
    
    ...

    def __call__(self, ...):
        child_a = ChildA(self.pA, self.pB)
        ... = child_a(...)
```

Unfortunately JAX works with PyTrees rather than Py[DAGs](https://en.wikipedia.org/wiki/Directed_acyclic_graph) -- i.e. common subtrees are always handled independently via [referential transparency](https://en.wikipedia.org/wiki/Referential_transparency) -- so our hands are more-or-less tied on this front.

Frankly, the need for any of this is definitely a wart. I'd love for there to be a better solution, but I haven't come up with one yet!

**Comment by PeishiJiang** [comment]
> See [the FAQ](https://docs.kidger.site/equinox/faq/#a-module-saved-in-two-places-has-become-two-independent-copies)!
> 
> The usual fix for this is to store the parameter in the parent and then pass it in at call time. For example:
> 
> ```python
> class Mother(eqx.Module):
>     pA: Array
>     child_a: ChildA
>     child_b: ChildB
>     
>     ...
>     
>     def __call__(self, ...):
>         ... = self.child_a(self.pA, ...)
> ```
> 
> Alternatively you can typically delay initialisation until call-time as well (since JAX compilation makes this efficient):
> 
> ```python
> class Mother(eqx.Module):
>     pA: Array
>     pB: Array
>     pC: Array
>     
>     ...
> 
>     def __call__(self, ...):
>         child_a = ChildA(self.pA, self.pB)
>         ... = child_a(...)
> ```
> 
> Unfortunately JAX works with PyTrees rather than Py[DAGs](https://en.wikipedia.org/wiki/Directed_acyclic_graph) -- i.e. common subtrees are always handled independently via [referential transparency](https://en.wikipedia.org/wiki/Referential_transparency) -- so our hands are more-or-less tied on this front.
> 
> Frankly, the need for any of this is definitely a wart. I'd love for there to be a better solution, but I haven't come up with one yet!

Thanks for the suggestions, Patrick! Both approaches sound good to me though the best way might be to design `ChildA` and `ChildB` that do not share the same parameters.
