### ISSUE TITLE
`typing_extensions` no longer required?

### ISSUE THREAD

**Issue by dhirschfeld** [patrick-kidger/equinox#262]
https://github.com/patrick-kidger/equinox/blob/76a2baa9e63f32e2ed28f2df06277ec1367c7655/equinox/internal/while_loop/while_loop.py#L5

Since `equinnox` now requires `python>=3.8` I think you can import `Literal` directly from the `typing` module:

![image](https://user-images.githubusercontent.com/881019/220313542-d7d024f5-a0fe-4a5a-8875-8e4fa47a97a3.png)

https://github.com/python/typing_extensions#included-items

**Comment by patrick-kidger** [comment]
Good catch, thanks. I've just fixed this at HEAD.
