### ISSUE TITLE
Robust wrapper of filter function with `arg`/`filter_spec`

### ISSUE THREAD

**Issue by LouisDesdoigts** [patrick-kidger/equinox#270]
We are developing a package [`zodiax`](https://github.com/LouisDesdoigts/zodiax) that we see as an extension of `equinox` for differentiable scientific software (it mostly just implements some less general and more user friendly syntactical method for `pytree` manipulation to help out users with less programming experience). 

We make extensive use of the now deprecated `args` parameter for `filter_grad` etc, since we typically only want to optimise a subset of some models parameters at one time. I've made a general and lightweight wrapper to re-implement this functionality. I want to try and avoid re-building this code in future given that the `equinox` is subject to change. 

I was hoping you could take a quick look and let me know if think this method is robust as the under-the-hood workings of `filter_grad` uses some methods that are unfamiliar to me and I am worried I could be missing some edge cases here. 

```python
import equinox as eqx

def filter_grad(filter_spec, *dec_args, **dec_kwargs):
    def wrapper(func):
        def inner_wrapper(pytree, *args, **kwargs):
            @eqx.filter_grad(*dec_args, **dec_kwargs)
            def recombine(diff, non_diff):
                return func(eqx.combine(diff, non_diff), *args, **kwargs)
            return recombine(*eqx.partition(pytree, filter_spec))
        return inner_wrapper
    return wrapper
```

Any thoughts are greatly appreciated! 

Cheers

**Comment by patrick-kidger** [comment]
There's various nitty things you can add (like `ft.wraps`, or arranging for your wrapped function to be a pytree) but your code basically looks good to me.

Regarding zodiax, I just had a quick skim. Some quick notes:
- Inheriting from `abc.ABC` is unnecessary, Equinox already does this for `Module`.
- On paths: JAX has an internal notion of "keypaths" that is equivalent. [See here.](https://github.com/google/jax/blob/e4d551a217cc11f7aa1cab9859afa079ecfae12b/jax/_src/tree_util.py#L412). At some point this may or may not become public API.
- I'd avoid using the term "pmap", that's usually taken to mean `jax.pmap`.

**Comment by LouisDesdoigts** [comment]
Awesome this is great to hear. The jax `KeyPaths` look very interesting, it seems like things could be improved using this under the hood. Will definitely look into this.

Thanks I really appreciate the help!
