### ISSUE TITLE
register_buffer equivalent

### ISSUE THREAD

**Issue by smorad** [patrick-kidger/equinox#279]
Is there an equinox equivalent of torch's `register_buffer`? I'd like to attach an `Array` to an `eqx.Module` without it becoming a parameter. I'm aware of the `frozen_layer` example, but in my case I never need to "unfreeze" the `Array`. Furthermore, I don't define a loss function -- only a general purpose model. This means that users who want to use my `Module` would have to implement their own loss function, which could be error prone if they forget to freeze the `Array`.

**Comment by patrick-kidger** [comment]
You can call `lax.stop_gradient` where you use it:
```python
class Model(eqx.Module):
    buffer: Array
    param: Array

    def __call__(self, x):
        return self.param * x + lax.stop_gradient(self.buffer)
```
This is probably worthy of an FAQ entry, actually.

**Comment by patrick-kidger** [comment]
Added in #280.

**Comment by smorad** [comment]
Fantastic, thanks!
