### ISSUE TITLE
Configure "bias" in the MLP

### ISSUE THREAD

**Issue by jlperla** [patrick-kidger/equinox#290]
Amazing package.  Would it be possible to extend the `MLP` type in https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/composed.py  to support passing on to the `use_bias` argument for the `Linear` layers?  In many cases, I have found that things work better if there is a bias on only the last output layer, on only the internal layers, and vice versa so separating them would be nice.  I haven't seen cases where you want only the first layer to have a bias, so leaving that one out.

To be more specific, I would imagine,
- In https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/composed.py#L44-L50  add in two arguments: 
```python
use_bias: bool = static_field(),
last_use_bias: bool = static_field(),
```
- And then the code becomes something like
```python
        if depth == 0:
            layers.append(Linear(in_size, out_size, last_use_bias, key=keys[0]))
        else:
            layers.append(Linear(in_size, width_size, use_bias, key=keys[0]))
            for i in range(depth - 1):
                layers.append(Linear(width_size, width_size, use_bias, key=keys[i + 1]))
            layers.append(Linear(width_size, out_size, last_use_bias, key=keys[-1]))
```
etc.  With a few other small changes like defaults for the bias.

Does this sound feasible?  If so, and you are amenable I could create a PR to implement it as practice for working with JAX?  If so and you roughly agree with the approach, just tell me your preferred names for the two arguments.  Alternatives might be `use_hidden_bias` and `use_last_bias` for example.

**Comment by jlperla** [comment]
Thanks.  I will give this a shot in April.  Unit tests should just go in https://github.com/patrick-kidger/equinox/blob/main/tests/test_nn.py#L144-L159 and check shape?

**Comment by patrick-kidger** [comment]
Yup!
