### ISSUE TITLE
Extra examples

### ISSUE THREAD

**Issue by patrick-kidger** [patrick-kidger/equinox#292]
- [x] Add a simple example showing how `eqx.tree_at` is used in its docstring.
- [x] Add an example for scan-over-layers, using `eqx.filter_vmap` and `lax.scan`. (Probably it'd need an `eqx.partition` and an `eqx.combine` either side of the scan, as we don't have a `filter_scan` like operation.) This would be a good candidate for the "tricks" section.

**Comment by matteoguarrera** [comment]
Hi @patrick-kidger, thank you all your work. I am preparing other examples that you might be interested in adding to the repository. Do you have some guidelines on what to do or should I just open a pull request?
I wrote down Notebooks for VAE and VQVAE to further demonstrate capabilities like stateful operation, stop gradients, training and inference mode, etc.

Thank you!

**Comment by patrick-kidger** [comment]
Hey there!

For this kind of thing I'm starting to think about dedicating a whole page of "third party examples", each of which can be hosted elsewhere but for which we can provide a link to. I think what you're suggesting here would be a great first addition to such a page.

WDYT? If you like the idea then feel free to add a `.md` page to the examples (in `mkdocs.yml`) linking to wherever you'd like to host these.

**Comment by matteoguarrera** [comment]
I agree that we might want to have a "awesome-equinox" kind of page somewhere, to reduce the burden of maintenance of the core library! However, I also think we should add more example for topics like stateful operation, stop gradients, and clipping.  
If you agree I can create a "awesome-equinox" repo and we can decide how to proceed further.

**Comment by patrick-kidger** [comment]
Ooh, I hadn't even meant that in the sense of an `awesome-equinox` page, but now that you mention that I rather like it. Absolutely, let's do that.

As for more examples on these topics -- all of that sounds reasonable to me! Perhaps (?) smaller snippets of code if it's on a very specific topic like that?

**Comment by matteoguarrera** [comment]
https://github.com/matteoguarrera/awesome-equinox

**Comment by patrick-kidger** [comment]
Awesome! (Literally!)

For an initial few things worth adding:

- Tagging @AakashKumarNain and @Artur-Galstyan and @nstarman, who I think have each got some cool projects worth listing here.
- There's @dlwh's Levanter.
- The various packages I maintain.
- The many many contents of this page: https://github.com/patrick-kidger/equinox/network/dependents?dependents_after=Mzg0ODU3MTE3NTY

Hmm, what else should we add?

**Comment by nstarman** [comment]
> Tagging ... @nstarman, who I think have each got some cool projects worth listing here.

Thanks! I am a maintainer for https://github.com/GalacticDynamics. We have 

- [unxt](https://github.com/GalacticDynamics/unxt) for unitful quantities (built on `equinox`, through @patrick-kidger's `quax`)
- [coordinax](https://github.com/GalacticDynamics/coordinax) for vectors and coordinates
- [galax](https://github.com/GalacticDynamics/galax) for galactic dynamics

**Comment by AakashKumarNain** [comment]
Thanks for the tag @patrick-kidger.

Here is my [Mistral-7B](https://github.com/AakashKumarNain/mistral_jax) port in Equinox. 

There are a few other projects that are in progress. I will add them here once I am done with them

**Comment by matteoguarrera** [comment]
I think all the projects mentioned are very cool! As a minimum requirements I would start to add projects that have a nice `readme.md` . Can you clean yours guys? :smile:

**Comment by nstarman** [comment]
> Can you clean yours guys?

`unxt`, `coordinax`, `galax` now all have decent readmes.

**Comment by patrick-kidger** [comment]
@mancusolab's [traceax](https://github.com/mancusolab/traceax) deserves a mention as well!

**Comment by Artur-Galstyan** [comment]
Thanks for the mention! My projects' APIs are not yet ready for public usage :( but once they are, I'll let you know with a PR :)
