### ISSUE TITLE
Have `eqx.nn.MLP` use scan-over-layers

### ISSUE THREAD

**Issue by patrick-kidger** [patrick-kidger/equinox#293]

**Comment by boris-kuz** [comment]
Took a crack at this here: https://github.com/patrick-kidger/equinox/pull/294

**Comment by patrick-kidger** [comment]
On balance I'm going to close this. This is (a) difficult to do whilst preserving backward compatibility, (b) probably provides only a small compile-time improvement, and (c) may even hinder runtime performance a little bit.
