### ISSUE TITLE
Jitting leads to much slower execution times and then to a crash (LLVM: resource unavailable) - Question

### ISSUE THREAD

**Issue by Artur-Galstyan** [patrick-kidger/equinox#307]
Hi Patrick,

for my next YT video I want to showcase Eqx for RL and so I use it to train an agent (using policy gradient algorithm) on some gym environments. 

The agent solves the environment easily, which is nice. Then, I just wanted to play around with the `filter_jit` method and place it at different places to see what would happen. The code ran significantly slower and then crashed with this error:

```
LLVM ERROR: pthread_create failed: Resource temporarily unavailable
```

Here's the relevant code snippet for reference:

```python
# eqx.filter_jit <<< This makes the code go 🚀🚀🚀
def train(
    t_optim: GradientTransformation,
    t_opt_state: PyTree,
    t_params: PyTree,
    t_eps_obs: Array,
    t_eps_actions: Array,
    t_eps_rewards: Array,
):
    # eqx.filter_jit <<< slow :(
    def loss_fn(
        l_model: PyTree,
        l_states: Array,
        l_rewards: Array,
        l_actions: Array,
    ) -> Array:
        logits = jax.vmap(l_model)(l_states)
        advantages = get_future_rewards(l_rewards)

        actions = l_actions.reshape(-1)

        l_loss_value = rlax.policy_gradient_loss(
            logits_t=logits,
            a_t=actions,
            adv_t=advantages,
            w_t=jnp.ones_like(advantages),
        )

        return l_loss_value

    # @eqx.filter_jit <<< slow :(
    def step(
        s_params: PyTree,
        s_eps_obs: Array,
        s_eps_rewards: List,
        s_eps_actions: Array,
        s_opt_state: PyTree,
    ):
        s_loss_value, grads = eqx.filter_value_and_grad(loss_fn)(
            s_params, s_eps_obs, s_eps_rewards, s_eps_actions
        )
        updates, s_opt_state = t_optim.update(grads, s_opt_state, s_params)
        s_params = eqx.apply_updates(s_params, updates)
        return s_params, s_opt_state, s_loss_value

    params, opt_state, loss_value = step(
        t_params, t_eps_obs, t_eps_rewards, t_eps_actions, t_opt_state
    )
    return params, opt_state, loss_value


```

Placing the loss function outside of `train` and jitting it makes the code run super fast, too:

```python
#this is super fast!

@eqx.filter_jit
    def loss_fn(...):
        (...)
def train(...):
    (...) # no jits here
```

On the other hand:

```python
# this is super slow!

@eqx.filter_jit
    def loss_fn(...):
        (...)
def train(...):
    (...)
    @eqx.filter_jit
    def step(...):
        (...)
```

And:

```python
# this is also super slow 
# (also useless to jit loss_fn, as it's being called from the jitted step)!

def train(...):
    (...)
    @eqx.filter_jit
    def loss_fn(...):
        (...)
    @eqx.filter_jit
    def step(...):
        (...)
```

I conclude that it's best to use `filter_jit` as "far up" as you can. I would like to understand why this is the case. `filter_jit` should make the code faster if the inputs have static shapes, no?

**Comment by patrick-kidger** [comment]
Hmm. It's a little hard for me to pin down exactly what's going on here, but I think what's probably happening is that the code is getting recompiled each step -- maybe you're passing in some non-JAX-array that changes each step (e.g. a step counter).

This would explain both the slowness (things are getting recompiled) and the LLVM error (which I've seen before when running out of memory -- in this case perhaps the number of cached JIT-compiled functions?)

You could debug this by (a) adding a print statement inside your JIT region, and see if things are getting recompiled; (b) call the following function on each argument you pass to your JIT'd function, and see what might be triggering recompilation: `causing_compilation = lambda x, name: print(f"compiling {name}"); causing_compilation(x, "x"); ...`; (c) checking the memory usage of your program.
