### ISSUE TITLE
equinox and pydantic

### ISSUE THREAD

**Issue by tylerflex** [patrick-kidger/equinox#321]
Hi, I'm really interested in using equinox along with pydantic to make my pydantic models compatible with jax.

I'm wondering whether this is possible and if so, whether there's a proper way to set this up. 

Here's a simple example:

```py
import equinox as eqx
import pydantic as pd
import jax

class MyModel(pd.BaseModel, eqx.Module):
    """Pydantic and equinox model."""

    field1: float
    field2: int = 0

def f(field1: float) -> float:
    obj = MyModel(field1 = field1, field2=1)
    return obj.field1 * obj.field2

jax.grad(f)(1.0)
# should print value of obj.field2
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[41], line 4
      1 import equinox as eqx
      2 import pydantic as pd
----> 4 class MyModel(pd.BaseModel, eqx.Module):
      6     field1: float
      7     field2: int = 0

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Any help or insight would be really appreciated! Thanks

**Comment by patrick-kidger** [comment]
This can be done like so:
```python
import equinox as eqx
import pydantic
import jax


class MetaEqxDantic(type(pydantic.BaseModel), type(eqx.Module)):
    pass


class EqxDantic(pydantic.BaseModel, eqx.Module, metaclass=MetaEqxDantic):
    pass


class MyModel(EqxDantic):
    """Pydantic and equinox model."""

    field1: float
    field2: int = 0


def f(field1: float) -> float:
    obj = MyModel(field1=field1, field2=1)
    return obj.field1 * obj.field2

print(jax.grad(f)(1.0))
```
This is a standard Python thing -- when using custom metaclasses, then it's not enough to just subclass both of the classes themselves. You also have to subclass their metaclasses, and use that as the new metaclass.

This kind of thing can be a bit touch-and-go. It seems to have worked here but this will depend on the implementation details of both Pydantic and Equinox. If you can I'd suggest using both libraries separately -- e.g. validate your input using Pydantic, and then convert it to an Equinox class.

**Comment by tylerflex** [comment]
@patrick-kidger do you know if there's an easy way to construct an `eqx.Module` from either a pydantic class, instance, or dict() containing the fields? for example.

```py
import equinox as eqx
import pydantic as pd
import jax

class ModelPd(pd.BaseModel):
    a: float
    b: int = 0

obj = ModelPd(a=1.0, b=2)

# how to convert to equinox?

# one way:

class ModelEqx(eqx.Module):
    a: float
    b: float

obj2 = ModelEqx(**obj.dict())

# but this requires copying a, b from ModelPd. A way to generate the proper ModelEqx?
```
is the only approach here through defining a metaclass that constructs the eqx.Module out of the pydantic class definition? or is there a simpler way?

**Comment by patrick-kidger** [comment]
Hmm, there's probably a few ways of doing this. But to avoid an X-Y problem: is this just that you want to initialise your model with (a) all the right fields that (b) have all the right types?

If so then this can be done by combining Equinox with a runtime type checker (rather than using pydantic, and needing to define two parallel model hierarchies). For example:
```python
import beartype
import equinox as eqx


@beartype.beartype
class Foo(eqx.Module):
    x: int
    y: str


Foo(3, "hi")
try:
    Foo("hi", 3)
except Exception:
    pass
else:
    assert False
```
