### ISSUE TITLE
Equinox `filter_jit` does not work with AOT compilation

### ISSUE THREAD

**Issue by JeppeKlitgaard** [patrick-kidger/equinox#325]
Hi @patrick-kidger 

I found out today that `equinox.filter_jit` cannot be used with the new `.lower().compile()` AOT compilation:

Taken from JAX documentation:
```python
import jax
import jax.numpy as jnp
import numpy as np

def f(x, y): return 2 * x + y
x, y = 3, 4

lowered = jax.jit(f).lower(x, y)

# Print lowered HLO
print(lowered.as_text())

# Compile function
compiled = lowered.compile()

# Execute the compiled function!
compiled(x, y)
```

Which works as expected

However, changing to using `filter_jit`:
```python
import jax
import jax.numpy as jnp
import numpy as np
import equinox as eqx

def f(x, y): return 2 * x + y
x, y = 3, 4

lowered = eqx.filter_jit(f).lower(x, y)

# Print lowered HLO
print(lowered.as_text())

# Compile function
compiled = lowered.compile()

# Execute the compiled function!
compiled(x, y)
```

Gives a `TypeError`:
> TypeError: function compiled for PyTreeDef(((((None,), (None, None)),), {})), called with PyTreeDef(((*, *), {}))

**Comment by patrick-kidger** [comment]
Also do be aware that you're passing entirely static arguments to `filter_jit` in your example, i.e. you're doing pure-Python computation without actually using any JAX.

**Comment by JeppeKlitgaard** [comment]
Thank you for the fantastically quick work @patrick-kidger! I will give it a spin in a bit.

Granted the example is a bit silly when combined with `equinox.filter_jit` I will agree – it is simply the one from the docs

**Comment by JeppeKlitgaard** [comment]
As far as I can tell, this is working now. Should I close this issue @patrick-kidger?

**Comment by patrick-kidger** [comment]
Yup, let's close this!
