### ISSUE TITLE
Inconsistency in calling MLP relative to other models

### ISSUE THREAD

**Issue by jlperla** [patrick-kidger/equinox#361]
In the progress of doing #358 I noticed the following:
```python
import jax
import jax.nn as jnn
import jax.numpy as jnp
import jax.random as jrandom
from jaxtyping import Array, Float, Int, PyTree  # https://github.com/google/jaxtyping

import equinox as eqx

@jax.jit
@jax.grad
def loss_fn(model, x, y):
    pred_y = jax.vmap(model)(x)
    return jax.numpy.mean((y - pred_y) ** 2)

batch_size, in_size, out_size = 32, 2, 3
key=jax.random.PRNGKey(0)
model_lin = eqx.nn.Linear(in_size, out_size, key=key)
model_seq = eqx.nn.Sequential(
        [
            eqx.nn.Linear(in_size, 4, key=key),
            eqx.nn.Linear(4, 1, key=key),
            eqx.nn.Linear(1, out_size, key=key),
        ]
    )
model_MLP = eqx.nn.MLP(in_size, out_size, 8, 2, key=key)

# Try these three models:
x = jax.numpy.zeros((batch_size, in_size), dtype=jnp.float32)
y = jax.numpy.zeros((batch_size, out_size), dtype=jnp.float32)
grads_lin = loss_fn(model_lin, x, y)
grads_seq = loss_fn(model_seq, x, y)
# grads_MLP = loss_fn(model_MLP, x, y)
```

That all works.  Now if I uncomment the last line (i.e. the `loss_fun(model_MLP, x, y)` it gives the following error:
```
KeyError                                  Traceback (most recent call last)
File [~/anaconda3/envs/jax/lib/python3.9/site-packages/jax/_src/api_util.py:563](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/jesse/Desktop/~/anaconda3/envs/jax/lib/python3.9/site-packages/jax/_src/api_util.py:563), in shaped_abstractify(x)
    562 try:
--> 563   return _shaped_abstractify_handlers[type(x)](x)
    564 except KeyError:

KeyError: 

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
[c:/Users/jesse/Desktop/Untitled-1.ipynb](file:///C:/Users/jesse/Desktop/Untitled-1.ipynb) Cell 6 in ()
     [30](vscode-notebook-cell:/c%3A/Users/jesse/Desktop/Untitled-1.ipynb#W5sZmlsZQ%3D%3D?line=29) grads_lin = loss_fn(model_lin, x, y)
     [31](vscode-notebook-cell:/c%3A/Users/jesse/Desktop/Untitled-1.ipynb#W5sZmlsZQ%3D%3D?line=30) grads_seq = loss_fn(model_seq, x, y)
---> [32](vscode-notebook-cell:/c%3A/Users/jesse/Desktop/Untitled-1.ipynb#W5sZmlsZQ%3D%3D?line=31) grads_MLP = loss_fn(model_MLP, x, y)

    [... skipping hidden 6 frame]

File [~/anaconda3/envs/jax/lib/python3.9/site-packages/jax/_src/api_util.py:554](https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/jesse/Desktop/~/anaconda3/envs/jax/lib/python3.9/site-packages/jax/_src/api_util.py:554), in _shaped_abstractify_slow(x)
    552   dtype = dtypes.canonicalize_dtype(x.dtype, allow_opaque_dtype=True)
    553 else:
--> 554   raise TypeError(
    555       f"Cannot interpret value of type {type(x)} as an abstract array; it "
    556       "does not have a dtype attribute")
    557 return core.ShapedArray(np.shape(x), dtype, weak_type=weak_type,
    558                         named_shape=named_shape)

TypeError: Cannot interpret value of type  as an abstract array; it does not have a dtype attribute
```

Sorry that I don't understand JAX well enough to know if this is expected or a bug.  But I don't believe it was caused by my changes in the PR.

**Comment by patrick-kidger** [comment]
So `jax.jit` (and `jax.grad` etc.) are relatively simplistic: when you pass something into them, JAX will try to convert the object into an array. (So that it can trace+compile its computation graph.)

However, `eqx.nn.MLP(...).activation` is a function. There's no way that this can be understood as an array, so JAX throws an error. The fix is to use the slightly higher-level `equinox.filter_jit` instead. This looks through everything that is passed, and only traces NumPy arrays and JAX arrays. (And forwards everything else into the computation unchanged.)

Have a read of the first two pages of the Equinox documentation [here](https://docs.kidger.site/equinox/), in particular the section on filtering.

(I swear this all makes sense if you have the right mental model for JAX's tracing JIT compiler... :D )

**Comment by jlperla** [comment]
Great.  Replacing with `@eqx.filter_jit
@eqx.filter_grad` everything works.

Not quite there yet, but slowly starting to come together!

I had adapted the code from the https://docs.kidger.site/equinox/#quick-example  
I now see the comment in the https://docs.kidger.site/equinox/all-of-equinox/#filtering about the MLP.

This issue should be closed, but one thought is that the `@eqx.filter_jit` and `@eqx.filter_grad` could be introduced in the https://docs.kidger.site/equinox/#quick-example section so people copy/paste it from the start (then say that in this example you could also use `@jax.jit @jax.grad` ?

**Comment by jlperla** [comment]
Similarly, the code on the front in https://github.com/patrick-kidger/equinox#quick-example  maybe it is worth showcasing the filters at that point?
