### ISSUE TITLE
Frozen field

### ISSUE THREAD

**Issue by mfkasim1** [patrick-kidger/equinox#37]
Is there a special reason on why the fields in `equinox.Module` are frozen? It makes it harder to implement modules with running states like `BatchNorm`.

**Comment by patrick-kidger** [comment]
Yep, this is deliberate -- in JAX arrays are immutable, so we stick with this philosophy with modules in Equinox. Helps to guard against user error! If you want to mutate something then you can do so out-of-place using `eqx.tree_at`.

**Comment by mfkasim1** [comment]
Thanks for the explanation!
