### ISSUE TITLE
Possible improvement to serialization documentation

### ISSUE THREAD

**Issue by bytbox** [patrick-kidger/equinox#370]
I'm not completely sure this is a good idea, but... for me, a common desire is "package up, in one file, both the pytree leaves, and instructions for creating the pytree skeleton". Concretely, I might have a function
```python
def make_model(key, **hyperparameters):
    return MyModel(depth=hyperparameters['depth'], key=key)
```
and then I would like to save in a single file both the dict `hyperparameters` and the weights of `MyModel`.

This is of course easy, but it's not immediately obvious from the documentation that it's possible at all (at least it wasn't to me). I think it's worth adding to the "Tricks" page (or perhaps FAQ) a section explaining that it _is_ possible (because `tree_serialise_leaves` is happy to dump to any `BinaryIO`), with an example like:
```python
def save_model(filename, model, hyperparameters)
  leaves = io.BytesIO()
  eqx.tree_serialise_leaves(leaves, model)
  leaves.seek(0)
  with open(filename, 'wb') as f:
    pickle.dump((hyperparameters, leaves), f)
```

**Comment by patrick-kidger** [comment]
This makes sense to me! I'd be happy to take a pull request on this -- I could see a more fully-featured example being a good way to demonstrate how to make this pattern work in full. FWIW this is the approach I take in my own code. The only requirement is that the hyperparameters themselves must be serialisable, e.g. not a Python function.

For completeness I note that there is also the [Orbax](https://github.com/google/orbax) library for serialisation. They support asynchronous serialisation, and sharded (multi-device) JAX arrays, which are useful for bigger models. It looks like their `orbax.checkpoint.PyTreeCheckpointer()` operates on essentially the same premise as `eqx.tree_{de,}serialise_leaves` in that it expects a PyTree structure at deserialisation time, so probably the pattern used here would apply to them too.

**Comment by patrick-kidger** [comment]
Closing as done!
