### ISSUE TITLE
Feature request: Add minimal gated unit (MGU)

### ISSUE THREAD

**Issue by carlosgmartin** [patrick-kidger/equinox#371]
Feature request: Add [minimal gated unit (MGU)](https://en.wikipedia.org/wiki/Gated_recurrent_unit#Minimal_gated_unit) to [equinox.nn](https://docs.kidger.site/equinox/api/nn/rnn/). I can open a PR if desired.

**Comment by patrick-kidger** [comment]
Thanks for the suggestion! There are a great many RNN variants out there, and I think that it makes most sense for Equinox to focus just on the major few. In practice I think that means anything beyond the basic GRU/LSTM is probably out-of-scope.
