### ISSUE TITLE
Using jaxopt for optimization

### ISSUE THREAD

**Issue by leonard-gleyzer** [patrick-kidger/equinox#376]
Hello,

I'd like to use the L-BFGS solver in the jaxopt library `jaxopt.LBFGS` (https://jaxopt.github.io/stable/_autosummary/jaxopt.LBFGS.html#jaxopt.LBFGS) when optimizing an `equinox.nn.MLP`, but I'm running into an issue:

MWE:

```python
import equinox as eqx
import jax
import jax.numpy as jnp
import jax.random as jr
import jaxopt


model = eqx.nn.MLP(1, 2, 2, 1, key=jr.PRNGKey(0))

def loss_fn(model, x, y):
    preds = jax.vmap(model)(x)
    return jnp.mean((preds - y) ** 2)

x = jnp.expand_dims(jnp.linspace(0, 2 * jnp.pi, 250), 1)
y = jnp.sin(x)

solver = jaxopt.LBFGS(fun=loss_fn, maxiter=500)
res = solver.run(model, x=x, y=y)
```

gives the error

`res = solver.run(model, x=x, y=y)
  File "/opt/miniconda3/envs/jax-env/lib/python3.10/site-packages/jaxopt/_src/base.py", line 354, in run
    return run(init_params, *args, **kwargs)
  File "/opt/miniconda3/envs/jax-env/lib/python3.10/site-packages/jaxopt/_src/implicit_diff.py", line 251, in wrapped_solver_fun
    return make_custom_vjp_solver_fun(solver_fun, keys)(*args, *vals)
TypeError: Value <jax._src.custom_derivatives.custom_jvp object at 0x12426d9f0> with type <class 'jax._src.custom_derivatives.custom_jvp'> is not a valid JAX type`

From your [documentation](https://docs.kidger.site/equinox/faq/#typeerror-not-a-valid-jax-type), this type of issue can be resolved by using `eqx.filter_jit`, though I'm not sure how to accomplish this with jaxopt.

Thank you!

**Comment by patrick-kidger** [comment]
jaxopt is assuming that `model` is of type `PyTree[Array]`, i.e. that it contains only arrays. You'll probably want to use filtering to pass the static pieces via closure:
```python
model = ...
dynamic_model, static_model = eqx.partition(model, eqx.is_array)

def loss_fn(dynamic_model, x, y):
    model = eqx.combine(dynamic_model, static_model)
    ...

solver = ...
solver.run(dynamic_model, ...)
```
Incidentally, doing the above for `jax.{jit, grad, ...}` etc. is exactly the purpose of `eqx.filter_{jit, grad, ...}` etc.

**Comment by leonard-gleyzer** [comment]
Thank you!

**Comment by BabaYara** [comment]
Sorry for re-opening this issue. 
I was wondering how one can update the model once the solver converges. 
It returns a params and state object. I have tried something like this, but it doesn't seem to be working:
new_network = eqx.apply_updates(dynamic_model, res.params)
new_network = eqx.combine(new_network, static_model)

the new network has a loss as big as the initial model.

**Comment by patrick-kidger** [comment]
You shouldn't need `eqx.apply_updates` here. Just `eqx.combine(dynamic_model, static_model)`, where `dynamic_model` is the JAXopt output.

**Comment by BabaYara** [comment]
I am definitely missing something then. 
Consider this simple working example:
`import equinox as eqx
import jax
import jax.numpy as jnp
import jax.random as jr
import jaxopt


model = eqx.nn.MLP(1, 1, 2, 2, key=jr.PRNGKey(0))
 
def loss_fn(model, x, y):
    preds = jax.vmap(model)(x)
    return jnp.mean((preds - y) ** 2)

x = jnp.expand_dims(jnp.linspace(0, 2, 250), 1)
y = 10.0 + 4.0*x

dynamic_model, static_model = eqx.partition(model, eqx.is_array)

def loss_fn(dynamic_model, x, y):
    model = eqx.combine(dynamic_model, static_model)
    preds = jax.vmap(model)(x)
    return jnp.mean((preds - y) ** 2)

dynamic_model, static_model = eqx.partition(model, eqx.is_array)
loss_fn(dynamic_model, x, y)

solver = jaxopt.LBFGS(fun=loss_fn, maxiter=10, tol = 1e-12, verbose = True, jit = False)
res = solver.run(dynamic_model, x=x, y=y)

loss_fn(res.params, x, y)
 `

The first loss on initialization is 206.52983 (loss_fn(dynamic_model, x, y))

When I run the solver, the LBFGS .loss falls to 2.924353e-07
But when I run the final loss with the new model (loss_fn(res.params, x, y)), the loss only goes to 5.37.

So it feels like something is off.
I tried it with Flax, and the LBFGS loss after training is very close to the one I get from running the loss function with the model after.

**Comment by BabaYara** [comment]
This is the Flax example:
``
from typing import Sequence

import numpy as np
import jax
import jax.numpy as jnp
import flax.linen as nn
import optax 
from jaxopt import LBFGS, BFGS, OptaxSolver

class MLP(nn.Module):
  features: Sequence[int]

  @nn.compact
  def __call__(self, x):
    for feat in self.features[:-1]:
      x = nn.relu(nn.Dense(feat)(x))
    x = nn.Dense(self.features[-1])(x)
    return x

model  = MLP([12, 8, 4])
def loss_fn(params, x, y):
    # preds = jax.vmap(model)(x)
    preds = model.apply(params, x)
    return jnp.mean((preds - y) ** 2)

x = jnp.expand_dims(jnp.linspace(0, 2, 250), 1)
y = 10.0 + 4.0*x
params = model.init(jax.random.PRNGKey(0), x)


``

**Comment by patrick-kidger** [comment]
An improvement from 206 to 5.37 suggests that LBFGS is successfully optimising your model. I don't know exactly what LBFGS is verbosely printing out that has a value of O(1e-7); you'd have to check the JAXopt documentation.

The size of your MLP is different between JAXopt and Equinox -- it's much larger for JAXopt.

**Comment by BabaYara** [comment]
I believe I found the issue:
Correcting the loss function by making sure the dimensions matched, solved it.,
 def loss_fn(dynamic_model, x, y):
    model = eqx.combine(dynamic_model, static_model)
    preds = jax.vmap(model)(x)
    return jnp.mean((jnp.expand_dims(preds, axis = 1) - y) ** 2)
 
Now it converges as expected. 
Thanks a lot for the quick response.

**Comment by patrick-kidger** [comment]
Btw, folks on this issueay be interested to know that we recently released a new optimisation library, [Optimistix](https://github.com/patrick-kidger/optimistix/) built using Equinox.
