### ISSUE TITLE
Support jax.nn.initializers in Module initialization API?

### ISSUE THREAD

**Issue by kngwyu** [patrick-kidger/equinox#387]
[jax.nn.initializers](https://jax.readthedocs.io/en/latest/jax.nn.initializers.html) provides several commonly used initializers such as `orthogonal` and `glorot_normal`. I'd like to propose supporting these initializers as arguments of common modules, e.g., :
```python
class Linear(Module):
...
    def __init__(
        self,
        in_features: Union[int, Literal["scalar"]],
        out_features: Union[int, Literal["scalar"]],
        use_bias: bool = True,
        w_init: jax.nn.initializers.Initializer = jax.nn.initializers.lecun_uniform(),
        b_init: jax.nn.initializers.Initializer = jax.nn.initializers.lecun_uniform(),
        *,
        key: PRNGKey
    ):
...
```
I know that now we can manually call these initializers, but doing custom initialization for many layers can be cumbersome. Taking initializers as arguments makes custom initialization much easier and clearer. I have two possible concerns with it, though:
- It can make the API complex especially for complex modules
- `vmap`ping  `Module.__init__` can cause some troubles when we give specific dimensions (e.g., `in_axis=1`) to initializers

Given these considerations, I'm still thinking about these APIs better, and happy to hear your opinions. I'm also happy to implement these things if you are down to this idea.

**Comment by patrick-kidger** [comment]
This request comes up every now and again, e.g.
#94
#179
and so far the answer has been to do custom parameter initialisation [using `equinox.tree_at`, as in these docs](https://docs.kidger.site/equinox/tricks/#custom-parameter-initialisation).

For example you can wrap
```python
def linear(*args, **kwargs):
    out = eqx.nn.Linear(*args, **kwargs)
    out = eqx.tree_at(lambda l: l.bias, out, replace_fn=jnp.zeros_like)
    return out
```
and use `linear` everywhere you were previously using `eqx.nn.Linear`, if you so wish.

So far I've resisted adding custom initialisers as this adds quite a lot of complexity -- e.g. a `MultiheadAttention` layer may in principle want different initialisers for each of its projections, so the API swiftly gets out of hand.

**Comment by kngwyu** [comment]
I see. Thank you for your explanation. I agree that it would add unreasonable complexity to `__init__` arguments of complex models.

Instead, how do you think about providing some syntax sugar to write this code to gather params?
```python
  get_weights = lambda m: [x.weight
                           for x in jax.tree_util.tree_leaves(m, is_leaf=is_linear)
                           if is_linear(x)]
```
For example, `tree_filter_leaves` like below could be useful:
```python
def tree_filter_leaves(
    select_fn_or_type: Callable[[_Node], bool] | Type,
    pytree: PyTree,
    map_fn: Callable[[_Node], Any] = lambda x: x,
) -> PyTree:
    if isinstance(select_fn_or_type, type):
        select_fn = lambda node: isinstance(node, select_fn_or_type)
    else:
        select_fn = select_fn_or_type
    leaves = jtu.tree_leaves(pytree, is_leaf=select_fn)
    return tuple(map(map_fn, filter(select_fn, leaves)))
```

**Comment by patrick-kidger** [comment]
I don't think that this comes up frequently enough (or that implementing the above is difficult enough) that it's worth adding a new function to Equinox itself. Adding the above probably also means adding `tree_filter_map` for example, and then the API surface gets even larger!

**Comment by kngwyu** [comment]
I see. Maybe it's better to just have this in my personal toolbox. Thank your for the discussion.

**Comment by adzcai** [comment]
Here's a simple wrapper around `eqx.tree_at` that makes it easier to pass a sequence of `jax.nn.initializers.Initializer`s:

```python
def tree_initialize(
    get_weights: Callable[[PyTree], Sequence[Array]],
    model: PyTree,
    initializers: Sequence[jax.nn.initializers.Initializer],
    *,
    key: Key[Array, ""],
):
    weights = get_weights(model)
    weights = [
        init(k, weight.shape, weight.dtype)
        for weight, init, k in zip(
            weights,
            initializers,
            jr.split(key, len(weights)),
            strict=True,
        )
    ]
    return eqx.tree_at(get_weights, model, weights)

model = eqx.nn.MLP(...)
model = tree_initialize(
  lambda model: [linear.weight for linear in model.layers] + [linear.bias for linear in model.layers],
  model,
  [jax.nn.initializers.orthogonal()] * len(model.layers) + [jax.nn.initializers.zeros] * len(model.layers),
  key = jax.random.key(42)
)
```

**Comment by LambdaP** [comment]
It is not directly related to the original question, but I'd like to point out that some functions in `jax.nn.initializers` are, not quite incompatible with Equinox, but counter-intuitive to use.

I encountered this issue when trying to use `initializers.delta_orthogonal()`. The following snippet seems perfectly reasonable:

```python
conv = eqx.nn.Conv2d(32,32,3, key=key1)
init_fn = jax.nn.initializers.delta_orthogonal()

ortho_weight = init_fn(key2, conv.weight.shape)
conv = eqx.tree_at(lambda l: l.weight, conv, ortho_weight)
```
…but it does something quite different than we'd naively expect. The reason is that here `init_fn()` expects a tensor of shape `(3,3,32,32)` but `conv.weight.shape` is `(32,32,3,3)`, i.e., `delta_orthogonal()` silently assumes a channels-last convention. In practice, instead of getting one delta 3×3 matrix for each (c_in, c_out) pair, we get one dense 3×3 matrix at index (15,15) and zero matrices everywhere else. Using `initializers.delta_orthogonal()` in this case requires doing something like
```python
init_ortho = jax.nn.initializers.orthogonal()

def init_fn(key, shape):
    c_shape = shape[:2]
    kh, kw = shape[-2:]
    ortho_mat = init_ortho(key, c_shape)
    out = jnp.zeros(shape, dtype=dtype)
    out = out.at[:,:,int(kh//2), int(kw//2)].set(ortho_mat)
    return out
# then use `init_fn()` as before
```

I'm not exactly sure what should ideally happen with respect to this, but maybe we could warn Equinox users about this?
