### ISSUE TITLE
Possible to use jax.vectorize?

### ISSUE THREAD

**Issue by chrisflesher** [patrick-kidger/equinox#388]
I found recently there is a `jax.vectorize` decorator that really simplifies `vmap` calls, like this:

```
@functools.partial(jnp.vectorize, signature='(n),(n)->(n)')
def multiply_quat(p: jax.Array, q: jax.Array) -> jax.Array:
  cross = jnp.cross(p[:3], q[:3])
  return jnp.array([p[3]*q[0] + q[3]*p[0] + cross[0],
                    p[3]*q[1] + q[3]*p[1] + cross[1],
                    p[3]*q[2] + q[3]*p[2] + cross[2],
                    p[3]*q[3] - p[0]*q[0] - p[1]*q[1] - p[2]*q[2]])
```

I am really liking this style because you don't have to worry about chaining `vmap` calls or specifing `in_axes`. Was wondering if there might be a way to support this style with `equinox` modules already? It wasn't super obvious to me if this is possible already. Thanks!

**Comment by patrick-kidger** [comment]
Yes, this should work directly with Equinox -- just like `jax.vmap` does.

Probably the only thing to be careful of is not write something like
```python
class Model(eqx.Module):
    ...

    def __init__(self, ...):
        self.layer = jax.vectorize(eqx.nn.Linear(...), ...)
```
as the return from `jax.vectorize` isn't a pytree.

**Comment by chrisflesher** [comment]
Ok, thank you for the info.
