### ISSUE TITLE
Cannot combine eqx.nn.MLP with lax.cond

### ISSUE THREAD

**Issue by mathieu-reymond** [patrick-kidger/equinox#389]
Hi,

I've been trying to combine equinox modules with `jax.lax.cond`, resulting in the following error:
```
TypeError: Value <PjitFunction of <function jax.numpy.tanh at 0x7fd1cc3f8790>> with type <class 'jaxlib.xla_extension.PjitFunction'> is not a valid JAX type
```

I can reproduce this behavior with the following MWE:

```python
import jax
import jax.numpy as jnp
import equinox as eqx

def polyak_averaging(net1, net2, tau):
    return jax.tree_map(
        lambda w1, w2: w1*tau+w2*(1-tau), net1, net2, is_leaf=eqx.is_inexact_array)

rng = jax.random.PRNGKey(0)
rng_1, rng_2 = jax.random.split(rng)
net1 = eqx.nn.MLP(in_size=4, out_size=24, width_size=24, depth=1, activation=jax.nn.tanh, final_activation=jax.nn.tanh, key=rng_1)
net2 = eqx.nn.MLP(in_size=4, out_size=24, width_size=24, depth=1, activation=jax.nn.tanh, final_activation=jax.nn.tanh, key=rng_2)

for i in jnp.arange(2):
    net2 = jax.lax.cond(
        i%2 == 0,
        lambda net1__net2: polyak_averaging(net1__net2[0], net1__net2[1], 0.1),
        lambda net1__net2: net1__net2[1],
        (net1, net2)
    )
```

Basically the `activation` and `final_activation` fields in `nn.MLP` are the cause of the issue. I've managed to solve this by making them static using `static_field()`, but I am not sure if this is a desirable solution. I think the alternative would be to preprocess `net1` and `net2` using `eqx.partition` before the `cond`, and put them back together with `eqx.combine` afterwards, but I would like to avoid having to do that (my actual code is a bit more involved, and calls the network inside true and false functions).

Can I safely make the activation fields static?

**Comment by patrick-kidger** [comment]
Hey there! So indeed `partition` and `combine` is the expected way to handle this. If this is a pattern you use frequently then you could write a "`filter_cond`" function to do this for you.

I've contemplated adding such "filter higher-order primitives" to Equinox before, but it hasn't come up frequently enough that I've felt the need.

In terms of making activation functions static -- this is okay only as long as the activation function is not itself a pytree with parameters -- e.g. `eqx.nn.PReLU.

**Comment by mathieu-reymond** [comment]
Thank you for the quick reply! Good point about the activation functions with parameters, I'll write a wrapper that does the partitioning and combining automatically.
