### ISSUE TITLE
Hashing rule question

### ISSUE THREAD

**Issue by ASEM000** [patrick-kidger/equinox#393]
Hello, 
I am confused about this behavior. Why is this the case? 
specifically, why do you hash by leaves values and not include the class definition in the hash rule?

```python
import equinox as eqx 

class Tree1(eqx.Module):
    a:int=1
    b:int=2

class Tree2(eqx.Module):
    c:int=1
    d:int=2

assert hash(Tree1()) == hash(Tree2()) == hash((1,2))
```

**Comment by patrick-kidger** [comment]
No particular reason. Either approach is acceptable.
