### ISSUE TITLE
Combining Ensemble

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/equinox#397]
In the ensembling section (https://docs.kidger.site/equinox/tricks/#ensembling), the example uses a vmap-ed creation. But if I have a list of MLPs (of the same size) not created with vmap, and I want to go from List[eqx.Module] -> eqx.Module, what is the best way to do that? Since I can't vmap over a list of modues (see below). I haven't been able to figure any way (basically the exact opposite of the function here: https://github.com/patrick-kidger/equinox/issues/313#issuecomment-1516340272). I looked at the combine function, but that replaces the Nones (when each MLP has no Nones). I feel like there is an easy way to do this that I am overlooking, but I can't seem to think of it. Any suggestions would be much appreciated. 

Here is a simple example of my goal: 

```python
import jax
import equinox as eqx

key = jax.random.PRNGKey(0)
keys = jax.random.split(key, 8)

def make_ensemble(keys):
    return [eqx.nn.MLP(2, 2, 2, 2, key=key) for key in keys]

ensemble = make_ensemble(keys)

def combine_ensemble(mlps):
    pass

@eqx.filter_vmap
def evaluate_per_ensemble(model, x):
    return model(x)

new_mlps = combine_ensemble(ensemble)
evaluate_per_ensemble(new_mlps, jax.random.normal(key, (8, 2))) # can't vmap over just ensemble, which is a list
```

**Comment by patrick-kidger** [comment]
Something like
```python
mlps = [MLP(...), ...]

def _stack(*args):
    if eqx.is_array(args[0]):
        return jnp.concatenate(args)
    else:
        assert all(args[0] == arg for arg in args[1:])
        return args[0]

ensemble = jax.tree_util.tree_map(_stack, *mlps)
```
should work.

**Comment by lockwo** [comment]
When I did that I got an error 

```
ValueError: vmap got inconsistent sizes for array axes to be mapped:
  * most axes (6 of them) had size 16, e.g. axis 0 of argument _dynamic_args[0].layers[0].weight of type float32[16,2];
  * one axis had size 8: axis 0 of argument _dynamic_args[1] of type float32[8,2]
  ```

I think because it make the shapes [16, 2] instead of [8, 2, 2].

If I did

```python
exp_dim = lambda x: jnp.expand_dims(x, axis=0)
def _stack(*args):
    if eqx.is_array(args[0]):
        return jnp.concatenate([exp_dim(i) for i in args])
    else:
        assert all(args[0] == arg for arg in args[1:])
        return args[0]
```

It ran without errors (and I think its correct?)

**Comment by patrick-kidger** [comment]
Ah sorry, I meant to write `stack` instead of `concatenate`.

**Comment by lockwo** [comment]
Awesome, thank you for the help and quick response!
