### ISSUE TITLE
Version Issues when using Jax 0.4.6

### ISSUE THREAD

**Issue by AnikenC** [patrick-kidger/equinox#403]
Hello!

In my virtual environment, I had been using a slightly older version of Jax (0.4.6) that should have been compatible with Equinox 0.10.4 however there was one small issue. I actually spotted this while using Diffrax, however, the specific file which does not match is in Equinox.

In equinox/equinox/_module.py line 158, the function jax.tree_util.register_pytree_with_keys has an extra argument flatten_func passed. For Jax version 0.4.6, the register_pytree_with_keys doesn't take in the flatten_func argument, however for more recent versions like 0.4.13 it does accept the argument. As a result, I was unable to import equinox (and diffrax resultantly).

To fix this all I did was update Jax and Jaxlib to their latest versions, and the bug went away. However, updating the required Jax versions for Equinox and Diffrax might be helpful, as it appears that specifying Jax 0.4.4+ is not sufficient.

**Comment by patrick-kidger** [comment]
Thanks for the report! I've just fixed the documentation to state this correctly.
