### ISSUE TITLE
bug in jax-metal or in equinox?

### ISSUE THREAD

**Issue by nihcompmed** [patrick-kidger/equinox#404]
I've used equinox on Linux boxes and standard Mac installs with no problems. However, I just installed jax-metal to use the AMD GPU on my desktop and I get the following unhashable type list error right at the import equinox as eqx line. Not quite sure how or why a list would not give this error  on a Mac CPU/Linux GPU but only on jax-metal.  Any suggestions appreciated. Thank you for all the work you've done on this framework. Big fan of simplicity!

TypeError                                 Traceback (most recent call last)
Cell In[1], line 10
      7 import numpy as np
      8 import optax  # https://github.com/deepmind/optax
---> 10 import equinox as eqx

File ~/jax-metal/lib/python3.9/site-packages/equinox/__init__.py:3
      1 import importlib.metadata
----> 3 from . import internal as internal, nn as nn
      4 from ._ad import (
      5     filter_closure_convert as filter_closure_convert,
      6     filter_custom_jvp as filter_custom_jvp,
   (...)
     11     filter_vjp as filter_vjp,
     12 )
     13 from ._better_abstract import (
     14     AbstractClassVar as AbstractClassVar,
     15     AbstractVar as AbstractVar,
     16 )

File ~/jax-metal/lib/python3.9/site-packages/equinox/internal/__init__.py:5
      1 from .._better_abstract import (
      2     AbstractClassVar as AbstractClassVar,
      3     AbstractVar as AbstractVar,
      4 )
----> 5 from .._compile_utils import (
      6     hashable_combine as hashable_combine,
      7     hashable_partition as hashable_partition,
      8 )
      9 from .._doc_utils import doc_remove_args as doc_remove_args, doc_repr as doc_repr
     10 from .._enum import Enumeration as Enumeration

File ~/jax-metal/lib/python3.9/site-packages/equinox/_compile_utils.py:12
      9 from jaxtyping import PyTree
     11 from ._caches import internal_caches
---> 12 from ._module import Module
     15 def hashable_filter(pytree: PyTree, filter_fn: Callable):
     16     leaves = jtu.tree_leaves(pytree)

File ~/jax-metal/lib/python3.9/site-packages/equinox/_module.py:17
     15 from ._doc_utils import doc_repr
     16 from ._pretty_print import tree_pformat
---> 17 from ._tree import tree_equal
     20 _P = ParamSpec("_P")
     21 _T = TypeVar("_T")

File ~/jax-metal/lib/python3.9/site-packages/equinox/_tree.py:10
      8 from ._custom_types import sentinel
      9 from ._doc_utils import doc_repr
---> 10 from ._filters import is_array
     13 if TYPE_CHECKING:
     14     _Node = Any

File ~/jax-metal/lib/python3.9/site-packages/equinox/_filters.py:11
      7 import numpy as np
      8 from jaxtyping import PyTree
---> 11 AxisSpec = Union[bool, Callable[[Any], bool]]
     14 #
     15 # Filter functions
     16 #
     19 def is_array(element: Any) -> bool:

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py:243, in _tp_cache.<locals>.inner(*args, **kwds)
    241 except TypeError:
    242     pass  # All real errors (not unhashable args) are raised below.
--> 243 return func(*args, **kwds)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py:316, in _SpecialForm.__getitem__(self, parameters)
    314 @_tp_cache
    315 def __getitem__(self, parameters):
--> 316     return self._getitem(self, parameters)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py:421, in Union(self, parameters)
    419 msg = "Union[arg, ...]: each arg must be a type."
    420 parameters = tuple(_type_check(p, msg) for p in parameters)
--> 421 parameters = _remove_dups_flatten(parameters)
    422 if len(parameters) == 1:
    423     return parameters[0]

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py:215, in _remove_dups_flatten(parameters)
    213         params.append(p)
    214 # Weed out strict duplicates, preserving the first of each occurrence.
--> 215 all_params = set(params)
    216 if len(all_params) < len(params):
    217     new_params = []

TypeError: unhashable type: 'list'

**Comment by patrick-kidger** [comment]
I think I recognise this as a bug with Python 3.9.<something small>. Try updating your Python version to 3.9.<something larger> and I think should be resolved.

**Comment by nihcompmed** [comment]
Thank you for that very quick response. That was it.
