### ISSUE TITLE
New version breaks backsolve through diffrax

### ISSUE THREAD

**Issue by joglekara** [patrick-kidger/equinox#411]
Hey I'm not sure wtf is going on but I think the new equinox broke the `backsolveAdjoint` method in diffrax

I'm getting

`ValueError: Tuple arity mismatch: 2 != 3; tuple: (State(` for my backsolve-based tests

I'll dig but you might already know what's up so thought I'd drop a note

**Comment by patrick-kidger** [comment]
Ach, that's unfortunate! Can you create a MWE? I did run the Diffrax test suite before doing this release of Equinox, but it looks like something got missed.

**Comment by patrick-kidger** [comment]
I've managed to reproduce this one locally. Looks like we'll need another hotfix release of Equinox shortly.
(This release has been unusually rocky!)

**Comment by patrick-kidger** [comment]
Alright, I think this should be fixed now. Any issues, let me know!
