### ISSUE TITLE
typo on the website

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/equinox#428]
Hi,

I'm bringing to your attention a minor issue in the equinox documentation. I believe [here](https://docs.kidger.site/equinox/examples/score_based_diffusion/) the character `->` is displayed as `-&gt;` in the einops functions, in the model definition.

Best,

**Comment by patrick-kidger** [comment]
Bother! Thanks for the report. Looks like this affects all the examples that use the `>` character.

**Comment by patrick-kidger** [comment]
Now fixed in #538!
