### ISSUE TITLE
Is it possible to create abstract function compositions? 

### ISSUE THREAD

**Issue by RezaRob** [patrick-kidger/equinox#430]
Thanks a lot for equinox!

Question 1:
Is there a way to "late-freeze" a Module or late-convert it to a PyTree so that we can manipulate it until it's ready?

Question 2:
Does it make sense to use such a mechanism to create "abstract composable functions?"

For example, if you wanted to do this:

```
import copy

"""  parameters won't be initialized here; only "abstract" objects are created: """

L = LinearModel(output=10)
M = Custom_Model(output=None)  # <-- output to be determined automatically later just like all inputs 
N = LinearModel(output=30)

""" create abstract functions f1 and f2 with undetermined input "None" """

f1 = L(M(None, N(None)), N(None))
f2 = copy.deepcopy(f1)

x1 = jax.numpy.ones((100, 100))
x2 = jax.numpy.ones((10, 10))

"""  
initialize parameters based on input shapes (x.shape) and do all the work of setting up the objects 
and determining input sizes of all these functions. A "Linear model" concatenates and flattens it's 
multiple inputs if necessary. After that, rewrite the __call__() methods to point 
to proper jax.jit functions which handle the required input types.

After this stage, f becomes a valid "PyTree" (or callable equinox Module object) that can be used 
like any other:
""" 

f1 = L(M(x1, N(x1)), N(x1))
f2 = L(M(x2, N(x2)), N(x2))

""" get the gradient """

g1 = f1.grad()
g2 = f2.grad()
print(g(x1), g(x2))
```

Is there a nice way of doing this? I don't know enough about PyTrees?

**Comment by patrick-kidger** [comment]
You could do this by wrapping Equinox in your own DSL to get the behaviour you want.

I don't think you'd need to worry about pytrees -- just write normal Python code. As all of this would happen before you interact with any JAX transforms, you should be fine.

**Comment by RezaRob** [comment]
Yes, you're right, that seems like the easiest way to do it. 

Also, if you think of any reason why that's a bad idea (not practical/useful in ML?) I would greatly appreciate a tip. 

Many thanks.

**Comment by patrick-kidger** [comment]
I think this approach works well for neural networks. I don't think it works as well for some of the other more complicated things than Equinox is used for (linear solvers, differential equation solvers etc.). But as long as you're doing NN then I think you should be fine.

**Comment by RezaRob** [comment]
Thank you so much for the tip. If possible, it would be really nice to have some relevant example of a differential equation solver in the examples directory.

**Comment by patrick-kidger** [comment]
If you're interested in differential equations, then check out [Diffrax](https://github.com/patrick-kidger/diffrax). This is built on top of Equinox.
