### ISSUE TITLE
Is there a way to pass a submodule without causing a copy?

### ISSUE THREAD

**Issue by ameya98** [patrick-kidger/equinox#433]
I hit this bug when trying to pass a submodule `A` to another submodule `B`. It seems like a distinct copy of `A` is created.

**Comment by patrick-kidger** [comment]
Have you seen https://docs.kidger.site/equinox/faq/#a-module-saved-in-two-places-has-become-two-independent-copies?

**Comment by ameya98** [comment]
I have, but I was wondering if there was a way out. I’m actually passing a function that calls the submodule A inside of it, yet the copy still seems to happen.
