### ISSUE TITLE
Performance vs `jax.tree_util.Partial`

### ISSUE THREAD

**Issue by Jordan-Dennis** [patrick-kidger/equinox#44]
Hi @patrick-kidger,
Following on from (this issue) [https://github.com/patrick-kidger/diffrax/issues/76], I tried to determine what was causing the `jit` to bottleneck for `diffrax`. I believe that it may have something to do with `equinox`. Here is an example of my reasoning based on the canonical example for `equinox`
```py
import equinox 
import jax
jax.config.update("enable_x64")

class Linear(equinox.Module):
    weight: jax.numpy.ndarray
    bias: jax.numpy.ndarray

    def __init__(self, in_size, out_size, key):
        wkey, bkey = jax.random.split(key)
        self.weight = jax.random.normal(wkey, (out_size, in_size))
        self.bias = jax.random.normal(bkey, (out_size,))

    def __call__(self, x):
        return self.weight @ x + self.bias

@jax.jit
@jax.grad
def loss_fn(model, x, y):
    pred_y = jax.vmap(model)(x)
    return jax.numpy.mean((y - pred_y) ** 2)

batch_size, in_size, out_size = 32, 2, 3
model = Linear(in_size, out_size, key=jax.random.PRNGKey(0))
x = jax.numpy.zeros((batch_size, in_size))
y = jax.numpy.zeros((batch_size, out_size))

%%timeit
grads = loss_fn(model, x, y)

So the idea is to repeat the equinox implementation functionally and see what happens

def init_linear(in_size, out_size, key):
    wkey, bkey = jax.random.split(key)
    weight = jax.random.normal(wkey, (out_size, in_size))
    biases = jax.random.normal(bkey, (out_size,))
    return weight, biases

batch_size, in_size, out_size = 32, 2, 3
weights, biases = init_linear(in_size, out_size, key=jax.random.PRNGKey(0))

@jax.tree_util.Partial
@jax.jit
def run_model(x, /, weights=weights, biases=biases):
    return weights @ x + biases

x = jax.numpy.zeros((batch_size, in_size))
y = jax.numpy.zeros((batch_size, out_size))

%%timeit
grads = loss_fn(run_model, x, y)
```
Sorry for being a thorn, and thanks in advance for chasing this up.
Jordan

**Comment by patrick-kidger** [comment]
I'm afraid your code isn't doing what you think it does. Have a look at the final `grads`. This doesn't actually have any JAX arrays in it, i.e. it is essentially free to compute. This is because you've captured `weights` and `biases` as default arguments in the `jax.tree_util.Partial`-wrapped `run_model`, and default arguments aren't part of the PyTree structure.

**Comment by Jordan-Dennis** [comment]
That's really, good to know. I have been using this structure as a bit of a cheat code if you will to pass `CompiledFunctions` to `CompiledFunctions`. 
Thanks again
Jordan
