### ISSUE TITLE
`AttributeError: module 'diffrax' has no attribute 'NoAdjoint'`

### ISSUE THREAD

**Issue by homerjed** [patrick-kidger/equinox#444]
Hello, 

In the [Score-based Diffusion](https://github.com/patrick-kidger/equinox/blob/main/examples/score_based_diffusion.ipynb) example, the error below is raised

```
AttributeError: module 'diffrax' has no attribute 'NoAdjoint'
```

what should be done to bring it up to date?

Thank you

**Comment by patrick-kidger** [comment]
Ah! Just delete it I think, and use the default adjoint method. I'd be happy to take a PR on this.

**Comment by homerjed** [comment]
Thanks!
