### ISSUE TITLE
Error when model itself is the carry in `jax.lax.scan`

### ISSUE THREAD

**Issue by ForceBru** [patrick-kidger/equinox#446]
## Code

```python
import jax, jax.random as jrnd
import equinox as eqx

key = jrnd.PRNGKey(5)
X = jrnd.normal(key, (20, 3))
y = jrnd.normal(key, (20, 1))

scanner = lambda carry, _: (carry, 5.0)

# 1. This works fine:
model1 = eqx.nn.Linear(X.shape[1], y.shape[1], key=key)
# NOTE: `model1` is the carry!
res1 = jax.lax.scan(eqx.filter_jit(scanner), model1, X)

# 2. This produces an error:
model2 = eqx.nn.MLP(X.shape[1], y.shape[1], 6, 3, key=key)
# NOTE: `model2` is the carry!
res = jax.lax.scan(eqx.filter_jit(scanner), model2, X)
```

### Why this code?

I'm trying to implement the training loop inside `jax.lax.scan`, so the carry is the model updated by optax. The result of `scan` is supposed to be the model from the last epoch and the loss history.

## Error

```
Traceback (most recent call last):
  File "_question.py", line 14, in <module>
    res = jax.lax.scan(eqx.filter_jit(scanner), model2, X)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/lax/control_flow/loops.py", line 254, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
                                                                ^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/lax/control_flow/loops.py", line 239, in _create_jaxpr
    carry_avals = tuple(_map(_abstractify, init_flat))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/lax/control_flow/common.py", line 40, in _abstractify
    return core.raise_to_shaped(core.get_aval(x))
                                ^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/core.py", line 1371, in get_aval
    return concrete_aval(x)
           ^^^^^^^^^^^^^^^^
  File "/Users/forcebru/.pyenv/versions/3.11.4/lib/python3.11/site-packages/jax/_src/core.py", line 1363, in concrete_aval
    raise TypeError(f"Value {repr(x)} with type {type(x)} is not a valid JAX "
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Value <jax._src.custom_derivatives.custom_jvp object at 0x126e2e9d0> with type <class 'jax._src.custom_derivatives.custom_jvp'> is not a valid JAX type

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "_question.py", line 14, in <module>
    res = jax.lax.scan(eqx.filter_jit(scanner), model2, X)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Value <jax._src.custom_derivatives.custom_jvp object at 0x126e2e9d0> with type <class 'jax._src.custom_derivatives.custom_jvp'> is not a valid JAX type
```

I think the problem is that activation functions in `eqx.nn.MLP` are `Callable`: https://github.com/patrick-kidger/equinox/blob/62c8aefd09aaf25ea3ecd17b71ef40694cd6c8e6/equinox/nn/_composed.py#L24-L34

The [documentation](https://docs.kidger.site/equinox/faq/#typeerror-not-a-valid-jax-type) says:

> This error happens because a model, when treated as a PyTree, may have leaves that are not JAX types (such as functions). It only makes sense to trace arrays. Filtering is used to handle this.
>
> Instead of [jax.jit](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html), use [equinox.filter_jit](https://docs.kidger.site/equinox/api/filtering/transformations/#equinox.filter_jit).

However, I'm already passing `eqx.filter_jit(scanner)` to `scan`, but it doesn't help. Perhaps JAX doesn't support functions (the MLP's activations in this case) as part of the carry?

Is there any way around this?

**Comment by ForceBru** [comment]
An obvious fix is to use a Python loop instead of `jax.lax.scan`:

```python
losses = []
for ep in range(epochs):
    (self.model, self.optim_state), loss_val = optim_step((self.model, self.optim_state), ep)
     losses.append(loss_val)
self.history_ = np.array(losses).flatten()
```

...instead of:

```python
(self.model, self.optim_state), losses = jax.lax.scan(
    optim_step, (self.model, self.optim_state), jax.numpy.arange(epochs, dtype=np.uint32)
)
```

But with the Python loop the code that used to run for 2 minutes has now been running for _20 minutes_, even though `optim_step` is jitted.

**Comment by patrick-kidger** [comment]
Right. So what's going on here is that `jax.lax.scan` requires that the carry be a PyTree of JAX arrays. But `model2` isn't a PyTree of JAX arrays!

It's a PyTree, but it includes a non-JAX-array amongst its leaves. (Namely `model2.activation` and `model2.final_activation`.)

The appropriate thing to do is exactly as in Option 1 of https://docs.kidger.site/equinox/all-of-equinox/#2-filtering: by partitioning and combining the JAX arrays can get updated in the scan, and all the non-arrays can be captured via closure. You should be able to write a `filter_scan` operation in this way. I've actually been contemplating adding `filter_scan`, `filter_cond`, `filter_while_loop` etc -- they just don't come up as frequently, so I haven't gotten around to it.

**Comment by ForceBru** [comment]
Ah, seems like I didn't think of `partition`ing and then recombining the model. I got too used to treating `eqx.filter_jit` and friends as "magic that makes stuff work". Thanks!
