### ISSUE TITLE
[Question] Using eqx.nn.Linear like torch.nn.Linear

### ISSUE THREAD

**Issue by Artur-Galstyan** [patrick-kidger/equinox#454]
Hi Patrick,

I'm trying to translate the LLaMA2 model from PyTorch to Equinox, which gave me the following problem:

In PyTorch, when you use `torch.nn.Linear`, PyTorch uses the last dimension as the input features. For instance, see the following code:

```python
from dataclasses import dataclass
from typing import Optional
import jax
import jax.numpy as jnp
import jaxtyping as jt
import numpy as np
import equinox as eqx
import torch 

# this is not so important, but kept here for reproducability
@dataclass
class ModelArgs:
    dim: int = 4096
    n_layers: int = 32
    n_heads: int = 32
    n_kv_heads: Optional[int] = None
    vocab_size: int = -1  # defined later by tokenizer
    multiple_of: int = 256  # make SwiGLU hidden layer size multiple of large power of 2
    ffn_dim_multiplier: Optional[float] = None
    norm_eps: float = 1e-5

    max_batch_size: int = 32
    max_seq_len: int = 128  # 2048
    dropout: float = 0.0

args = ModelArgs()

head_dim = args.dim // args.n_heads
lin = torch.nn.Linear(args.dim, args.n_heads * head_dim, bias=False)
print(lin.weight.shape) # output =  torch.Size([4096, 4096])

x = torch.rand(1, 8, 4096)
print(x.shape) # output = torch.Size([1, 8, 4096])
print(lin(x).shape) # output = torch.Size([1, 8, 4096])
```

That worked perfectly fine. I now want to translate this to Equinox. Here's my attempt:

```python
class Temp(eqx.Module):
    lin: eqx.nn.Linear

    def __init__(self):
        key = jax.random.PRNGKey(32)
        self.lin = eqx.nn.Linear(args.dim, args.n_heads * head_dim, use_bias=False, key=key)
        print(self.lin.weight.shape) # (4096, 4096)
    
    def __call__(self, x):
        return jax.vmap(self.lin)(x) # vmap was a desperate attempt :(


test_x = jnp.ones(shape=(1, 8, 4096))
print(test_x.shape) # (1, 8, 4096)

a = Temp()
a(test_x)
```

If you run this, you will get the following error:
```
TypeError: dot_general requires contracting dimensions to have the same shape, got (4096,) and (8,).
```

I could try to hack this specific vector into some shape to make the code run through, but I'm looking for the right way (or rather the most "Jax-way") to handle this problem. Do you have some ideas?

**Comment by patrick-kidger** [comment]
Vmap twice. Each one peels off a single batch dimension.

**Comment by Artur-Galstyan** [comment]
This did indeed work. Thanks!

I guess for the general case I would need $n-1$ nested `vmap`s, where $n$ is the number of dimensions of the input, i.e.

```python
def dynamic_vmap(f, x, num_vmaps):
    for _ in range(num_vmaps):
        f = jax.vmap(f)
    return f(x)
```
And probably I'd need to use `[fori_loop](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.fori_loop.html#jax.lax.fori_loop)` to optimize this further. 

Thanks for the hint!

**Comment by lockwo** [comment]
It seems similar to something already in the FAQ: https://docs.kidger.site/equinox/faq/#how-do-i-input-higher-order-tensors-eg-with-batch-dimensions-into-my-model

**Comment by Artur-Galstyan** [comment]
Yes, I had seen that segment, but just wasn't aware about the double vmap 😄 I'll try a PR for that FAQ section later; something like: "if you have even more dimensions, consider using multiple vmaps..." something along those lines.

**Comment by mfouesneau** [comment]
Sorry, I'm facing the same error message using `nn.MLP`
```python
model = eqx.nn.MLP(X_train.shape[1], 1, 4, y_train.shape[1], key=key)
model(X_train)
```
X and y are 2d arrays.
