### ISSUE TITLE
`donate` discrepencies between `flter_jit` and `filter_pmap` documentation and implementation

### ISSUE THREAD

**Issue by colehaus** [patrick-kidger/equinox#467]
`filter_jit` has `all`, `warn` and `none` with `none` as the default in the documentation and implementation.
`filter_pmap` has `all`, `warn` and `none` with `all` as the default in the documentation. The implementation actually expects one of `arrays`, `warn` or `none` and has `none` as the default. What's the right resolution here? Switch the `filter_pmap` documentation to `none` as the default and the implementation to use `all` instead of `arrays`?

**Comment by patrick-kidger** [comment]
Whoops!

> Switch the filter_pmap documentation to none as the default and the implementation to use all instead of arrays?

Yes, that's what it should be. I'd be happy to take a quick PR on this. If not I'll fix it myself shortly.

**Comment by colehaus** [comment]
I should be able to make a PR shortly. Thoughts on also changing the types from `string` to `Literal["all", "warn", "none"]`? Would have probably caught the implementation issue here.

**Comment by patrick-kidger** [comment]
Yup, that also sounds best to me.
