### ISSUE TITLE
Traceback for filter_grad

### ISSUE THREAD

**Issue by chrisflesher** [patrick-kidger/equinox#502]
Maybe this is not a problem with equinox and more user error (me)... just wanted to report a traceback message that took a long time to debug.

Here is the minimal code example:

```
import equinox
import jax
import jax.numpy as jnp


class MyModule(equinox.Module):

    values: jax.Array

    def __init__(self, values: jax.Array):
        self.values = values

    @equinox.filter_jit
    def __call__(self, index) -> jax.Array:
        return self.values[index]


@equinox.filter_grad
def my_grad(my_module, index) -> jax.Array:
    values = my_module(index)
    return jnp.sum(values)


my_module = MyModule(values=jnp.zeros((100, 2), dtype=float))
index = jnp.array([1], dtype=int)
updates = my_grad(my_module=my_module, index=index)
```

The traceback was

```
Traceback (most recent call last):
  File "untitled.py", line 28, in <module>
    updates = my_grad(my_module=my_module, index=index)
  File "/home/chris/.local/lib/python3.8/site-packages/equinox/_ad.py", line 72, in __call__
    value, grad = self._fun_value_and_grad(*args, **kwargs)
TypeError: __call__() missing 1 required positional argument: 'x'
```

I couldn't figure out what `x` the traceback was referring to (there is no `x` variable near any of the lines mentioned). Also was getting confused by the `__call__` reference, I thought this was referring to `MyModule.__call__` but found out later it was referring a wrapper class that equinox uses internally.

Finally found the issue was `updates = my_grad(my_module=my_module, index=index)` does not accept keyword arguments like I was expecting. It worked fine after changing to `updates = my_grad(my_module, index)`.

Anyways... was wondering how easy it would be to improve this traceback message? If it's not worth implementing feel free to close this issue.

**Comment by patrick-kidger** [comment]
Thanks for the report! Indeed this isn't super clear -- I've just opened #503 to try and improve the error message.

Actually accepting a keyword argument in that position would be a bit better still, but that involves some fairly complicated signature-binding code, and it's probably better to keep the implementation simple.

Unrelatedly, right now you have `filter_jit` inside the `filter_grad`. Note that it's usually more efficient to swap these two around -- the JIT should almost always be the top-level transform.

**Comment by chrisflesher** [comment]
Ah wow, that was fast. Thanks for the tip on `filter_jit` / `filter_grad`!
