### ISSUE TITLE
Compilation logging shows generic function name for every JIT'ed function for `filter_jit`, `filter_grad`, `filter_value_and_grad`

### ISSUE THREAD

**Issue by marcelroed** [patrick-kidger/equinox#51]
I've recently been debugging long compile times in my neural networks and stumbled upon an XLA compiler flag that can be set using

```python
jax.config.update('jax_log_compiles', True)
```

This setting prints out some messages when each function starts and ends its compilation including the amount of time spent. However, currently, the error message shows a generic function name from within the implementation of `filter_jit`, `filter_grad` and `filter_value_and_grad`, e.g.

```
WARNING:absl:Finished tracing + transforming prim_fun for jit in 0.00043702125549316406 sec
WARNING:absl:Finished tracing + transforming prim_fun for jit in 0.0002541542053222656 sec
WARNING:absl:Compiling prim_fun (4766936320 for args (ShapedArray(float32[]),).
WARNING:absl:Finished XLA compilation of broadcast_in_dim in 0.06613397598266602 sec
WARNING:absl:Finished tracing + transforming f_wrapped for jit in 0.0012121200561523438 sec
WARNING:absl:Compiling f_wrapped (5095206976 for args (ShapedArray(float32[1]),).
WARNING:absl:Finished XLA compilation of f_wrapped in 0.00688481330871582 sec
```

where `f_wrapped` comes from here
https://github.com/patrick-kidger/equinox/blob/3af0cdefd70e7a36850260a34cbc58d52c6a4b59/equinox/jit.py#L17

When looking for the culprit of excessive debugging times, having the names of the functions available is important.

**Comment by patrick-kidger** [comment]
(Let's discuss this over in #52.)
