### ISSUE TITLE
Different behaviour of `filter_value_and_grad` unintuitive for stateful models. 

### ISSUE THREAD

**Issue by hlzl** [patrick-kidger/equinox#512]
Hi Patrick,

just curious why `filter_value_and_grad` returns a nested tuple with `aux` at the second position of the first tuple, while `filter_grad` and `filter_vjp` both simply return the aux at the last position of the output tuple if `has_aux=True`.

IMO it would be more intuitive to continue that pattern and also return `aux` as the third element of the return tuple for `filter_value_grad` if `has_aux=True`.

Thank you!

**Comment by patrick-kidger** [comment]
Yup, this is a bit weird! However, we're just following what JAX does here. The `filter_*` transforms are generally intended to be drop-in replacements for these.

**Comment by hlzl** [comment]
Ah, that makes sense, thank you!
