### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/equinox#525]
In the UNet implementation (https://docs.kidger.site/equinox/examples/unet/) the link for score based diffusion goes to https://docs.kidger.site/equinox/examples/unet/score_based_diffusion/ which is a 404, I believe it should go to https://docs.kidger.site/equinox/examples/score_based_diffusion/

**Comment by patrick-kidger** [comment]
Thanks for the report! This should be fixed in #531.
