### ISSUE TITLE
BUG: tests fail with `jaxtyping` 0.2.23

### ISSUE THREAD

**Issue by GaetanLepage** [patrick-kidger/equinox#551]
The following tests fail with `jaxtyping` 0.2.23;
```
FAILED tests/test_nn.py::test_layer_norm - beartype.roar.BeartypeCallHintParamViolation: Function jaxtyping._decorator...
FAILED tests/test_while_loop.py::test_nested_loops[False] - beartype.roar.BeartypeCallHintForwardRefException: Forward reference "jaxty...
FAILED tests/test_while_loop.py::test_nested_loops[True] - beartype.roar.BeartypeCallHintForwardRefException: Forward reference "jaxty...
```

**Comment by GaetanLepage** [comment]
The one in `test_nn.py` is an easy one.
Change this type annotation from `tuple[int]` to `tuple[int, ...]`.
https://github.com/patrick-kidger/equinox/blob/c31b4c2f6e11af1205cfb63ce282ce540a28f50c/equinox/nn/_normalisation.py#L53

However, for the failure of `test_while_loop.py::test_nested_loops`, I have no idea...

**Comment by patrick-kidger** [comment]
Thanks for the report! I'm guessing you're running the Equinox tests from v0.11.0.
I think these errors should already be fixed on the Equinox `main` branch.

**Comment by GaetanLepage** [comment]
Indeed, it works great on `master`. 
Do you think about making a release to ship those fixes ? (v0.11.1 for instance)

**Comment by patrick-kidger** [comment]
Yes, there will be a release in the near future.

**Comment by GaetanLepage** [comment]
Thank you very much !
I am closing this issue then :)
