### ISSUE TITLE
scan not working with module methods

### ISSUE THREAD

**Issue by PistaSaki** [patrick-kidger/equinox#558]
When I use an equinox `Module` method as the recurrent function in `scan`, it throws an error. It used to work in version 0.10.11 without any problems but fails in 0.11.0 and 0.11.1. Here is a minimal code:
``` python
import equinox as eqx
from jax import Array, lax, numpy as jnp


class RecurrentCell(eqx.Module):
    w: Array

    def update(self, state, input) -> tuple[Array, Array]:
        return state, input * self.w


start_state = jnp.array([0.0])
inputs = jnp.array([1.0, 2.0, 3.0])
cell = RecurrentCell(w=jnp.array(2.0))
states, outputs = lax.scan(cell.update, start_state, inputs)
print(outputs)
```
An error it throws:
```
Traceback (most recent call last):
  File "D:\tmp\bordel.py", line 15, in <module>
    states, outputs = lax.scan(cell.update, start_state, inputs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tmp\venv_new\Lib\site-packages\jax\_src\traceback_util.py", line 177, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\tmp\venv_new\Lib\site-packages\jax\_src\lax\control_flow\loops.py", line 253, in scan
    init_flat, carry_avals, carry_avals_out, init_tree, *rest = _create_jaxpr(init)
                                                                ^^^^^^^^^^^^^^^^^^^
  File "D:\tmp\venv_new\Lib\site-packages\jax\_src\lax\control_flow\loops.py", line 239, in _create_jaxpr
    jaxpr, consts, out_tree = _initial_style_jaxpr(
                              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\tmp\venv_new\Lib\site-packages\equinox\_module.py", line 839, in __hash__
    return hash(tuple(jtu.tree_leaves(self)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'ArrayImpl'
```
Further info: I'm on Windows 10, using Python 3.11.3 with Jax 0.4.18.

**Comment by patrick-kidger** [comment]
Ah, this looks like an instance of this JAX bug: https://github.com/google/jax/issues/13554.

This is arising in v0.11.0 due to change #485, which was to fix #480. In this case I think Equinox is now doing the correct thing here, and it's just unfortunate that this is trigger this JAX bug. :/

It should be possible to work around this fairly simply: replace `lax.scan(cell.update, ...)` with `lax.scan(lambda *a, **kw: cell.update(*a, **kw), ...)`, i.e. wrap things in a trivial lambda function.

**Comment by getfilthyrich** [comment]
Thank you for the quick answer! That solves it. :)
And thank you for the great library!

**Comment by pablo2909** [comment]
Only to document the issue, since it does not seem there is anything to fix in this library, it also happens with `lax.cond(cond, equinox_module_1, equinox_module_2, x)` and wrapping it with a `lambda` function fixes it.

**Comment by xaviergonzalez** [comment]
Can anyone give a good conceptual explanation of why it's a good design decision by jax for the following two approaches to behave differently?

```
import jax
import equinox as eqx
import jax.random as jr
import jax.numpy as jnp
class RNN(eqx.Module):
  W: jax.Array
  def __init__(self, D):
    self.W = jr.normal(jr.PRNGKey(0), shape=(D,))
  def step(self, c, a):
    out = jnp.tanh(self.W @ c + a)
    return out, out
rnn = RNN(10)
```

Option A:

`jax.lax.scan(rnn.step, jnp.zeros(10), jnp.ones((10, 10)))` leads to `TypeError: unhashable type: 'jaxlib.xla_extension.ArrayImpl'`

Option B:

`jax.lax.scan(lambda c, a: rnn.step(c,a), jnp.zeros(10), jnp.ones((10, 10)))` works fine.

If I'm understanding correctly, in Option A, jax is hashing both the method `rnn.step` and the equinox module `rnn`, which has a jax array as an attribute. So, it makes sense to me why this fails.

But I don't understand why it's a consistent design choice for Option B. to work fine (though I'm certainly glad that it does!).

**Comment by patrick-kidger** [comment]
In this case it's doing a simple `hash(fn)`, and lambdas are hashable so this works.

I actually agree with you that this seems like a suboptimal approach for JAX to take -- ideally it would closure-convert into a pure function if it wanted to do something like this.
