### ISSUE TITLE
Better support for broadcasting in linear layer

### ISSUE THREAD

**Issue by jaschau** [patrick-kidger/equinox#56]
In equinox's implementation, for a weight matrix `w` of shape `(d_out, d_in)`, the computational rule for the linear layer update is (https://github.com/patrick-kidger/equinox/blob/main/equinox/nn/linear.py#L65)
```
y = w x + b
```
This is problematic if `x` is a higher-dimensional tensor with shape `(d_in, d_1, ..., d_n)`. 
The outcome of w x is a tensor of shape `(d_out, d_1, ..., d_n)`, while `b` is a tensor of shape `(d_out,)`.
Since numpy's broadcasting rule works from right-to-left (https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules), broadcasting the two won't work.

Example:

```
import equinox as eqx
import equinox.experimental as eqxe
import jax
import jax.nn as jnn
import jax.numpy as jnp
import jax.random as jrandom
seed = 0

key = jrandom.PRNGKey(seed)
key, key_linear, key_input = jrandom.split(key, 3)
#print("key=", key)
d_in = 3
d_out = 4
x = jrandom.normal(key_input, shape=(d_in, 5))
linear = eqx.nn.Linear(d_in, d_out, use_bias=True, key=key_linear)
# fails with ValueError due to impossibility of broadcasting
res = linear(x)
```
To remedy this, I would propose to change the implementation to PyTorch style (https://pytorch.org/docs/stable/generated/torch.nn.functional.linear.html). This would allow arbitrary left-most dimensions.
If we could add a reshape to make it work with tensors with arbitrary number of trailing dimensions, that would be even better :)

**Comment by patrick-kidger** [comment]
So this is actually a deliberate choice to keep Equinox's API simple and consistent.

If you need to handle additional dimensions, then this can be done: just use `jax.vmap`, as per `jax.vmap(linear)(x)` or `jax.vmap(linear, in_axes=(1,), out_axes=(1,))(x)`, etc.

**Comment by jaschau** [comment]
Hi @patrick-kidger, thanks for the clarification. I have created a small PR adding the above explanation to the documentation to avoid confusion for future users.

**Comment by patrick-kidger** [comment]
Great, thanks for the contribution! I really appreciate it.
