### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'typing'

### ISSUE THREAD

**Issue by TomClarkMassSpec** [patrick-kidger/equinox#567]
Hi,

Just created new environment so I can access functionality of Optimistix which has jax and Equinox dependencies. Trying to incorporate equinox into my previous code. When I add import equinox as eqx to:

```
import jax.numpy as jnp
import pandas as pd
import numpy as np_reg
#from typing import Tuple
from jax import lax
from jax import jit, grad, vmap
import matplotlib.pyplot as plt
from jaxopt import Bisection
import equinox as eqx

```
 I get: AttributeError: module 'jax' has no attribute 'typing' .

jax/jaxlib 4.19, Equinox 11.1, python 3.10.2

Perhaps this will go away if I make the leap by finish writing my first Equinox.modules and delete my old class definitions and remove typing import.

**Comment by TomClarkMassSpec** [comment]
Additional details:Traceback (most recent call last):

  Cell In[7], line 10
    import equinox as eqx

  File /opt/anaconda3/lib/python3.8/site-packages/equinox/__init__.py:3
    from . import internal as internal, nn as nn

  File /opt/anaconda3/lib/python3.8/site-packages/equinox/internal/__init__.py:5
    from .._compile_utils import (

  File /opt/anaconda3/lib/python3.8/site-packages/equinox/_compile_utils.py:7
    from jaxtyping import PyTree

  File /opt/anaconda3/lib/python3.8/site-packages/jaxtyping/__init__.py:33
    from .array_types import (

  File /opt/anaconda3/lib/python3.8/site-packages/jaxtyping/array_types.py:667
    ScalarLike = Shaped[jax.typing.ArrayLike, ""]

AttributeError: module 'jax' has no attribute 'typing'

**Comment by patrick-kidger** [comment]
Hmm, I'm afraid I can't replicate this. Just importing everything in your MWE seems to work without errors.

Double check your JAX version. If you're an older version then the `jax.typing` module may not exist.

**Comment by TomClarkMassSpec** [comment]
Thanks for taking time to look. I will reinstall.
