### ISSUE TITLE
Simple example for differentiating loss with basic MLP?

### ISSUE THREAD

**Issue by cottrell** [patrick-kidger/equinox#570]
I'm not sure if there is a simple example for working with these. Maybe it's an obvious filter spec? I might have missed an example as the ipynb are more tricky to search.

```python
import jax.numpy as jnp
import numpy as np
import equinox as eqx
import jax


def example():
    key = jax.random.PRNGKey(seed=0)
    model = eqx.nn.MLP(2, 1, 4, 3, key=key)
    X = np.random.randn(100, 2).astype(np.float32)
    y = np.random.randn(100, 1).astype(np.float32)

    def nll(model, X, y):
        yp = jax.vmap(model)(X)
        mse = jnp.mean((y - yp) ** 2)
        return mse

    yp = jax.vmap(model)(X)

    loss = nll(model, X, y)
    loss = jax.jit(nll)(model, X, y)  # FAILS
    # TypeError: Cannot interpret value of type <class 'jax._src.custom_derivatives.custom_jvp'> as an abstract array; it does not have a dtype attribute
```

error

```
TypeError: Cannot interpret value of type <class 'jax._src.custom_derivatives.custom_jvp'> as an abstract array; it does not have a dtype attribute
> /home/cottrell/projects/notebooks/my-gym/my/gym/usr/cottrell/equinox_mlp.py(22)example()
     20 
     21     loss = nll(model, X, y)
---> 22     loss = jax.jit(nll)(model, X, y)  # FAILS
     23     # TypeError: Cannot interpret value of type <class 'jax._src.custom_derivatives.custom_jvp'> as an abstract array; it does not have a dtype attribute
     24 

   8 frames hidden (try 'help hidden_frames')
```

**Comment by patrick-kidger** [comment]
You probably want to use `eqx.filter_jit` instead of `jax.jit`. See [the intro documentation](https://docs.kidger.site/equinox/all-of-equinox/#2-filtering). It's useful to have a mental model for what an Equinox model is (a PyTree), and whether or not that PyTree contains any non-arrays. (Which is basically what determines when `eqx.filter_foo` is necessary over `jax.foo`. Just always using the Equinox version is a reasonable thing to do though, to skip this concern.)

Incidentally, you mention differentiation in the title but it doesn't appear in the MWE. For that you will probably want `eqx.filter_grad`.

**Comment by cottrell** [comment]
> You probably want to use `eqx.filter_jit` instead of `jax.jit`. See [the intro documentation](https://docs.kidger.site/equinox/all-of-equinox/#2-filtering). It's useful to have a mental model for what an Equinox model is (a PyTree), and whether or not that PyTree contains any non-arrays. (Which is basically what determines when `eqx.filter_foo` is necessary over `jax.foo`. Just always using the Equinox version is a reasonable thing to do though, to skip this concern.)
> 
> Incidentally, you mention differentiation in the title but it doesn't appear in the MWE. For that you will probably want `eqx.filter_grad`.

Yes, I think you mean "never to be differentiated" things in the pytree? And I guess, I am not clear on why a generic like MLP is not using `eqx.static_field` to denote these? Else the user needs to know the structure of the internal state in order to jit and grad them? Or am I missing something in my understanding?

**Comment by patrick-kidger** [comment]
> Reading a bit more into the MLP implmentation ... I suspect (guessing), that maybe the activations in the MLP could be eqx.Modules themselves and that might make some of this a little simpler? I think then they could either have differentiable structure or not.

Yup, that's correct. This is the reason that the activations aren't set as `field(static=True)`, so that if a learnt activation is used, then it will pick up gradients.
