### ISSUE TITLE
Wrapping module methods

### ISSUE THREAD

**Issue by danielward27** [patrick-kidger/equinox#575]
Apologies, this is more of a pattern question rather than an issue. I want a way to enforce shape checking within methods of an equinox module. I see three possibilities:

1) Use a metaclass, something like

```python


import functools
import inspect
from abc import abstractmethod

import equinox as eqx
import jax.numpy as jnp
from jax import Array


class _AbstractClassMeta(type(eqx.Module)):
    def __new__(
        mcs,
        name,
        bases,
        dict_,
        /,
        strict: bool = False,
        abstract: bool = False,
        **kwargs,
    ):
        if AbstractClass in bases and not inspect.isabstract(mcs):
            dict_["my_method"] = check_shape(dict_["my_method"])
        return super().__new__(mcs, name, bases, dict_, strict, abstract, **kwargs)


def check_shape(method):
    def wrapper(self, a):
        assert a.shape == self.shape
        print("shape checking succeeded.")
        return method(self, a)

    return wrapper


class AbstractClass(eqx.Module, metaclass=_AbstractClassMeta):
    shape: tuple = (5,)

    @abstractmethod
    def my_method(self, a: Array):
        pass


class ConcreteClass(AbstractClass):
    def my_method(self, a):
        print(f"Concrete method called with {a}.")


ConcreteClass().my_method(jnp.arange(5))
```
2) Define a decorator and manually decorate all the methods on the concrete implementations. Quite clear, but a pain and perhaps easy to forget and hence error prone.
3) Prepend an underscore to the abstract method `_my_method`, and then define a wrapped method on the abstract class `my_method` that includes shape checking. Again quite clear and simple, but introduces slightly annoying underscores and extra methods.

I was wondering what approach you would recommend out of these (or others)?

**Comment by patrick-kidger** [comment]
For shape-checking I would recommend using [jaxtyping](https://github.com/google/jaxtyping).

**Comment by danielward27** [comment]
Thanks. https://github.com/google/jaxtyping/issues/93 seems to be a corresponding issue, so feel free to close this

**Comment by patrick-kidger** [comment]
Great, will do.

And I'm happy to say that the jaxtyping issue you link will soon be closed. https://github.com/google/jaxtyping/pull/140 implements that feature.
