### ISSUE TITLE
Warning when using both __init__ and __post_init__

### ISSUE THREAD

**Issue by mthiboust** [patrick-kidger/equinox#585]
[You recently added](https://github.com/patrick-kidger/equinox/pull/514) a warning if `__init__()` and `__post_init__()` are both used in a Module. However, I think the following code is ok even if it triggers such a warning. Am I missing something or can I safely filter out this specific warning in my case?

**My use case:** in some context, I would like to simplify the initialization API of a Module which takes many arguments. For instance, in the following toy example, I would like to be able to init my module with only `MyParticularModule(1)` instead of `MyVeryGenericModule(1, 1, 1)` 

```python
import equinox as eqx

class MyVeryGenericModule(eqx.Module):
    a1: int
    a2: int
    a3: int
    b: int = eqx.field(init=False)

    def __post_init__(self):
        self.b = self.a1 + self.a2 + self.a3

class MyParticularModule(eqx.Module):
    def __init__(self, a):
        super().__init__(a, a, a)

MyVeryGenericModule(1, 1, 1) # MyVeryGenericModule(a1=1, a2=1, a3=1, b=3)
MyParticularModule(1)        # MyParticularModule(a1=1, a2=1, a3=1, b=3))
```

This code generates this warning:
```
UserWarning: Class `__main__.Child` has both an `__init__` method and a `__post_init__` method. This means that the `__post_init__` method will not be run!
The reason for this is that `__post_init__` is intended to be used with the automatically-generated `__init__` method provided by Python dataclasses, which are generated of the form:

def __init__(self, field1, field2)
    self.field1 = field1
    self.field2 = field2
    self.__post_init__()

and as such a user-provided `__init__` overrides both the setting of fields, and the calling of `__post_init__`.
The above is how Python dataclasses work, and has nothing to do with Equinox!
If you are using `__post_init__` to check that certain invariants hold, then consider using `__check_init__` instead. This is an Equinox-specific extension that is always ran. See here for more details: https://docs.kidger.site/equinox/api/module/advanced_fields/#checking-invariants
```

### Related comment

[In your documentation](https://docs.kidger.site/equinox/api/module/advanced_fields/#checking-invariants), you explain why you added the `__check_init__()` method by mentioning a silent bug if not used. But the example could also have been corrected by simply adding `super().__init__(x)` inside the Child `__init__()` method, right?

```python
class Parent(eqx.Module):
    x: int

    def __post_init__(self):
        if self.x <= 0:
            raise ValueError("Oh no!")

class Child(Parent):
    x_as_str: str

    def __init__(self, x):
        super().__init__(x) # Added line
        self.x = x
        self.x_as_str = str(x)

Child(-1)  # ValueError: Oh no!
```

**Comment by patrick-kidger** [comment]
Both of the examples you've written are functionally correct (due to the use of `super()`), yup!

That said, I would still advocate against this approach, as I think it's a code smell. In this particular case it's not obvious to an outside observer whether the original developer was aware that `__post_init__` won't be called directly from the subclass -- so this code is harder to reason about. More broadly, type hierarchies which call the parent's version of the same method (in this case `__init__`), often produce code that is hard to reason about or is prone to bugs.

It's not publicly-advertised documentation right now (as I haven't extensively tested the `strict=True` flag it mentions yet), but you might like this [abstract/final design pattern](https://docs.kidger.site/equinox/pattern/) guide.

**Comment by mthiboust** [comment]
Thanks Patrick for your answer!

Your abstract/final design pattern is interesting. I'll think more about it to see if I can apply it in my use case. At first, I'm afraid it would mean a lot of redundancy because the child classes would all repeat the many same attributes (attributes that may change in the future and cause new breaking-change versions for child classes defined by the library users). I'll also reconsider doing class factories instead.

**Comment by mthiboust** [comment]
I found a cleaner workaround by refactoring my code. Thanks again for the advice
