### ISSUE TITLE
[Feature Request] filter_jacfwd, filter_jacrev

### ISSUE THREAD

**Issue by smorad** [patrick-kidger/equinox#603]
Equinox's `filter_*` functions are very helpful functions. It would be great if there were`filter_jacfwd` and `filter_jacrev` functions. 

For my specific use case, I am using `eqx.filter_value_and_grad(fn)(model, ...)`. As far as I can tell, If I wanted to compute the Jacobian of `fn` with respect to the inputs, I would need to rewrite `fn` with the type signature `fn(model_static, model_params, ...)`. This means I won't be able to use `eqx.filter_value_and_grad` or really any other `eqx.filter_*` on fn. Furthermore any calls to `eqx.filter_*` inside of `fn` must also be rewritten as `jax.*`!

**Comment by patrick-kidger** [comment]
I'd definitely be happy to add them. I actually have a draft of them [here](https://github.com/patrick-kidger/equinox/pull/372) -- I think the only thing that needs doing is to remove the `filter_dce` function this PR also adds, as I think that's something that ended up without a clear use-case.

Would you be comfortable making a copy of that PR without `filter_dce`? If so then I'd be happy to merge it.

**Comment by chrisflesher** [comment]
I tried using the `jacfwd` function from that draft PR. But am getting `nan`'s in the solution. Whereas `equinox.grad` applied to the same function doesn't contain any `nan`s... I don't have a distilled example... was wondering if there might be any possible differences between `equinox.grad` and the proposed `equinox.jacfwd` that might be causing this?

**Comment by patrick-kidger** [comment]
It could be a difference between forward and reverse mode autodifferentiation, perhaps?

**Comment by lockwo** [comment]
Revived PR for this: https://github.com/patrick-kidger/equinox/pull/674

**Comment by lockwo** [comment]
This should now be complete with the latest version https://github.com/patrick-kidger/equinox/releases/tag/v0.11.4
