### ISSUE TITLE
How to deal with intermediate results?

### ISSUE THREAD

**Issue by nasyxx** [patrick-kidger/equinox#620]
In flax, we can use `self.sow('intermediates', 'features', x)` https://flax.readthedocs.io/en/latest/guides/model_inspection/extracting_intermediates.html.

But in equinox, I'm not quite sure how to handle this. Should I store it in the states?

**Comment by patrick-kidger** [comment]
Can you just return the intermediate values as normal outputs?

**Comment by nasyxx** [comment]
> Can you just return the intermediate values as normal outputs?

Yes, but it is very troublesome to modify, because intermediate values may be in `model.block[-1].inner_model.inner_model`. If return is needed, I must modify each layer's return.

Perhaps returning a `dict[str, Array]` for each layer would require less modification, but I am unsure if this is a good idea.

**Comment by patrick-kidger** [comment]
> I must modify each layer's return.

In Equinox, this is a feature, not a bug :) Having each layer explicitly specify what it returns -- and not have any extra information escape as "side effects" -- is a big part of how Equinox maintains direct compatibility with JAX transforms, and part of its philosophy about keeping the code readable/maintainable.

> Perhaps returning a `dict[str, Array]` for each layer would require less modification, but I am unsure if this is a good idea.

I think this sounds like a reasonable approach, if you're looking for a simple way to return extra information without modifying call signatures.

**Comment by nasyxx** [comment]
Thank you! 

I still have a question. If I put the intermediates in the state, what is the difference between it and returning it directly? Will putting values in state affect the calculation of grad?

Since my model is already stateful, it is currently much simpler for me to put the values into the state than to modify the return.

**Comment by patrick-kidger** [comment]
If you're only returning them -- and not using them as an input to the model -- then I'd probably suggest not putting them in the state. That's just to follow conventions a little more closely by using states only for stateful values. But that's not a strong feeling.

This won't affect the gradient either way though. You'll get gradients with respect to whatever you explicitly ask to be differentiated; nothing more or less.

**Comment by nasyxx** [comment]
Thanks!  Thank you for your guidance.  I understand now. Equinox is even better than I thought. 

After transitioning from PyTorch to JAX this year spring, I have explored three different frameworks: Haiku, Flax, and Equinox. Among these, Flax appears to diverge most from the core JAX experience. In contrast, the all-PyTree approach employed by Equinox is particularly enlightening.
