### ISSUE TITLE
Could arrays be specified as buffers as field metadata?

### ISSUE THREAD

**Issue by mjo22** [patrick-kidger/equinox#621]
Hello! I have some arrays in my project that should always be marked as buffers (as in jax.lax.stop_gradients). I think the way that equinox ties metadata to dataclass.field is pretty elegant (as in converter and static). Would it be possible to add a “buffer” option in field, that always makes sure jax.lax.stop_gradients is called? I think this would be really nice.

**Comment by patrick-kidger** [comment]
It should be possible to get equivalent behaviour using the existing feature set. Here are two ways that aren't too magic:

**Option 1: wrap the array into a `Buffer` class**

```python
class Buffer(eqx.Module):
    _array: Array

    def get(self):
        return lax.stop_gradient(self._array)

class FooModule(eqx.Module):
    some_buffer: Buffer

    def __init__(self):
        self.some_buffer = Buffer(some_array)

    def ___call__(self, x):
        return x * self.some_buffer.get()
```
This is probably simplest!

**Option 2: override `__getattribute__`**

Class MjoModule(eqx.Module):
    def __getattribute__(self, item):
        value = super().__getattribute__(item)
        for field in dataclasses.fields(value):
            if field.name == item:
                if "buffer" in field.metadata:
                    value = lax.stop_gradient(value)
                break
        return value

class FooModule(MjoModule):
        buffer: Array = eqx.field(metadata={"buffer": True})

        def __call__(self, x):
            return x * self.buffer
```
This gives you the behaviour you asked for.

---

I can see that you're asking for this as a feature request for Equinox itself. So far I've resisted adding this in, mostly to (a) avoid adding "silently magic" behaviour to `eqx.Module`, and (b) to avoid privileging `jax.grad` over any other JAX transform.

That said, those aren't strong feelings. I can definitely see the value in adding this to Equinox itself.

**Comment by mjo22** [comment]
Great! Thanks so much. Overwriting `__getattribute__` is a good option for me. As for the feature request, whatever you think is best. This makes sense.

**Comment by mjo22** [comment]
Would like to reopen this… at least for me, this feature would be really nice. I don’t want my `Module`s to diverge from `equinox`, so if this is of general interest that would be awesome!

**Comment by patrick-kidger** [comment]
I definitely see the value in adding this as a feature.

One question I do have is why you think it's better to have
```python
class Foo(eqx.Module):
    x: Array = eqx.field(buffer=True)
```

**Comment by mjo22** [comment]
This is the true, in this case I agree with this. The issue I’m running into is that I want to access `self.bar` many times. I currently have a Module that stores coordinate system buffers, and this Module is then a field of some OtherModule. This OtherModule may access the buffers multiple times, and it is an abstract base class and may also do so in different ways depending on the subclass of OtherModule. Users of the repo have the ability to create a subclass, and I don’t want them to have to worry about these details.

My current solution is to offload buffers to particular Modules and create a base class where all fields have stop_gradient run in `__getattr__`. This isn’t so bad. But it would be nice to have more flexibility than this.

**Comment by patrick-kidger** [comment]
Can you give a quick MWE drafting what you're describing, with `Module` and `OtherModule`?

**Comment by mjo22** [comment]
Sure. This roughly outlines my current situation and solution:

```python

class BufferModule(eqx.Module):

   b1: Array
   b2: Array

    def __getattr__(self, name):
        value = getattr(self, name)
        if isinstance(value, Array):
            return jax.lax.stop_gradients(value)
        else:
            return value

class AbstractModule(eqx.Module):

    buffers: BufferModule

    @abstractmethod
    def __call__(self, arr):
        # Do something with b1 and b2

class AnotherModule(eqx.Module):

    module: AbstractModule  # subclass of AbstractModule
    arr: Array

    def __call__(self, another_arr):
        result = module(self.arr)
        # Do something else with b1 and b2
        # and another_arr
```

Here, AbstractModule is something that either the user or developers with little equinox / jax experience may subclass. AnotherModule takes a subclass as AbstractModule as an argument, and also may access the buffers.

The reason I would like the field metadata is that in general, I don’t want to have to move all of the buffers to a single class. In general, AbstractModule could have a buffer in it accessed by AnotherModule, or BufferModule could have non-buffers.

**Comment by patrick-kidger** [comment]
Okay! In this case I'd probably suggest the following pattern:
```python
class Foo(eqx.Module):
     _array: Array

    @property
    def array(self):
        return jax.lax.stop_gradient(array)

    def __call__(self, x):
        # do something with `self.array`
```
which I think should be un-footgun-able by new users, whilst also explicitly declaring the `stop_gradient`.

(I'm not really against the idea of `field(buffer=True)`, but I'm not a huge fan of how it secretly sneaks in special behaviour, which I think Equinox otherwise does a fairly good job of avoiding. So I am trying to see if there's a better way to accomplish any particular goal.)

**Comment by mjo22** [comment]
Okay, this makes sense to me. I like this. It’s taken a bit to get used to the idea of wrapping arrays like this.
