### ISSUE TITLE
Observer patterns in JAX

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/equinox#64]
Hello,

First, thank you for providing Equinox, it is very informative and there is a lot to learn from it ! :)

Second, I come from the PyTorch ecosystem where I implemented the observer pattern in a very light framework for my research, like FastAI of PyTorch Lightning. For the past weeks I have been learning JAX/Flax and wanted to do the same, this turns out harder as we are constrained to functional programming, hence no state. 
However, I came across Equinox and one of your experimental feature, that is stateful operation. Knowing this, do you think it is possible to implements callbacks for JAX and if yes what is your opinion on this ? 

Apologies if my issue does not fit here or if the answer to it is obvious.

Thank you very much

**Comment by patrick-kidger** [comment]
Depends what you're trying to do, really. If you want to implement callbacks that e.g. save results, print something, etc. then `jax.experimental.host_callback.{id_tap, id_print, call}` are probably what you want. (This is actually what Equinoxs' stateful operations themselves are built on top of.)

Other than that, the typical pattern in JAX is usually something like:

```python

@jax.jit
def make_step(...):
    ...
    return ...  # return any extra data you want to log/etc. here

for step in range(num_training_steps):
    ... = make_step(...)
    # do any non-JAX operations (logging etc.) here
```
in which any extra such operations happen outside the JIT'd region. (Which should make sense -- JIT is about optimising numerical computations. It has nothing to do with any side-effects, logging, etc.)

**Comment by pablo2909** [comment]
I understand, I did not know about `host_callback`, thank you for pointing it out ! :) 

I had more in mind something like:

```python
class Callback1:
    def train_step():
        # Do some numerical computation in training
    ...

class Callback2:
    def train_step():
        # Do some other numerical computations in training
        # that can be associated with the previous callback
    ...


class Runner:
    list_callbacks: list

    def fit(self, train_config):
        self("train_step") # Call in order all the train_step of the callbacks
    
    def __call__(self, cb_name, train_state):
        for cb in self.list_callbacks:
            cb(cb_name)
```

And ideally we could JIT at once all the `make_step` and they would all have access to a certain external state that `Runner` holds. 
This is actually the core idea of the Fastai library, and I wondered if we could do something similar in Jax. 

Thanks again for your input, I have been struggling quite a bit to draft something that could work. :)

**Comment by patrick-kidger** [comment]
This kind of thing should be doable in normal JAX. As a first simple implementation without any bells and whistles:

```python
def make_step1(..., external_state):
   ...  # do stuff
    return ..., new_state

def make_step2(..., external_state):
    ...  # do stuff
    return ..., new_state

@functools.partial(jax.jit, static_argnums=0)
def runner(list_callbacks, initial_state):
    state = initial_state
    for callback in list_callbacks:
        ..., state = callback(..., state)
```
(Or indeed many other variations on this theme.)

The key ideas are that (a) any external state be an explicit input to any function, and (b) if you want to change that state, then the mutated version of that state should be returned from the function.

**Comment by pablo2909** [comment]
Thank you very much for your input ! :)
