### ISSUE TITLE
Port Pytorch model checkpoint to Equinox

### ISSUE THREAD

**Issue by faresobeid** [patrick-kidger/equinox#642]
I was wondering whats the best way to convert a PyTorch model checkpoint (a .pth file) to equinox to be able to use to finetune for example? I couldn't find any implementations of this so far.

**Comment by lockwo** [comment]
You might find eqxvision utilities useful in this regard: https://github.com/paganpasta/eqxvision/blob/main/eqxvision/utils.py#L120

**Comment by faresobeid** [comment]
Thank you thats exactly what I was looking for! I'll try that out now and see how it goes.
