### ISSUE TITLE
Permission for Use

### ISSUE THREAD

**Issue by Impure-King** [patrick-kidger/equinox#643]
Hey, Patrick! I have been following Equinox for the past year or so and it has helped me understand so much about PyTrees and JAX. I have been trying to implement my own library (with a similar goal as Equinox has) for an high school project and I have gotten my own Module system running. However, I find lifted transformations like ``filter_jit`` and ``filter_grad`` have been really difficult to implement for me. Is it fine, if I temporarily make your filtered transformations part of my API, until I figure out how to create them myself? Since both of our libraries are just PyTrees, it has been really nice to use your transformations to verify my results. I will be adding some new PyTree optimizers + layers and will definitely let you know if I plan to make my library public.

**Comment by Impure-King** [comment]
Also, I feel like it would be a great idea to add a short article in the docs explaining how the filtered_transformations and PyTrees work internally. It would really help new JAX users to understand why Equinox and PyTree-based libraries offer so much flexibility (it took me a while to understand haha). Nevertheless, the existence of Equinox is great, due to it's relatively little magic.

**Comment by lockwo** [comment]
Equinox is licensed under the Apache-2 license, which (like other permissive OSS licenses) allows you to take the code and (largely) do what you want with it. Specifically "The Apache License 2.0 outlines what users are allowed to do with the licensed code. Under this license, users can:

Use the code commercially: Companies can include the licensed code in proprietary software that they then sell to customers.
Alter the code: Developers are permitted to make modifications to the original code.
Distribute any copies or modifications of the code: An individual or organization is allowed to copy and/or update the code, then make that version available to others (even commercially).
Sublicense the code: A company can distribute their reworked version of the code under a stronger license.
Use patent claims: Under the terms of the Apache License 2.0, contributors to the code explicitly grant patent rights to users (although experts believe that the language of other permissive licenses also [grants such rights](https://opensource.com/article/18/2/how-make-sense-apache-2-patent-license?ref=fossa.com)).
Place warranty: Users of the open source code can place a warranty on the licensed software.
And while there are no restrictions on the code, there are a few caveats to keep in mind. For example, the license states that users cannot hold contributor(s) legally liable for any reason. Also, the license does not grant you any rights to use the trademarks of the licensor.
"

Quote from: https://fossa.com/blog/open-source-licenses-101-apache-license-2-0/

You can read the license here: https://github.com/patrick-kidger/equinox/blob/main/LICENSE.

Additionally, GitHub has helpful little toolbars on it: <img width="1343" alt="Screenshot 2024-01-20 at 5 05 23 PM" src="https://github.com/patrick-kidger/equinox/assets/42878312/141ba119-e66c-4b0a-8a4a-54321f46db69">

All in all, even though this is not my code or my repository, I can say, yes, you are free to redistribute the code. Although if this is a school project, you may be required by them to give attribution. Additionally, I agree, filtering is a key part of the library and more documentation on it would in my opinion be good.

**Comment by Impure-King** [comment]
Thanks for the info. Sorry, I am new to licensing of repositories, so that's why I wanted to make sure. I will be citing Equinox as well.

**Comment by patrick-kidger** [comment]
Thank you @lockwo, this is a marvelous explanation. (And definitely better than I could have done.)

Indeed, just to confirm, please feel free to do anything you like with it.

For the documentation on filtered transformations: I'm probably a little too familiar to see what might be missing -- so I'd be happy to consider PRs making improvements. :)
