### ISSUE TITLE
weird interaction between equinox and Chex

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/equinox#645]
hello,

I am observing a behaviour I can't explain when using `chex.assert_max_traces` and `eqx.filter_jit`:

The following works as expected
```python
import chex
import equinox as eqx
import jax


@jax.jit
@chex.assert_max_traces(1)
def f(x, i):
    print("COMPILE")
    return x * 2


for i in range(10):
    print(f(2.0 * i, i))
```
and returns

```bash
COMPILE
0.0
4.0
8.0
12.0
16.0
20.0
24.0
28.0
32.0
36.0
```

But if we use `@eqx.filter_jit` instead as such: 

```python
import chex
import equinox as eqx
import jax


@eqx.filter_jit
@chex.assert_max_traces(1)
def f(x, i):
    print("COMPILE")
    return x * 2


for i in range(10):
    print(f(2.0 * i, i))
```

here is what we get:

```bash
COMPILE
0.0
COMPILE
4.0
COMPILE
8.0
COMPILE
12.0
COMPILE
16.0
COMPILE
20.0
COMPILE
24.0
COMPILE
28.0
COMPILE
32.0
COMPILE
36.0
```

So: 
- it compiles every time
- It does not throw an error for recompiling 

An other odd behaviour is when we exchange the order of the decorators:

- this returns an error (as we expect)
```python
import chex
import equinox as eqx
import jax

@chex.assert_max_traces(1)
@jax.jit
def f(x, i):
    print("COMPILE")
    return x * 2


for i in range(10):
    print(f(2.0 * i, i))
```

```bash
ValueError: @assert_max_traces must not wrap JAX-transformed function (@jit, @vmap, @pmap etc.); change wrappers ordering.
```

But this not:

```python
import chex
import equinox as eqx
import jax

@chex.assert_max_traces(1)
@eqx.filter_jit
def f(x, i):
    print("COMPILE")
    return x * 2


for i in range(10):
    print(f(2.0 * i, i))
```

which returns:

```bash
COMPILE
0.0
COMPILE
4.0
COMPILE
8.0
COMPILE
12.0
COMPILE
16.0
COMPILE
20.0
COMPILE
24.0
COMPILE
28.0
COMPILE
32.0
COMPILE
36.0
```

Why could that be ? Thanks for any help :)

**Comment by pablo2909** [comment]
Oh it might be because `filter_jit` considers static non-jax and non-numpy array, but it doesn't explain why `chex` doesn't catch it, no ?

**Comment by patrick-kidger** [comment]
> Oh it might be because `filter_jit` considers static non-jax and non-numpy array, but it doesn't explain why `chex` doesn't catch it, no ? 

Yup, exactly. In this case the recompilations are as-intended with Equinox. However the fact that Chex doesn't catch them is a little odd (arguably a Chex bug).

You may like to use `eqx.debug.assert_max_traces` instead.

**Comment by pablo2909** [comment]
I will , thank you :) I'll report the bug the Chex and close it here then !
