### ISSUE TITLE
what does eqx.experimental.set_state do in the following code?

### ISSUE THREAD

**Issue by Basant1861** [patrick-kidger/equinox#663]
I am using the following code snippet (specifically the function **load_torch_weights**) but it uses some equinox methods(**eqx.experimental.set_state** and **eqx.experimental.StateIndex**) which seem no longer supported in the latest version of equinox. Since this function seems to be a good way of converting torch weights to equinox , I would like to know what are the alternatives to using **eqx.experimental.set_state** and **eqx.experimental.StateIndex**. 

[https://github.com/paganpasta/eqxvision/blob/main/eqxvision/utils.py](url)

Regards,

**Comment by patrick-kidger** [comment]
Hey there! So these got replaced with a stable (no longer experimental, much better behaved) stateful API -- [see here](https://docs.kidger.site/equinox/api/nn/stateful/).  (In particular the example linked at the top is a useful reference.)

Unfortunately I think Eqxvision is only semi-maintained at this point. Not my project, so not much I can do! I'd love to see ths updated to the stable API.

**Comment by Basant1861** [comment]
hello Patrick! Just wanted to know if you would be able to look into this issue. Thanks!

**Comment by Artur-Galstyan** [comment]
@Basant1861 I'd love to help, but we can be much more helpful if you provided a little code snippet (MVP ideally) with the concrete issue/error you're facing. Otherwise, it's very difficult to assist you.

**Comment by Basant1861** [comment]
@Artur-Galstyan Hello....Apologies for the long delay in responding. I chose not to go down the rabbit hole so postponed this issue altogether. Is there a way to put this post on hold or something which marks it as "not an open issue but just on hold". Or shall I leave it as it is?

**Comment by Artur-Galstyan** [comment]
Hi there, one option would be to close the issue. Normally question type issues are left open for others in case they have the same problem. Unfortunately, I don't really understand the question at hand here :/ I'd say keep this open if you choose to go down the rabbit hole, otherwise you can close it :)

**Comment by patrick-kidger** [comment]
I think this is about a topic that is sufficiently out-of-date that I'm going to close it. :)
