### ISSUE TITLE
Feature request for custom behavior in apply_updates

### ISSUE THREAD

**Issue by mjo22** [patrick-kidger/equinox#678]
Hello again! I have a small feature request related to my question on #676.

I have an optimization problem where I need custom behavior in `eqx.apply_updates`. Therefore, I am wondering if this function can be generalized to accept an optional `update_fn` argument, whose default is the current `_apply_update` [here](https://github.com/patrick-kidger/equinox/blob/main/equinox/_update.py).

In #676, I mention that I am looking for a way to re-parameterize my models to a space where typical `eqx.apply_updates` behavior is a good thing to do (i.e. transforming a positive real quantity to a log scale).

However, I have a problem where it is not possible to transform to a space where I can do a simple additive parameter update. In particular, I need to optimize over the space of rotation matrices. In this case, I cannot necessary simply do this because rotation matrices do not commute.

There are many ways to approach this kind of problem, many of which are easily supported in the current framework and do involve additive parameter updates. However, one good way to do it is implemented in the package `jaxlie`, in particular in its [`jaxlie.manifold`](https://github.com/brentyi/jaxlie/tree/master/jaxlie/manifold) submodule. Without getting into too much detail, the function `jaxlie.manifold.rplus` is an `apply_updates` generalization that involves a matrix multiplication update. I would like to do something similar using generic behavior from the `equinox` ecosystem.

**Comment by patrick-kidger** [comment]
So `apply_updates` is a very simple function! It really only exists to produce something that looks a bit like Optax. I think for more advanced uses cases like your own, I would recommend writing your own tree-map that accomplishes what you're after.

**Comment by mjo22** [comment]
Okay, that makes sense! Looks easy to implement.
