### ISSUE TITLE
Could filtered transformations accept an optional filter_spec?

### ISSUE THREAD

**Issue by mjo22** [patrick-kidger/equinox#682]
Hi Patrick, I was thinking more about #618, and I was wondering your thoughts on the following:

```python
@partial(eqx.filter_grad, filter_spec=filter_spec)
def loss_fn(model, x, y):
    return jnp.sum((y - model(x))**2)

x, y = …
model = SomeComplicatedModule(…)
filter_spec = … # create a filter spec of model
grads = loss_fn(model, x, y)
```

In the above, filter_grad would take an optional filter_spec that is a prefix of model. I know the current paradigm is explicit calls to eqx.partition and eqx.combine, but I think this addition would make working with filtered transformations more user friendly for people that are new to pytrees, jax, and equinox (this is very important for my library). In general I’d like do this with filter_vmap and filter_pmap as well. What do you think?

My current solution is to create wrappers that do something like this (see [here](https://github.com/mjo22/cryojax/blob/main/src/cryojax/core/_filtered_transformations.py)). However, I’m not a big fan of doing this in my library and am wondering if you’ve thought about if something like this belongs in equinox. I imagine there is some implementation detail that complicates things that I don’t understand here.

**Comment by patrick-kidger** [comment]
Haha! This actually used to exist: they got removed [in Equinox v0.10.0](https://github.com/patrick-kidger/equinox/releases/tag/v0.10.0).

In practice they were used very rarely for `filter_grad` and essentially never for the other transformations, so it made sense to get rid of them. This gave us dramatically simpler code -- besides being easier to maintain, I think this makes it a lot more convincing to believe that operations like `eqx.filter_*` really are fairly thin wrappers around their `jax.*` counterparts.

For this reason I'm afraid it's unlikely these will every appear in Equinox -- we already tried them and we didn't like them! :)

**Comment by mjo22** [comment]
This totally makes sense, very good to know. If you have any warnings against doing this in practice, please let me know! I’ve implemented this in the linked code with wrappers around `eqx.filter_*` (which is admittedly a little tedious).

**Comment by patrick-kidger** [comment]
There's nothing really wrong with it. In the context of user friendliness (which you mention), I think the only thing I'd say is that it ended up being a complicated part of an API that a new user would see very early on, which was another contributing reason to its demise.
