### ISSUE TITLE
[Bug?] Possible incompatible interaction between optax and equinox?

### ISSUE THREAD

**Issue by ericmjl** [patrick-kidger/equinox#69]
Hi @patrick-kidger, I'm reporting what I _think_ might be a bug in the interaction between equinox and optax (though I am a bit unsure as to which library to report it in).

Specifically, there is a weird error that shows up whenever I use the MLP module with a subset of optax optimizers.

Here is a minimal reproducible example. With the following code block:

```python
import optax 
import equinox as eqx 
from jax.example_libraries import stax
from jax import random, nn

optimizer = optax.adabelief(learning_rate=1e-3) # errors out on adam, adamw; no errors with sgd
model = eqx.nn.Sequential(
    [
        eqx.nn.Linear(in_features=1, out_features=1024, key=random.PRNGKey(45)),
        nn.relu,  # no problem when commented out
        eqx.nn.Linear(in_features=1024, out_features=1, key=random.PRNGKey(39)),
    ]
)
opt_state = optimizer.init(model)
```

I get the following stack trace (hidden in details):

<details>
<pre><code>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/ericmjl/github/incubator/score-models/notebooks/scratch.ipynb Cell 11' in <module>
      7 # model = GaussianModel()
      8 model = eqx.nn.Sequential(
      9     [
     10         eqx.nn.Linear(in_features=1, out_features=1024, key=random.PRNGKey(45)),
   (...)
     13     ]
     14 )
---> 15 opt_state = optimizer.init(model)

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/_src/combine.py:45, in chain.<locals>.init_fn(params)
     44 def init_fn(params):
---> 45   return tuple(fn(params) for fn in init_fns)

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/_src/combine.py:45, in <genexpr>(.0)
     44 def init_fn(params):
---> 45   return tuple(fn(params) for fn in init_fns)

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/optax/_src/transform.py:457, in scale_by_belief.<locals>.init_fn(params)
    456 def init_fn(params):
--> 457   mu = jax.tree_map(jnp.zeros_like, params)  # First moment
    458   s = jax.tree_map(jnp.zeros_like, params)  # Second Central moment
    459   return ScaleByBeliefState(count=jnp.zeros([], jnp.int32), mu=mu, nu=s)

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/jax/_src/tree_util.py:184, in tree_map(f, tree, is_leaf, *rest)
    182 leaves, treedef = tree_flatten(tree, is_leaf)
    183 all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 184 return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/jax/_src/tree_util.py:184, in <genexpr>(.0)
    182 leaves, treedef = tree_flatten(tree, is_leaf)
    183 all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
--> 184 return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py:1889, in zeros_like(a, dtype, shape)
   1887 @_wraps(np.zeros_like)
   1888 def zeros_like(a, dtype=None, shape=None):
-> 1889   _check_arraylike("zeros_like", a)
   1890   lax_internal._check_user_dtype_supported(dtype, "zeros_like")
   1891   if np.isscalar(shape):

File ~/anaconda/envs/score-models/lib/python3.9/site-packages/jax/_src/numpy/util.py:298, in _check_arraylike(fun_name, *args)
    295 pos, arg = next((i, arg) for i, arg in enumerate(args)
    296                 if not _arraylike(arg))
    297 msg = "{} requires ndarray or scalar arguments, got {} at position {}."
--> 298 raise TypeError(msg.format(fun_name, type(arg), pos))

TypeError: zeros_like requires ndarray or scalar arguments, got <class 'jax._src.custom_derivatives.custom_jvp'> at position 0.

</code></pre></details>

On the other hand, if one were to comment out the `nn.relu` line above, we would have no issues running the code above.

Not knowing the internals of equinox well enough (I only started playing with it today), I'm not exactly sure how to pinpoint what the exact issue is, so I decided to report the matter here first.

**Comment by patrick-kidger** [comment]
See [the FAQ](https://docs.kidger.site/equinox/faq/#optax-is-throwing-an-error). You need to add an `eqx.filter` in there.

If you think this could be more clearly advertised then I'd be happy accept a PR improving rhe documentation.

**Comment by ericmjl** [comment]
That unblocked me! Thank you, @patrick-kidger!

I'm wondering if you'd be open to changing the title of the FAQ from "FAQ" to "Common Debugging Questions"? That might be all it takes to make the page a bit more prominent. I'm happy to handle the PR for that :smile:.

**Comment by patrick-kidger** [comment]
I think FAQ is the standard name for such a page.
