### ISSUE TITLE
Elegant way to index pytrees at arbitrary leaves using equinox?

### ISSUE THREAD

**Issue by mjo22** [patrick-kidger/equinox#695]
Hello! I have a question for a problem I'm working on, and I was wondering if anyone may have the time to offer some insight. I ask because I suspect that tools in `eqx.internal` may be useful, and I am not too familiar with them.

As a completely arbitrary example, let's say I have the following pytree

```python
a_1, a_2, a_3 = ...  # Three arrays with the same leading dimension
b, c = ... # Two other arrays with different leading dimensions than a_i, and also from each other
tree = [(a_1, a_2, a_3), b, None, (c, (None,))]
```

The question is the following: is there an elegant way within `equinox` for me to return a pytree with the same structure as `tree`, where each of `(a_1, a_2, a_3)`, `b`, and `c` are indexed at an arbitrary index `(i_a, i_b, i_c)`? (this is related to my [question](https://github.com/patrick-kidger/optimistix/issues/55) in `optimistix`)

To be more clear, I'm wondering if there is a neat (and efficient) way to grab the structure

```python
tree_at_index = [(a_1[i_a], a_2[i_a], a_3[i_a]), b[i_b], None, (c[i_c], (None,))]
```

For example, would the indexing tools [here](https://github.com/patrick-kidger/equinox/blob/main/equinox/internal/_omega.py) be useful? If so, would there happen to be some example code in a privileged downstream library that someone could point me to?

**Comment by patrick-kidger** [comment]
I think this be doable with `jax.tree_util.tree_map(lambda index, subtree_of_arrays: jax.tree_util.tree_map(lambda array: array[index], subtree_of_arrays), pytree_of_indices, pytree_of_arrays)`?

**Comment by mjo22** [comment]
This makes sense. I think I misunderstood the indexer!
