### ISSUE TITLE
`UnexpectedTracerError` when vmapping `SpectralNorm`

### ISSUE THREAD

**Issue by pablo2909** [patrick-kidger/equinox#705]
Hello,

I am getting an `UnexpectedTracerError` when running the following code:

```python
import jax.numpy as jnp
import equinox as eqx
from jax import lax
from jax import random


VAL = 0.5

class SpectralLinear(eqx.Module):
    lin: eqx.Module

    def __init__(self, *, key: random.PRNGKey):
        lin_key, norm_key = random.split(key)
        self.lin = eqx.nn.SpectralNorm(
            eqx.nn.Linear(2, 2, key=lin_key), weight_name="weight", key=norm_key
        )

    def __call__(self, x, state):
        return self.lin(x, state)


spectral_lin, state = eqx.nn.make_with_state(SpectralLinear)(key=random.PRNGKey(0))

def call(f, x, s):
    return f(x, s)


@eqx.filter_jit
def vmap_condf(net, state, x, sigma):
    net_array, net_not_array = eqx.partition(net, eqx.is_array)

    def condf(net, state, x, sigma):
        net_val, new_state = lax.cond(
            sigma > VAL,
            lambda x, n, state: call(eqx.combine(n, net_not_array), x, state),
            lambda x, n, state: call(eqx.combine(n, net_not_array), x, state),
            x,
            net,
            state,
        )
        return net_val, new_state

    return eqx.filter_vmap(condf, in_axes=(None, None, 0, 0), out_axes=(0, None))(
        net_array, state, x, sigma
    )


vmap_condf(
    spectral_lin, state, jnp.arange(6.0).reshape(3, 2), jnp.array([1.0, 0.0, 0.2])
)
```

The error does not happen if I do not use `SpectralNorm`. Any indication on what is going on ? 

Thank you :)

Edit:

If using the `JAX_CHECK_TRACER_LEAKS` then the error is:

```bash
Exception: Leaked trace MainTrace(2,BatchTrace). Leaked tracer(s):

Traced<ShapedArray(float32[2])>with<BatchTrace(level=2/0)> with
  val = Traced<ShapedArray(float32[3,2])>with<DynamicJaxprTrace(level=1/0)>
  batch_dim = 0
This BatchTracer with object id 4954725552 was created on line:
  /Users/test.py:34:29 (vmap_condf.<locals>.condf)
<BatchTracer 4954725552> is referred to by <list 4954778176>[1]
<list 4954778176> is referred to by <tuple 4951074368>[0]
<tuple 4951074368> is referred to by <_FlattenedData 4951326160>.static_field_values

Traced<ShapedArray(float32[2])>with<BatchTrace(level=2/0)> with
  val = Traced<ShapedArray(float32[3,2])>with<DynamicJaxprTrace(level=1/0)>
  batch_dim = 0
This BatchTracer with object id 4954725472 was created on line:
  /Users/test.py:34:29 (vmap_condf.<locals>.condf)
<BatchTracer 4954725472> is referred to by <list 4954778176>[0]
<list 4954778176> is referred to by <tuple 4951074368>[0]
<tuple 4951074368> is referred to by <_FlattenedData 4951326160>.static_field_values
```

**Comment by patrick-kidger** [comment]
It's pretty subtle, but this is actually a bug in your choice of `out_axes`. You should have `out_axes=(0, 0)`. As the model state interacts with the vmap'd input then it also picks up a batch tracer.

We could probably affor to have a better error message here, though! I'd be happy to take a pull request on that. The relevant line is here:

https://github.com/patrick-kidger/equinox/blob/b88edca745129693385ed91861670163b79850e1/equinox/_vmap_pmap.py#L208

where we could check whether any elements of `_nonvmapd` have a batch tracer.

**Comment by pablo2909** [comment]
Thank you for the prompt answer Patrick ! I would be happy to contribute with a PR on that. Follow-up question though, why does this work then ?

```python
import equinox as eqx
import jax
import jax.numpy as jnp
from jax import lax, random

VAL = 0.5


class SpectralLinear(eqx.Module):
    lin: eqx.Module

    def __init__(self, *, key: random.PRNGKey):
        lin_key, norm_key = random.split(key)
        self.lin = eqx.nn.SpectralNorm(
            eqx.nn.Linear(2, 2, key=lin_key), weight_name="weight", key=norm_key
        )

    def __call__(self, x, state):
        return self.lin(x, state)


spectral_lin, state = eqx.nn.make_with_state(SpectralLinear)(key=random.PRNGKey(0))


def call(f, x, s):
    return f(x, s)


@eqx.filter_jit
def vmap_condf(net, state, x, sigma):
    net_array, net_not_array = eqx.partition(net, eqx.is_array)

    def condf(net, state, x, sigma):
        # net_val, new_state = lax.cond(
        #     sigma > VAL,
        #     lambda x, n, state: call(eqx.combine(n, net_not_array), x, state),
        #     lambda x, n, state: call(eqx.combine(n, net_not_array), x, state),
        #     x,
        #     net,
        #     state,
        # )
        net_val, new_state = call(eqx.combine(net, net_not_array), x, state)
        return net_val, new_state

    return eqx.filter_vmap(condf, in_axes=(None, None, 0, 0), out_axes=(0, None))(
        net_array, state, x, sigma
    )


vmap_condf(
    spectral_lin, state, jnp.arange(6.0).reshape(3, 2), jnp.array([1.0, 0.0, 0.2])
)

```

**Comment by pablo2909** [comment]
Second follow up question :) but I'm not sure how to treat the batched state. Let's say I want to call a second time `vamp_condf`, how should this be done ? should I average the state across the batch dimension ?

```python
_, batched_state = vmap_condf(
    spectral_lin, state, jnp.arange(6.0).reshape(3, 2), jnp.array([1.0, 0.0, 0.2])
)

_, second_batched_state = vmap_condf(
    spectral_lin,
    batched_state.mean(axis=0), # something like .mean(axis=0) but in a way that works
    jnp.arange(2.0, 8.0).reshape(3, 2),
    jnp.array([2.0, 1.0, 0.0]),  
)
```
I guess I never wondered before how it works when using PyTorch and it was abstracted away

**Comment by patrick-kidger** [comment]
Haha! It's about whether the predicate of the `lax.cond` is batched. In your first question, `sigma` is batched so the predicate `sigmal > VAL` is batched. So the `lax.cond` will need to return different values depending on whether each batch element of this predicate is true or false. So *all* outputs of the `lax.cond` are necessarily batched as well.

(Sorry, I should have been more precise in my previous answer about where this batch tracer was coming from.)

As for how you want to handle the batched state -- up to you, really! The batching was introduced because of whatever the `lax.cond` is doing for you, so the appropriate reduction logic will likewise depend on what you are trying to accomplish mathematically. (If each element of your batch continues to have some particular meaning between calls, then perhaps you could pass it back around as a batched input to your next `vmap`.)

I'm not sure how PyTorch handles this in particular, but IIRC PyTorch will usually either (a) throw an error and not allow you to use batched predicates in if statements (e.g. `if non_scalar_tensor:`) or (b) pick a member of your `state` batch element arbitrarily (e.g. I recall `torch.nn.DataParallel` did that back in the day).

**Comment by pablo2909** [comment]
Ok I see, thanks a lot for the explanation ! It was quite subtle indeed. 

I'll close the issue and come back with a small PR to improve the error message :)
