### ISSUE TITLE
Question - How to assert that a `filter_spec` is valid?

### ISSUE THREAD

**Issue by itk22** [patrick-kidger/equinox#756]
Hi Patrick,

I would like to know if it's possible to assert that a `filter_spec` is valid for a given PyTree and control the error message. In my code, I am making it possible to use a custom filter to partition the model for the training. I want to produce informative error messages - for example, in the code below, I would like to be able to print "Invalid filter" or something similar if the user provides an `invalid_filter`. 

```
import equinox as eqx
import jax.tree_util as jtu


class Mock(eqx.Module):
    id: int


mock = Mock(id=12)

# Valid filter
valid_filter = lambda m: m.id

# Invalid filter - nodes is not a leaf
invalid_filter = lambda m: m.name

filter_spec = jtu.tree_map(lambda _: False, mock)
filter_spec = eqx.tree_at(
    valid_filter,
    filter_spec,
    replace=True,
)

mock_filtered = eqx.filter(mock, filter_spec)
print(mock_filtered)
```

**Comment by patrick-kidger** [comment]
I think JAX+Equinox's errors themselves should detect any invalid filters. If you want to provide a custom error message then this is probably best done with `try/except`.

**Comment by itk22** [comment]
Ahh, I see, thanks for the reply!
