### ISSUE TITLE
`Conv` doesn't support complex dtype

### ISSUE THREAD

**Issue by ChenAo-Phys** [patrick-kidger/equinox#763]
The convolutional layer in jax supports complex data types in principle, but the current `Conv` layer in equinox doesn't. The only problem is the default weight initialization `self.weight = jrandom.uniform(...)`, which doesn't work with complex types.

I want to have a minor change to make the default initialization `jrandom.normal` when the dtype is complex. I can submit a PR if it looks good to you @patrick-kidger

**Comment by ChenAo-Phys** [comment]
I forgot to mention that some other layers like `Linear` have similar problems.

**Comment by patrick-kidger** [comment]
It looks like JAX has intentionally not added support for this: https://github.com/google/jax/issues/4680

I'd be happy to add support for this, but I'd suggest keeping the distribution used consistent with the existing choice, i.e. make it be a uniform distribution. (Whether that's defined componentwise or magnitude-wise.)
