### ISSUE TITLE
Remove references to internal `jax.core.pp_*` functions

### ISSUE THREAD

**Issue by jakevdp** [patrick-kidger/equinox#766]
These are deprecated as of the latest JAX release (https://github.com/google/jax/pull/21829)

Equinox is the only user of these APIs that I can find – I'm curious about your thoughts of how to move forward here. Could equinox migrate to its own implementation? Or is this a good case for `jax.extend.core`, even thought there is very little other usage outside JAX?

On the other hand, this file already reaches into `jax._src` directly. Maybe grabbing `pp_` APIs directly from `jax._src` is the right solution. What do you think?

**Comment by patrick-kidger** [comment]
Our use of custom pp rule is for `eqx.internal.noinline`, which is itself an undocumented+unusual API. This custom rule is really just a minor nice-to-have, so I'm happy to just remove Equinox's use of this! :)
Done in #767!

**Comment by jakevdp** [comment]
Thanks!
