### ISSUE TITLE
How to extract learnable parameters of a subnetwork

### ISSUE THREAD

**Issue by itk22** [patrick-kidger/equinox#773]
Hi Patrick, 

Could you please advise me on how I could partition a model so that only the learnable parameters of a subnetwork are modified in the optimization? For example, consider a module encompassing a hypernetwork that predicts a target network's weights. My attempt so far looks like this:
```
base_filter = jt.map(lambda _: False, hyper_siren)
context_filter = eqx.tree_at(
    lambda tree: tree.hyper_net,
    base_filter,
    replace=True,
)

params, static = eqx.partition(hyper_siren, context_filter)
```
which results in errors, because of hyper_net's activation functions etc. I am sure this can be done with Equinox, it's just that I haven't been able to implement it.

**Comment by patrick-kidger** [comment]
Perhaps something like
```
base_filter = jtu.tree_map(lambda _: False, hyper_siren)
hyper_filter = jtu.tree_map(eqx.is_array, hyper_siren.hyper_net)
eqx.tree_at(lambda tree: tree.hyper_net, base_filter, hyper_filter)
```

**Comment by itk22** [comment]
That's exactly what I was looking for, thanks!
