### ISSUE TITLE
test_traceback_runtime_eqx fails with latest jaxtyping (0.2.33)

### ISSUE THREAD

**Issue by GaetanLepage** [patrick-kidger/equinox#781]
The test suites passes fine with jaxtyping <= 0.2.31 but, with more recent versions of jaxtyping I observe the following failure:

```
=========================== short test summary info ============================
FAILED tests/test_errors.py::test_traceback_runtime_eqx - assert 3 == 2
======= 1 failed, 390 passed, 1 skipped, 57 warnings in 64.44s (0:01:04) =======
```

See complete logs [here](https://pastebin.com/XqcqUHvd).

Can something be wrong on my end ?

Context: updating jaxtyping in nixpkgs: https://github.com/NixOS/nixpkgs/pull/326520

**Comment by patrick-kidger** [comment]
Ah, this is something I already sorted out on for Equinox at HEAD, and I just haven't done a new release for yet. If you can hang in there for a bit then I'm hoping to do one fairly shortly. (My hope is to get #704 in first.)

These tests have generally been the ones that keep popping up -- they're far too sensitive to the internal details of other libraries -- so I've actually now pruned them back to try and minimise the spurious issues here.

**Comment by GaetanLepage** [comment]
Ok understood. Thank you for your answer !
We will skip this test for now then.

**Comment by GaetanLepage** [comment]
Everything seems to be working now.
Closing :)
