### ISSUE TITLE
Better error messages for strict

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/equinox#782]
When programming on objects with lots of abstract method (e.g. https://github.com/lockwo/distreqx/blob/main/distreqx/distributions/_distribution.py), you sometimes forget to define a method (especially if the base class doesn't actually implement and just raises a NotImplementedError). In cases like this, you get a somewhat uninformative error message along the lines of `TypeError: Abstract strict 'eqx.Module's must be named starting with 'Abstract' or '_Abstract'.`

For example:

```python
import equinox as eqx
from abc import abstractmethod


class AbstractA(eqx.Module, strict=True):

    @abstractmethod
    def foo(self):
        pass


class B(AbstractA, strict=True):

    #def foo(self):
    #    return 

b = B()
```
yields `TypeError: Abstract strict 'eqx.Module's must be named starting with 'Abstract' or '_Abstract'. Got B when defining __main__.B.`

(uncommenting fixes it). Of course, this is expected and should error. However, it would be very helpful if the error message would indicate which abstract function isn't defined (which is the cause of the error). E.g. `TypeError: Abstract strict 'eqx.Module's must be named starting with 'Abstract' or '_Abstract'. Method 'foo' is undefined in concrete class B` or something like that would be great.

Does this suggestion sound within the realm of possibility?

**Comment by patrick-kidger** [comment]
Absolutely! I'd be happy to take a PR on this.
