### ISSUE TITLE
Calling eqx.Module method invokes user defined __getattr__

### ISSUE THREAD

**Issue by yuzu-ido** [patrick-kidger/equinox#791]
Hi team, thank you for providing Equinox. I have encountered a new issue in 0.11.4 that has not been a problem up to 0.11.3. When I have a `eqx.Module` based class with a user defined `__getattr__, `calling a method now calls `__getattr__` twice. This is a problem since my` __getattr__` itself needs to call a method, resulting in an infinite loop. Please let me know if this behavior can be reverted. 
```
import equinox as eqx

class Foo(eqx.Module):
    baz: str = "foobaz"

    def __getattr__(self, name):
        print("you've hit getattr", name)
        return "getattr"

    def moo(self):
        return "moo"

print(Foo().baz)  # existing variable
print(Foo().pie)  # missing variable
print(Foo().moo())  # existing method
```
Output:
```
foobaz
you've hit getattr pie
getattr
you've hit getattr __name__
you've hit getattr __qualname__
moo
```
System info:
jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.4
python: 3.10.9 (main, Jan 16 2023, 22:37:31) [Clang 15.0.7 ]
jax.devices (1 total, 1 local): [cuda(id=0)]
equinox: 0.11.4

**Comment by patrick-kidger** [comment]
So as a general Python thing (unrelated to JAX or Equinox) it's usually inadvisible to have a wildcard `__getattr__` that attempts to handle everything. It's pretty common for any code you interact with try to try doing something like:
```python
if hasattr(your_obj, "__some_magic_method__"):
    your_obj.__some_magic_method__(...)
```
which will give unexpected behaviour here!

In this case you're running afoul of exactly this kind of thing in Equinox: we check for `__name__` and `__qualname__` attributes at various points internally (along with several other special attributes) to be sure that we can forward them appropriately e.g. across flattening+unflattening.

The best fix here would be to check the value of `name` in your `__getattr__`, and only handle the ones you know you want to handle.

An alternative would be to handle this case in particular by doing:
```python
if name in ("__name__", "__qualname__"):
    raise AttributeError
```

**Comment by yuzu-ido** [comment]
Thanks for the response. There's quite a lot of `name` I'd want to handle, so the alternative option sounds like a plan. My temporary fix was to copy and paste the ~10 line helper function into` __getattr__` directly but that seems cleaner.
