### ISSUE TITLE
Non-default `__init__` with `default_factory` throws error.

### ISSUE THREAD

**Issue by samuelstevens** [patrick-kidger/equinox#811]
```py
import equinox as eqx


class Module(eqx.Module):
    stuff: object
    default_int: 2
    default_lst: list[object] = eqx.field(default_factory=list)

    def __init__(self, stuff: object):
        self.stuff = fancy_calculation(stuff)


if __name__ == "__main__":
    module = Module(1)
```

This raises `ValueError: The following fields were not initialised during __init__: {'lst'}`.

I would like to define both a custom constructor and define mutable defaults for attributes in my modules. Is this possible?

Maybe this is an issue with dataclasses rather than equinox Modules. If so, I'll open an issue with Python.

**Comment by patrick-kidger** [comment]
`default_factory` is only used if you do not define a custom `__init__` method. This is normal dataclass behaviour that we inherit :)

**Comment by samuelstevens** [comment]
Sounds good. Thanks.
