### ISSUE TITLE
Comparable PixelShuffle functionality?

### ISSUE THREAD

**Issue by mathDR** [patrick-kidger/equinox#812]
Is there a way to add a bespoke layer?  In particular, I am trying to reproduce a `torch` model that has a `PixelShuffle(2)` layer embedded in a `nn.Sequential()` call.

What would be the best way to do that?

**Comment by lockwo** [comment]
You can write a module that has the functionality you want, and use it in your bigger model. Like https://github.com/patrick-kidger/equinox/issues/809#issuecomment-2303854615 for example
