### ISSUE TITLE
Type errors with Module

### ISSUE THREAD

**Issue by NeilGirdhar** [patrick-kidger/equinox#814]
For some reason, PyRight doesn't realize that degenerate derived classes have the same constructor as their parent class.
```python
from collections.abc import Mapping
from typing import override
import equinox as eqx

class Node(eqx.Module):
    name: str | None

    @override
    def __init__(self, *, streams: Mapping[str, int]) -> None:
        super().__init__()
        self.name = None

class Derived(Node):
    pass

Node(streams={})  # No error!
Derived(streams={})
# ...:22:1 - error: Argument missing for parameter "name" (reportCallIssue)
# ...:22:9 - error: No parameter named "streams" (reportCallIssue)
#    2 errors, 0 warnings, 0 informations
```

**Comment by NeilGirdhar** [comment]
Actually, I'm going to go back to never overriding `__init__`, and stick to just filling in `__post_init__` as before.

**Comment by ponseko** [comment]
Sorry dropping in this old threat, but this does seem like a legitimate issue still in 0.12.2.
The code below runs fine and gives no type warning when `A` is a regular dataclass, so you'd expect the same behaviour for an eqx.Module.

```python
class A(eqx.Module):
    x: int

class B(A):
    def __init__(self, a, b):
        self.x = a + b

class C(B):
    pass
    
c = C(1, 2) # !! Expected 1 positional argument Pylance
```

Advising not to use `__init__` for child classes seems a bit off here. Perhaps this is already fixed in upcoming #1028 ?

**Comment by NeilGirdhar** [comment]
Why is it "off"?

**Comment by patrick-kidger** [comment]
@ponseko - this is a known limitation of pyright / of static type-checking for dataclasses.

Equinox Modules are _very nearly_ frozen dataclasses, with precisely two divergences, both in their `__init__` methods:

1. Despite being frozen you can write `self.foo = foo` inside `__init__` methods. (Not normally possible with frozen dataclasses, which think this is mutation.)
2. `__init__` methods are inherited by subclasses. (Normally dataclasses would still create an autogenerated `__init__` method that just fills in the fields.)

There's no way to communicate point 2 to the type checker, and so the appropriate way around this is indeed a `# pyright: ignore` I'm afraid.

**Comment by NeilGirdhar** [comment]
Why not something like this:

```python
class A(eqx.Module):
    x: int = eqx.field(init=False)

class B(A):
    a: InitVar[Any]
    b: InitVar[Any
    def __post_init__(self, a, b):  # you should still get in the habit of calling super here.
        self.x = a + b

class C(B):
    pass
    
c = C(1, 2)
```

I think that should work?

**Comment by ponseko** [comment]
@NeilGirdhar Neat, that indeed removes the errror -- and (perhaps more importantly) gives proper type hints, even when using `__init__`. Thank you.

My previous phrasing of using `__post_init__` was itself probably a bit _off_. It's a valid solution for sure, but I like that `eqx.Module`s just behave nicely for any regular (downstream) user in that you can just use `__init__` in the way anyone would expect. The reasoning for why this cannot be the case here makes sense, thanks @patrick-kidger.
