### ISSUE TITLE
Accessing self during __post_init__ seems to result in a differently registered pytree

### ISSUE THREAD

**Issue by garymm** [patrick-kidger/equinox#840]
I'm trying to create a class that manages both the optimizer state and some neural network.

In order to accomplish this I am trying to initialize the optimizer state in `__post_init__`. However it seems that the pytree registration for the type that is `self` in `__post_init__` differs from the pytree registration after `__post_init__`, and this leads to errors with the message `Custom node type mismatch`.

As minimal an example as I could come up with:

```python
import equinox as eqx
import jax
import jax.numpy as jnp
import optax

class Bar(eqx.Module):
    net: eqx.Module
    opt_state: optax.OptState = eqx.field(init=False)

    def __post_init__(self):
        yes, no = self.partition_for_grad()
        self.opt_state = optax.adam(1e-3).init(yes)

    def apply_grads(self, grads) -> "Bar":
        updates, opt_state = optax.adam(1e-3).update(grads, self.opt_state)
        self = eqx.tree_at(lambda x: x.opt_state, self, opt_state)
        return eqx.apply_updates(self, updates)

    def partition_for_grad(self) -> "tuple[Bar, Bar]":
        def is_array_in_net(path, value):
            return isinstance(value, jnp.ndarray) and jax.tree_util.GetAttrKey(name="net") == path[0]

        filter_spec = jax.tree_util.tree_map_with_path(is_array_in_net, self)
        yes, no = eqx.partition(self, filter_spec)
        return yes, no


net = eqx.nn.Linear(10, 10, key=jax.random.PRNGKey(0))

bar = Bar(net)
def loss(bar_yes_grad, bar_no_grad):
    bar = eqx.combine(bar_yes_grad, bar_no_grad)
    return jnp.sum(bar.net.weight)

bar_yes_grad, bar_no_grad = bar.partition_for_grad()
grads = jax.grad(loss)(bar_yes_grad, bar_no_grad)
bar = eqx.combine(bar_yes_grad, bar_no_grad)
bar = bar.apply_grads(grads)
```

The error is:
```
ValueError: Custom node type mismatch: expected type: <class '__main__.Bar'>, value: Bar(
  net=Linear(
    weight=f32[10,10],
    bias=f32[10],
    in_features=10,
    out_features=10,
    use_bias=True
  ),
  opt_state=<uninitialised>
).
```

I have also tried inserting code into both `__post_init__` and `apply_grads` to set `opt_state=None`, but that doesn't seem to fix it:
```python
    def __post_init__(self):
        yes, no = self.partition_for_grad()
        yes.opt_state = None
        self.opt_state = optax.adam(1e-3).init(yes)

    def apply_grads(self, grads):
        grads = eqx.tree_at(lambda x: x.opt_state, grads, None)
        updates, self.opt_state = optax.adam(1e-3).update(grads, self.opt_state)
        return eqx.apply_updates(self.net, updates)
```

**Comment by patrick-kidger** [comment]
Ah, this is a detail of how Equinox handles initialisation. During `__init__` time we substitute `self.__class__` with a different one that allows you to call `__setattr__`. (Meanwhile the rest of the time if you try to do `some_value.some_field = some_value` then you'll get an error, as `eqx.Module`s should be treated as immutable.)

Note that what you're trying to do here doesn't really make a whole lot of sense -- `yes` has type `Bar`, which includes a field `opt_state`... which you're only now the in the process of assigning!

If you want to wrap model and optimizer state together that's totally fine, but you should partition just the `.net`, not the whole of `self`. :)

**Comment by garymm** [comment]
OK I guess WAI then? Thanks for the explanation.
