### ISSUE TITLE
StateIndex is a Module, but not a PyTree

### ISSUE THREAD

**Issue by NeilGirdhar** [patrick-kidger/equinox#842]
Is this a correct usage of stateful programming?
```python
import equinox as eqx
import jax.numpy as jnp
from jax import jit


class Model(eqx.Module):
    x: eqx.nn.StateIndex = eqx.field(init=False)

    def __post_init__(self) -> None:
        self.x = eqx.nn.StateIndex(jnp.zeros(()))


@jit
def f(m: Model, state: eqx.nn.State) -> None:
    pass


model, state = eqx.nn.make_with_state(Model)()
f(model, state)
```
If so, why isn't `StateIndex` a PyTree?

**Comment by NeilGirdhar** [comment]
It seems like in a variety of places, Equinox is torn between making modules py-trees (with all static fields marked as static) versus leaving some static fields as dynamic to allow using `tree_at`, etc. to modify those fields.

This is seems confusing to me (at least for now).  Would it be possible to either add a flag to `tree_at` so that it crawls over some static fields, which can be marked `crawlable`?  That way, Equinox modules are always pytrees, and you still have the behavior you want.

**Comment by patrick-kidger** [comment]
I believe `StateIndex` is a pytree. It just subclasses `eqx.Module` in the usual way.

Looking at your PR it seems like you're trying to avoid having non-arrays in its PyTree structure. I can see that that's a small QoL improvement, which seems reasonable to me.

On your latter point: note that it's not possible to have a module declare its static fields at class definition time. Consider for example `eqx.nn.MLP.activation`, which may be a 'static' `jax.nn.relu` or a 'dynamic' `eqx.nn.PReLU`.

WDYT?

**Comment by NeilGirdhar** [comment]
> I believe `StateIndex` is a pytree. It just subclasses `eqx.Module` in the usual way.

Hmm, I think you're mistaken.  The `init` field is dynamic can be set `object()`, which is not a pytree.  Therefore, `StateIndex` is not a pytree.

> you're trying to avoid having non-arrays in its PyTree structure.

Not exactly.  I'm avoiding have non-pytrees in dynamic parameters.  Another alternative would be to use a sentinel that's a pytree.

> On your latter point: note that it's not possible to have a module declare its static fields at class definition time. Consider for example `eqx.nn.MLP.activation`, which may be a 'static' `jax.nn.relu` or a 'dynamic' `eqx.nn.PReLU`.

You can just make the field dynamic and wrap the static value (`jax.nn.relu`) in a `Module` like this:
```python
class JaxActivation(Module):
    f: Callable[[Array], Array] = eqx.field(static=True)
```

**Comment by patrick-kidger** [comment]
All types are pytrees. JAX is explicit about the fact that even `object()` is a valid pytree leaf -- see the first code block here: https://jax.readthedocs.io/en/latest/working-with-pytrees.html The only distinction between types is whether they are pytree nodes or pytree leaves.

Anyway, to ease use of `jax.jit` -- which accepts specifically `PyTree[ArrayLike]` and not `PyTree[Any]` -- then `eqx.nn` does generally try to mark known-static fields as static. I'll continue discussion on your PR over there; as I say I think this is a reasonable QoL improvement.

**Comment by NeilGirdhar** [comment]
> All types are pytrees. JAX is explicit about the fact that even `object()` is a valid pytree leaf

Ah, okay!  I'm using the wrong terminology.  Let's say "flattenable" then?  That is, things that can be passed dynamically to a function decorated by jax.jit.   In Flax, they used to call this `pytree_like`, which is where I got the terminology.

>  I say I think this is a reasonable QoL improvement.

Great!  Thanks.
