### ISSUE TITLE
Entering `while_loop` when condition is `False`

### ISSUE THREAD

**Issue by dkweiss31** [patrick-kidger/equinox#870]
Hi Patrick! I'm running into a strange issue with `while_loop`s where sometimes the code enters the loop body when the condition is false. As I mentioned before I'm trying to do quantum trajectories simulations with diffrax and equinox where I wrap diffeqsolve in a while_loop. Here is a minimal example that reproduces the issue. Note that interestingly, this issue only crops up when I wrap `loop_over_jumps` in `vmap`: in testing if I just call it for a specific `key` I haven't reproduced the error. This code fails on the `error_if`.

```python
import diffrax as dx
import equinox as eqx
import jax
import jax.numpy as jnp
import optimistix as optx


class State(eqx.Module):
    final_state: jax.Array
    final_time: float
    key: jax.random.PRNGKey


def norm(y):
    return jnp.linalg.norm(y, axis=(-1, -2)).real


def _run(_y0, _tsave, _rand):
    def vector_field(t, y, _):
        y = -1j * (H - 1j * 0.5 * jump_ops[0].mT @ jump_ops[0]) @ y
        return y

    def cond_fn(t, y, *args, **kwargs):
        return norm(y) ** 2 - _rand

    solution = dx.diffeqsolve(
        dx.ODETerm(vector_field),
        dx.Tsit5(),
        t0=_tsave[0],
        t1=_tsave[-1],
        dt0=_tsave[1] - _tsave[0],
        y0=_y0,
        saveat=dx.SaveAt(t1=True),
        event=dx.Event(cond_fn, optx.Newton(1e-5, 1e-5, optx.rms_norm)),
    )
    return solution


def loop_over_jumps(key, no_jump_prob):
    rand_key, next_key = jax.random.split(key)
    rand = jax.random.uniform(rand_key, minval=no_jump_prob)
    first_result = _run(y0, tsave, rand)  # run until first termination
    state = State(
        final_state=first_result.ys[0, :, :],
        final_time=first_result.ts[0],
        key=next_key,
    )

    def outer_cond_fun(_state):  # enter the loop if we need to apply a jump and then restart
        return _state.final_time < tsave[-1]

    def outer_body_fun(_state):
        jump_time = eqx.internal.error_if(
            _state.final_time, _state.final_time >= tsave[-1], msg='Incorrectly entered the while loop',
        )
        _next_key, _rand_key = jax.random.split(_state.key, num=2)
        psi_after_jump = jump_ops[0] @ _state.final_state  # apply the jump
        psi_after_jump = psi_after_jump / norm(psi_after_jump)  # normalize the new state
        new_times = jnp.linspace(jump_time, tsave[-1], len(tsave))
        _rand = jax.random.uniform(_rand_key)
        result_after_jump = _run(psi_after_jump, new_times, _rand)
        return State(
            final_state=result_after_jump.ys[0],
            final_time=result_after_jump.ts[0],
            key=_next_key,
        )

    return eqx.internal.while_loop(
        outer_cond_fun, outer_body_fun, state, max_steps=100, kind='checkpointed'
    )


dim = 3
a = jnp.diag(jnp.sqrt(jnp.arange(1, stop=dim, dtype=complex)), k=1)
jump_ops = [0.1 * a]
y0 = jnp.array([0.0, 0.0, 1.0], dtype=complex)[..., None]
H = 0.0 * a
tsave = jnp.linspace(0.0, 50, 31)
keys = jax.random.split(jax.random.PRNGKey(31), 4)
result = jax.vmap(loop_over_jumps, in_axes=(0, None))(keys, 0.9)  # Incorrectly entered the while loop
```

**Comment by patrick-kidger** [comment]
So the way that vmap-of-loop works is that once a batch element has finished iterating, then we continue to evaluate the body function on the final element, and then `jnp.where` it away. JAX itself has the same behaviour:
```python
import equinox as eqx
import jax

def cond_fn(x):
    return x < 5

def body_fn(x):
    x = eqx.error_if(x, x >= 5, "egads")
    return x + 1

def run(init):
    return jax.lax.while_loop(cond_fn, body_fn, init)

jax.vmap(run)(jax.numpy.array([2, 4]))
```
This can definitely be a bit surprising, but is ultimately due to the fact that JAX doesn't handle dynamic batch sizes. As such we have to evaluate that final body function on *something* whilst waiting for the other batch elements to complete. (And there isn't necessarily a 'known safe' value to use: if `cond_fn(init) == False` for a batch element, then even the initial condition might not be suitable.)

This is another flavour of the better-known 'vmap of cond turns into select' gotcha.

**Comment by dkweiss31** [comment]
I see, Thanks for the clear explanation! This is a pretty sharp bit, I might submit something to the JAX folks to get it added to the sharp bits page.

The reason this is actually a problem for me is that I fit a spline to each intermediate result for saving at the times the user actually specified. My code then fails the check [here](https://github.com/patrick-kidger/diffrax/blob/ada5229c46ed041b30090b969f9943082e5300d6/diffrax/_global_interpolation.py#L408), since every value in `ts` is the final time. I guess a solution would be to have a cond inside of the body, executing the body when appropriate and returning the previous state otherwise?

**Comment by dkweiss31** [comment]
Nope, this runs exactly into your 'vmap of cond turns into select' gotcha 🤦‍♂️ , sigh. I'll keep tinkering!

**Comment by dkweiss31** [comment]
Sorry for spam: just wanted to say that a simple `where` check on the times I send to the interpolator fixes the problem :)
