### ISSUE TITLE
Pretty-print trees as tree diagrams

### ISSUE THREAD

**Issue by patrick-kidger** [patrick-kidger/equinox#88]
This looks like it might be a bit of fun to try when displaying PyTrees i.e. models:

https://github.com/AharonSambol/PrettyPrintTree

**Comment by ASEM000** [comment]
Hey Patrick,
I think translating the module to the GitHub-compatible mermaid flowchart* would also be great. 
For instance, you could have the model and its mermaid flowchart in the same directory.
I tried to work on this idea for my repo**,  but it seems like it needs a bit of time.

*https://mermaid-js.github.io/mermaid/#/flowchart
**https://github.com/ASEM000/pytreeclass
