### ISSUE TITLE
Is Equinox compatible with Flax?

### ISSUE THREAD

**Issue by jeertmans** [patrick-kidger/equinox#886]
Hello!

I use Equinox everywhere in my code (especially to create classes that are PyTrees), and creating ML models is pretty simple thanks to your library.

However, there exists plenty of ML "frameworks" for JAX, and each framework has its own pros and cons. I am now facing an "issue", as I want to integrate $\mathrm{E}(3)$-equivariant modules in my code, and, to my best knowledge, the only libraries available are using Flax, e.g., [E3x](https://github.com/google-research/e3x) (the "old" `linen` module, not `nnx`).

I guess I am not the first one trying to mix multiple frameworks, and I was wondering if you had recommendations / knowledge about this?

E.g., should I rather stick with Flax for the ML:

```python
class MyModule(equinox.Module):
  ...

class EquivariantModel(flax.linen.Module):
  features = 8
  max_degree = 2

  @flax.linen.compact
  def __call__(self, x: MyModule):
    ...
```

Or is it better to put layers as dataclass attributes, and go the usual "Equinox" way?

```python
class Model(equinox.Module):
  layer: e3x.nn.TensorDense
```

I just wanted to know if you had an opinion or experience on that question?

**Comment by patrick-kidger** [comment]
Given the preferences you've expressed -- using Equinox as your main NN library -- then I suspect the best thing to do will be something like this:
```python
class Foo(flax.linen.Module): ...

class FlaxToEquinox(eqx.Module):
    params: PyTree[Array]
    flax_model: flax.linen.Module = eqx.field(static=True)

    def __init__(self, flax_model: flax.linen.Module):
        self.params = flax_model.init(...)
        self.flax_model = flax_model

    def __call__(self, ...):
        return self.flax_model.apply(self.params, ...)

model = FlaxToEquinox(Foo(...))
```
and then never have to think about the underlying Flax model at all -- just do Equinox as normal.

**Comment by patrick-kidger** [comment]
Not that I know of, I'm afraid. I think that's just a limitation of Flax.

**Comment by jeertmans** [comment]
No issue, you already answered the main question here :)

Thanks!
