### ISSUE TITLE
Incompatibility with jax 0.4.34 (and 0.4.35)

### ISSUE THREAD

**Issue by Prsodk** [patrick-kidger/equinox#892]
After making a new environment, I got the following errors. After downgrading to jax 0.4.33, the code worked again. 
The problem is most likely a problem in Optax 0.2.3 (latest version available with pip), possibly connected with weight decay.

[jax_error.txt](https://github.com/user-attachments/files/17621713/jax_error.txt)

I have not reported at optax.

:)

**Comment by Prsodk** [comment]
Thank you. I have installed from github now. And it works. There are some performance drawdown at the moment:
[mnist_training.txt](https://github.com/user-attachments/files/17623139/mnist_training.txt)

**Comment by patrick-kidger** [comment]
I've seen a few such reports for recent versions of JAX. If you can produce a MWE then I'd recommend raising the performance differences on the JAX GitHub.
