### ISSUE TITLE
Speeding up module creation

### ISSUE THREAD

**Issue by lockwo** [patrick-kidger/equinox#899]
If you are creating many modules (thousands or millions), the slowdown in class creation over python becomes quite noticeable. In my specific application, I could change to python classes and it was fine, but I'm curious in general if there's a way to accelerate it?

MVC

```python
class A(eqx.Module):
  w: str

  def __init__(self):
    self.w = "hi"
  
class B:
  def __init__(self):
    self.w = "hi"

%timeit a = A()

%timeit a = B()
```

`30.3 µs ± 649 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)`

`250 ns ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)`

**Comment by johannahaffner** [comment]
Hi! 

I took a look at this, and I think this overhead can't be optimised away.  Given that the Module [metaclass](https://github.com/patrick-kidger/equinox/blob/15a800dd0ab1fc91b033c9305a5fe2f7bf2aecae/equinox/_module.py#L179) runs several hundred lines of Python control flow to check if certain properties hold and enforce them if not, it makes sense to me that this takes a few microseconds.

To test this, I had slightly expanded your MWE - the overhead is not data classification, or pytree registration, but checking for all the desirable things we want equinox modules to have. And that is quite a bit more than data class or registered pytrees would provide!

```python
from dataclasses import dataclass

import equinox as eqx
import jax.tree_util as jtu


class A(eqx.Module):
    w: str

    def __init__(self):
        self.w = "hi"
  
class B:
    def __init__(self):
        self.w = "hi"

@dataclass
class C: 
    def __init__(self):
        self.w = "hi"

@jtu.register_pytree_node_class
class D:
    def __init__(self):
        self.w = "hi"

    def tree_flatten(self):
        return ((), self.w)
    
    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)
    

%timeit -r7 -n100000 a = A()
%timeit -r7 -n100000 b = B()
%timeit -r7 -n100000 c = C()
%timeit -r7 -n100000 d = D()

a = A()
bye = "bye"
get = lambda x: x.w  
%timeit -r7 -n100000 e = eqx.tree_at(get, a, bye)
```

**Comment by patrick-kidger** [comment]
Thank you for the analysis Johanna!

I'll also note that usually this overhead goes unnoticed as most of it disappears under JIT-compilation, so it's only those handful of classes which are instantiated outside of a JIT'd region that affect anything.

**Comment by lockwo** [comment]
Makes sense, this outside of `jit` performance is definitely an edge case/not something usually optimized for
