### ISSUE TITLE
How to switch between different objectives without re-JITing. 

### ISSUE THREAD

**Issue by adam-hartshorne** [patrick-kidger/equinox#912]
I have the following architecture of Equinox modules. Where the output of Module A goes into Module B and Module C. The output of B and C are then combined and I wish to optimise the loss between 1) B & Data, 2) B & C using Optax. 

If I try to train these simultaneously, it won't work very well. So I wish to do the following is a tik tok style training whereby, 

1) for x epochs, train to optimise Loss(B, Data) with parameters of C are frozen (or if possible not even calling C).
then
2) for y epochs, train to optimise Loss(B,C), where A and B parameters are frozen.

Ideally, I want a warmup period of just 1), then start to TikTok between scenarios 1 and 2.

![equinox_model](https://github.com/user-attachments/assets/d109f06b-e07c-4d40-bc0f-f4c018e3906c)

**Comment by patrick-kidger** [comment]
Makes sense. What's the problem with re-JIT'ing though? Just have a boolean flag indicating which of the two scenarios you are in, and then when it toggles you'll re-JIT once and then be good to go.

(If you really needed you could avoid re-JIT'ing by using `lax.cond` though.)

**Comment by adam-hartshorne** [comment]
Perfect. Thanks
