### ISSUE TITLE
Sharding Question

### ISSUE THREAD

**Issue by adam-hartshorne** [patrick-kidger/equinox#921]
When using eqx.filter_shard to shard data of shape (n,m,p) on a GPU 

```
num_devices = 8
devices = mesh_utils.create_device_mesh((num_devices, 1))
sharding = jshard.PositionalSharding(devices)
replicated = sharding.replicate()
data = eqx.filter_shard(data, sharding)
```

this fails because lax.with_sharding_constraint expects data shape to be values of rank 2. 

I understand that you can shard say a device_mesh of (N, M) (where N and M are divisors of n and m, and then JAX will shard the n dim, then the m dim, but in my case it isn't valid to do so. 

And I could flatten the data to 2-rank tensor manually, but just wondering if I missing something that does allow to handle situation where the data tensor is a shape of rank something other than 2?

**Comment by patrick-kidger** [comment]
Yup, this is expected -- see also https://github.com/patrick-kidger/equinox/issues/755. It's just how JAX works with `lax.with_sharding_constraint`. I don't think I have a better answer for you unfortunately :)

**Comment by adam-hartshorne** [comment]
Thanks for the quick response.
