### ISSUE TITLE
TypeError: unhashable type: 'numpy.ndarray'

### ISSUE THREAD

**Issue by conceptofmind** [patrick-kidger/equinox#95]
Hello,

I was following through the RNN documentation while attempting to implement the PaLM model from this [library](https://github.com/lucidrains/PaLM-jax). I have previously contributed to some of lucidrains PyTorch implementations before and was working on an example for the JAX version of PaLM. When using `eqx.filter_jit` on the train_step function I receive the error:

**ValueError: Non-hashable static arguments are not supported. An error occured during a call to 'train_step' while trying to hash an object of type <class 'tuple'>... The error was: TypeError: unhashable type: 'numpy.ndarray'**

Do you have any idea why this may occur?

I greatly appreciate your time and help.

Thank you,

Enrico

The enwik8 data was downloaded from the Hutter prize page: http://prize.hutter1.net/

Code:
```
from random import randrange
import tqdm
import gzip
import numpy as np

from torch.utils.data import DataLoader, Dataset

import jax
from jax import nn
from optax import adam, clip_by_global_norm, chain, apply_every

# https://github.com/lucidrains/PaLM-jax
from palm_jax import PaLM

import equinox as eqx

# constants

NUM_BATCHES = int(1e5)
BATCH_SIZE = 4
GRADIENT_ACCUMULATE_EVERY = 4
LEARNING_RATE = 2e-4
MAX_GRAD_NORM = 0.5
VALIDATE_EVERY  = 100
SAMPLE_EVERY  = 500
SEQ_LEN = 1024

# helpers

def cycle(loader):
    while True:
        for data in loader:
            yield data

def decode_token(token):
    return str(chr(max(32, token)))

def decode_tokens(tokens):
    return ''.join(list(map(decode_token, tokens)))

# prepare enwik8 data

with gzip.open('../datasets/enwik8.gz') as file:
    X = np.fromstring(file.read(int(95e6)), dtype=np.uint8)
    data_train, data_val = np.split(X, [int(90e6)])

class TextSamplerDataset(Dataset):
    def __init__(self, data, seq_len):
        super().__init__()
        self.data = data
        self.seq_len = seq_len

    def __getitem__(self, index):
        rand_start = randrange(0, self.data.shape[0] - self.seq_len - 1)
        return self.data[rand_start: rand_start + self.seq_len + 1]

    def __len__(self):
        return self.data.shape[0] // self.seq_len

train_dataset = TextSamplerDataset(data_train, SEQ_LEN)
train_loader  = cycle(DataLoader(train_dataset, batch_size = BATCH_SIZE))

# setup model and params

key = jax.random.PRNGKey(0)

model = PaLM(
    num_tokens = 256,
    dim = 512,
    depth=12,
    heads=8,
    dim_head=64,
    key = key
)

# cross entropy loss

def cross_entropy(logits, targets, axis = -1):
    logprobs = nn.log_softmax(logits, axis = axis)
    nll = np.take_along_axis(logprobs, np.expand_dims(targets, axis = axis), axis = axis)
    ce = -np.mean(nll)
    return ce

@eqx.filter_value_and_grad
def loss_fn(model, data):
    inp, labels = data[:, :-1], data[:, 1:]
    logits = jax.vmap(model)(inp)
    return cross_entropy(logits, labels, axis = -1)

# optimizer

optim = chain(
    clip_by_global_norm(MAX_GRAD_NORM),
    adam(LEARNING_RATE),
    apply_every(GRADIENT_ACCUMULATE_EVERY)
)

optim_state = optim.init(model)

# train step

@eqx.filter_jit
def train_step(model, data, optim_state):
    loss, grads = loss_fn(model, data)
    updates, optim_state = optim.update(grads, optim_state)
    model = eqx.apply_updates(model, updates)
    return model, optim_state, loss

# training

for i in tqdm.tqdm(range(NUM_BATCHES), mininterval=10., desc='training'):
    data = next(train_loader).numpy()
    model, optim_state, loss = train_step(model, data, optim_state)
    if i % GRADIENT_ACCUMULATE_EVERY == 0:
        print(f'loss: {loss.item()}')
```

**Comment by patrick-kidger** [comment]
Hey there. So JAX's JIT compiler works by separating arguments into those that are:

1. "traced". These are inputs into the compiled XLA computation graph, which is a DAG of operations between arrays. When you call your Python-level function, all traced arguments are replaced with special tracer objects that record the computations applied to them; the resulting recording is what is lowered to XLA and compiled.
2. "static". These are inputs to the Python function that are passed through unchanged. Typically their values will determine the structure of the computation graph that is built. (In whatever way you see fit.) It is a requirement that all static arguments be hashable and eq-able.

By default `jax.jit` requires that you manually specify which arguments are traced and which are static. (`jax.jit(..., static_argnums=...)`. Equinox aims to be more ergonomic by determining this automatically, using the filtering rules provided. By default this corresponds to tracing all JAX arrays and static'ing everything else; in practice this is what is desired 99% of the time.

Now NumPy arrays aren't JAX arrays, so according to the above default they're static. But NumPy arrays aren't hashable.

You should either change the filter rule used with `eqx.filter_jit` so as to trace them, or wrap the array in a hashable wrapper to static them.

Equinox deliberately doesn't provide a default either way as both approaches are reasonable, so it's better to raise an error and let the user explicitly specify which behaviour is desired.

**Comment by conceptofmind** [comment]
Hi @patrick-kidger ,

Thank you for taking the time to answer my question. 

I re-reviewed the equinox documentation and changed the filtering rule in `eqx.filter_jit` to include `data`: `@eqx.filter_jit(kwargs=dict(data=True))`. This seems to have resolved the value error above and loss decreases normally. I will have to do a further review of the JAX documentation to ensure everything is running optimally.

I am working on a full pre-training example integrated with HuggingFace, tfds, etc., and will link it after if it proves to be beneficial for showing a use-case with the equinox library. 

I appreciate the information and help.

Thank you,

Enrico
